// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_c_firemage : GeneralScript
{
	protected override void Load()
	{
		AddNpc(1, 20027, "Pyromancer Master", "c_firemage", -172.0, 6.0, -7.0, -41.080002, "MASTER_FIREMAGE", "", "", -2, 20.0);
		AddNpc(3, 20041, "", "c_firemage", 195.0, 3.0, 5.0, 0.0, "", "MASTER_FIREMAGE_BOX_TRIGGER", "", -2, 50.0);
	}
}
