// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_c_highlander : GeneralScript
{
	protected override void Load()
	{
		AddNpc(1, 20029, "Highlander Master", "c_highlander", 6.0, 0.0, 59.0, 0.0, "MASTER_HIGHLANDER", "", "", -2, 20.0);
		AddNpc(22, 20041, "", "c_highlander", 98.0, 0.0, 116.0, 0.0, "", "JOB_KLAIPE_TRIGGER", "", -2, 100.0);
		AddNpc(23, 20026, "", "c_highlander", 83.490356, 0.7928, 69.787071, 0.0, "", "WOOD_CARVING_SESSION_CREATE", "WOOD_CARVING_SESSION_DESTROY", -2, 250.0);
	}
}
