// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_c_nunnery : GeneralScript
{
	protected override void Load()
	{
		AddNpc(11, 153142, "Sister 1", "c_nunnery", 14.0, -57.0, -97.0, 315.0, "REQUEST_MISSION_ABBEY", "TUTO_SAALUS_NUNNERY_CHECK", "", -2, 100.0);
		AddNpc(13, 153143, "Sister 2", "c_nunnery", 201.0, -75.0, 37.0, 315.0, "C_NUNNERY_NPC1", "TUTO_UPHILL_DEFENSE_CHECK", "", -2, 100.0);
		AddNpc(15, 153170, "Enchanter Master", "c_nunnery", 320.950226, -49.580482, 282.752106, -103.0, "ENCHANTER_MASTER", "", "", -2, 40.0);
		AddNpc(16, 20103, "Merchant 2", "c_nunnery", 506.48111, -28.620001, -335.4216, 0.0, "HT_ESCAPE_MERCHANT", "", "", -2, 40.0);
		AddNpc(17, 20156, "Gentleman 10", "c_nunnery", 331.359741, -75.849998, -188.077759, 0.0, "KEY_QUEST_NPC_NUNNERY", "", "", -2, 40.0);
	}
}
