// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_c_voodoo : GeneralScript
{
	protected override void Load()
	{
		AddNpc(1, 20136, "Bokor Mama", "c_voodoo", -22.0, 0.0, 32.0, 270.0, "MASTER_BOCORS", "", "", -2, 20.0);
	}
}
