// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_d_cathedral_53 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(25, 147398, "Saule God2", "d_cathedral_53", 295.436981, 0.0003, -199.013428, -141.0, "", "", "", -2, 100.0);
		AddNpc(26, 147389, "Saule God1", "d_cathedral_53", 230.067673, 0.0003, -218.008896, 16.0, "", "", "", -2, 100.0);
	}
}
