// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_d_cathedral_54 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(19, 147389, "Saule God1", "d_cathedral_54", -970.276672, 3.8507, -618.525574, 26.0, "", "", "", -2, 100.0);
	}
}
