// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_d_cmine_8 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(700, 147392, "Treasure Box 1", "d_cmine_8", 140.289993, 9.16, 191.320007, 178.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(1072, 20041, "", "d_cmine_8", 2632.0, -183.0, 2219.0, 0.0, "", "REPEAT_MON_GEN_TRIGGER", "", -2, 10.0);
		AddNpc(1076, 20165, "City Middle-Aged Man", "d_cmine_8", -1376.40625, 57.5569, -826.448059, -39.0, "KLAIPE_HQ_02_NPC", "", "", -2, 40.0);
		AddNpc(1077, 40095, "", "d_cmine_8", -1372.0, 59.0, -852.0, 0.0, "KLAIPE_HQ_01_NPC_D", "KLAIPE_HQ_01_NPC_E", "", -2, 40.0);
		AddNpc(1078, 147393, "Treasure Box 3", "d_cmine_8", 2615.0, -185.0, 2262.0, -90.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(1086, 155000, "Crystal Processing Device", "d_cmine_8", -1455.132324, 71.926796, 248.012054, 148.0, "CRYSTAL_MACHINE", "", "", -2, 40.0);
		AddNpc(1087, 155020, "Melody Crystal", "d_cmine_8", -1439.498291, 140.688995, 889.50708, -90.0, "", "", "", -2, 40.0);
		AddNpc(1087, 155020, "Melody Crystal", "d_cmine_8", -522.680908, -22.993967, 980.538391, -90.0, "", "", "", -2, 40.0);
		AddNpc(1087, 155020, "Melody Crystal", "d_cmine_8", -149.250473, 7.4462, -18.783997, -90.0, "", "", "", -2, 40.0);
		AddNpc(1088, 47161, "Lost Stuff Of Vendor 2", "d_cmine_8", -2258.282471, 76.169815, -393.615936, -22.0, "D_CMINE_8_BAG", "", "", -2, 40.0);
		AddNpc(1088, 47161, "Lost Stuff Of Vendor 2", "d_cmine_8", -1235.446533, -64.321297, -1063.332764, -22.0, "D_CMINE_8_BAG", "", "", -2, 40.0);
		AddNpc(1088, 47161, "Lost Stuff Of Vendor 2", "d_cmine_8", 281.249573, 7.4462, 172.768753, -22.0, "D_CMINE_8_BAG", "", "", -2, 40.0);
		AddNpc(1088, 47161, "Lost Stuff Of Vendor 2", "d_cmine_8", 1117.186279, -49.774799, -80.433083, -22.0, "D_CMINE_8_BAG", "", "", -2, 40.0);
		AddNpc(1088, 47161, "Lost Stuff Of Vendor 2", "d_cmine_8", 1830.75769, -183.068695, 1928.846191, -22.0, "D_CMINE_8_BAG", "", "", -2, 40.0);
		AddNpc(1095, 147503, "Spell Gear", "d_cmine_8", -1084.61438, 4.8904, -584.17218, 0.0, "", "", "", -2, 40.0);
		AddNpc(1095, 147503, "Spell Gear", "d_cmine_8", 608.995667, -136.232025, 1120.479858, 0.0, "", "", "", -2, 40.0);
		AddNpc(1096, 147503, "Spell Gear", "d_cmine_8", -1571.317383, 140.688995, 866.015015, 0.0, "", "", "", -2, 40.0);
		AddNpc(1096, 147503, "Spell Gear", "d_cmine_8", 992.440735, -49.774799, 187.07608, 0.0, "", "", "", -2, 40.0);
		AddNpc(1097, 147503, "Spell Gear", "d_cmine_8", -88.299377, 7.4462, -156.16626, 0.0, "", "", "", -2, 40.0);
		AddNpc(1097, 147503, "Spell Gear", "d_cmine_8", 2779.585205, -183.068695, 1975.99939, 0.0, "", "", "", -2, 40.0);
		AddNpc(1098, 40095, "", "d_cmine_8", -1439.498291, 140.688995, 889.50708, 0.0, "D_CMINE_8_JUKEBOX", "", "", -2, 40.0);
		AddNpc(1098, 40095, "", "d_cmine_8", -522.680908, -22.993967, 980.538391, 0.0, "D_CMINE_8_JUKEBOX", "", "", -2, 40.0);
		AddNpc(1098, 40095, "", "d_cmine_8", -149.250473, 7.4462, -18.783997, 0.0, "D_CMINE_8_JUKEBOX", "", "", -2, 40.0);
		AddNpc(1099, 151006, "Purifier", "d_cmine_8", -2827.543945, 73.2211, -64.025238, -73.0, "", "", "", -2, 40.0);
		AddNpc(1099, 151006, "Purifier", "d_cmine_8", -1207.39209, -64.321297, -1002.802979, -23.0, "", "", "", -2, 40.0);
		AddNpc(1099, 151006, "Purifier", "d_cmine_8", -237.956482, -24.804523, 1107.556763, -96.0, "", "", "", -2, 40.0);
		AddNpc(1099, 151006, "Purifier", "d_cmine_8", 849.203003, -93.170998, 1371.261353, -50.0, "", "", "", -2, 40.0);
		AddNpc(1099, 151006, "Purifier", "d_cmine_8", 955.431274, -49.774799, 567.375549, -3.0, "", "", "", -2, 40.0);
		AddNpc(1099, 151006, "Purifier", "d_cmine_8", 2005.62439, -183.068695, 1798.464722, -122.0, "", "", "", -2, 40.0);
		AddNpc(1103, 40095, "", "d_cmine_8", -1590.405762, 72.295776, 58.780037, 0.0, "PARTY_Q_011_CHAMICAL01", "", "", -2, 40.0);
		AddNpc(1107, 152022, "Small Pot", "d_cmine_8", -1589.045898, 72.298378, 60.07848, 0.0, "PARTY_Q_011_MACHIN01", "", "", -2, 40.0);
		AddNpc(1109, 40030, "Treasure Chest", "d_cmine_8", 1805.0, -179.0, 1854.0, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
	}
}
