// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_d_cmine_01 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(100, 20110, "Miners' Village Alchemist", "d_cmine_01", -1188.0, 317.0, -1799.0, 0.0, "MINE_1_ALCHEMIST", "", "", -2, 400.0);
		AddNpc(101, 151006, "Purifier", "d_cmine_01", -881.872375, 183.700821, -1246.434448, 0.0, "MINE_1_PURIFY_1", "", "", -2, 40.0);
		AddNpc(105, 151006, "Purifier", "d_cmine_01", 33.130001, 184.139999, -44.16, -85.0, "MINE_1_PURIFY_5", "", "", -2, 40.0);
		AddNpc(107, 151006, "Purifier", "d_cmine_01", -341.709991, 111.379997, 992.150024, 0.0, "MINE_1_PURIFY_7", "", "", -2, 40.0);
		AddNpc(112, 147453, "Crystal Basket", "d_cmine_01", 748.169983, 17.459999, 103.720001, -95.0, "MINE_1_CRYSTAL_10", "", "", -2, 70.0);
		AddNpc(525, 20041, "", "d_cmine_01", 343.0, 111.0, 523.0, 0.0, "", "REPEAT_MON_GEN_TRIGGER", "", -2, 10.0);
		AddNpc(528, 20026, "", "d_cmine_01", 1196.969971, 3.59, 195.800003, 0.0, "", "JOB_HIGHLANDER4_3", "", -2, 120.0);
		AddNpc(533, 40030, "Treasure Chest", "d_cmine_01", 1316.0, 4.0, 730.0, 270.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(536, 151015, "Purifier Parts 1", "d_cmine_01", -1035.849976, 181.899994, -1460.689941, 0.0, "MINE_1_CRYSTAL_4", "", "", -2, 40.0);
		AddNpc(536, 151015, "Purifier Parts 1", "d_cmine_01", -743.190002, 181.470001, -85.559998, 0.0, "MINE_1_CRYSTAL_4", "", "", -2, 40.0);
		AddNpc(537, 20026, "", "d_cmine_01", 1287.0, 33.0, -994.0, 0.0, "", "MINE_1_CRYSTAL_9_TRIGGER", "", -2, 300.0);
		AddNpc(538, 151006, "Purifier", "d_cmine_01", 1417.73999, 32.720001, -913.539978, -90.0, "MINE_1_CRYSTAL_9_DEVICE", "", "", -2, 40.0);
		AddNpc(539, 20026, "", "d_cmine_01", -1125.76001, 111.379997, 427.640015, 0.0, "", "MINE_1_CRYSTAL_18_TRIGGER", "", -2, 300.0);
		AddNpc(540, 151008, "Mine Lift", "d_cmine_01", -1501.22998, 189.360001, 706.830017, -106.019997, "", "MINE_1_ELEVATOR", "", -2, 40.0);
		AddNpc(541, 147392, "Treasure Box 1", "d_cmine_01", 645.390015, 17.75, -27.959999, -90.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(542, 147392, "Treasure Box 1", "d_cmine_01", 331.209991, 111.480003, 494.600006, -90.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(543, 147392, "Treasure Box 1", "d_cmine_01", -1542.959961, 154.800003, 494.070007, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
	}
}
