// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_d_cmine_9 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(1026, 155013, "Red Crystal", "d_cmine_9", 147.0, -50.0, -947.0, 0.0, "D_CMINE_9_RED", "", "", -2, 40.0);
		AddNpc(1027, 155014, "Blue Crystal", "d_cmine_9", 623.935974, 261.99707, 81.737274, 0.0, "D_CMINE_9_BLUE", "", "", -2, 1.0);
		AddNpc(1028, 155015, "Yellow Crystal", "d_cmine_9", -610.702209, 408.634369, 375.548065, 0.0, "D_CMINE_9_YELLOW", "", "", -2, 40.0);
		AddNpc(1042, 40070, "Bulletin Board", "d_cmine_9", -437.660339, 398.509308, 572.383972, -46.0, "D_CMINE_9_WARNING", "", "", -2, 40.0);
		AddNpc(1047, 47124, "Magic Circle", "d_cmine_9", -367.542755, 397.564667, 596.727722, 0.0, "", "D_CMINE_9_DROPSTONET", "", -2, 5.0);
		AddNpc(1047, 47124, "Magic Circle", "d_cmine_9", -499.821899, 396.256866, 828.263977, 0.0, "", "D_CMINE_9_DROPSTONET", "", -2, 5.0);
		AddNpc(1047, 47124, "Magic Circle", "d_cmine_9", -324.602081, 355.327148, 976.861023, 0.0, "", "D_CMINE_9_DROPSTONET", "", -2, 5.0);
		AddNpc(1048, 47124, "Magic Circle", "d_cmine_9", -188.505417, 321.367493, 809.814819, 0.0, "", "D_CMINE_9_DROPSTONET", "", -2, 5.0);
		AddNpc(1048, 47124, "Magic Circle", "d_cmine_9", -46.276516, 272.036163, 572.529175, 0.0, "", "D_CMINE_9_DROPSTONET", "", -2, 5.0);
		AddNpc(1048, 47124, "Magic Circle", "d_cmine_9", -193.360107, 191.288269, 255.957153, 0.0, "", "D_CMINE_9_DROPSTONET", "", -2, 5.0);
		AddNpc(1049, 47124, "Magic Circle", "d_cmine_9", -492.289917, 87.868813, -111.718407, 0.0, "", "D_CMINE_9_DROPSTONET", "", -2, 5.0);
		AddNpc(1049, 47124, "Magic Circle", "d_cmine_9", -731.580078, 60.706509, -390.534241, 0.0, "", "D_CMINE_9_DROPSTONET", "", -2, 5.0);
		AddNpc(1049, 47124, "Magic Circle", "d_cmine_9", -769.621277, 0.325253, -717.238098, 0.0, "", "D_CMINE_9_DROPSTONET", "", -2, 5.0);
		AddNpc(1054, 147392, "Treasure Box 1", "d_cmine_9", 667.0, 229.0, 1447.0, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
	}
}
