// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_d_cmine_6 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(5, 151014, "Modify Wall", "d_cmine_6", 129.080002, 183.639999, -112.43, -86.0, "CMINE3_BOSSROOM_OPEN", "", "", -2, 100.0);
		AddNpc(10, 20110, "Miners' Village Alchemist", "d_cmine_6", -2181.0, 360.0, -1677.0, 0.0, "MINE_3_ALCHEMIST", "", "", -2, 400.0);
		AddNpc(11, 20041, "", "d_cmine_6", -1251.0, 316.0, -1730.0, 0.0, "", "MINE_3_RESQUE1", "", -2, 50.0);
		AddNpc(12, 20041, "", "d_cmine_6", -736.0, 182.0, -1326.0, 0.0, "", "MINE_3_RESQUE2", "", -2, 200.0);
		AddNpc(13, 151013, "Mine Crystal", "d_cmine_6", -659.0, 181.610001, 4.0, 0.0, "MINE_3_RESQUE3", "", "", -2, 30.0);
		AddNpc(14, 151009, "Miner", "d_cmine_6", -1187.670044, 303.48999, 104.160004, -62.0, "MINE_3_RESIENT1_BIND", "", "", -2, 40.0);
		AddNpc(15, 151012, "Miner Girl Laima", "d_cmine_6", -1206.569946, 303.48999, 87.32, -18.0, "MINE_3_GIRL_BIND", "", "", -2, 40.0);
		AddNpc(16, 20041, "", "d_cmine_6", 2103.432861, 124.675529, 1956.925537, 0.0, "", "MINE_3_BOSS", "", -2, 160.0);
		AddNpc(17, 20041, "", "d_cmine_6", -458.0, 183.0, -873.0, 0.0, "", "MINE_3_DEFENCE1", "", -2, 100.0);
		AddNpc(18, 47233, "Crystal Pillar", "d_cmine_6", 2048.030029, 56.93, 1753.449951, 153.0, "CMINE6_TO_KATYN7_1_START", "", "", -2, 100.0);
		AddNpc(514, 151010, "Miner'S Wife", "d_cmine_6", -1170.0, 303.0, 120.0, -13.0, "D_CMINE_NPC01_BIND", "", "", -2, 0.0);
		AddNpc(515, 151011, "Miner Lady", "d_cmine_6", -1200.25, 303.48999, 98.059998, -85.0, "D_CMINE_NPC02_BIND", "", "", -2, 0.0);
		AddNpc(516, 20041, "", "d_cmine_6", -446.0, 183.0, -1014.0, 0.0, "", "REPEAT_MON_GEN_TRIGGER", "", -2, 10.0);
		AddNpc(522, 20041, "", "d_cmine_6", 1673.233032, 151.045227, 1167.976929, 0.0, "", "CMINE_6_CMINE_8", "", -2, 30.0);
		AddNpc(530, 147392, "Treasure Box 1", "d_cmine_6", -1145.180054, 303.589996, 103.150002, -90.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(531, 20150, "Veteran Miner 2", "d_cmine_6", -1187.670044, 303.48999, 104.160004, -62.0, "MINE_3_RESIENT1", "", "", -2, 40.0);
		AddNpc(532, 47236, "Girl", "d_cmine_6", -1206.569946, 303.48999, 87.32, -18.0, "MINE_3_GIRL", "", "", -2, 40.0);
		AddNpc(533, 20114, "Marta", "d_cmine_6", -1170.0, 303.0, 120.0, -13.0, "D_CMINE_NPC01", "", "", -2, 0.0);
		AddNpc(534, 147473, "Mira", "d_cmine_6", -1200.25, 303.48999, 98.059998, -85.0, "D_CMINE_NPC02", "", "", -2, 0.0);
		AddNpc(539, 20026, "", "d_cmine_6", 1628.578613, 56.932098, 1610.588989, 0.0, "", "PARTY_Q_TRIGGER", "", -2, 60.0);
		AddNpc(540, 147392, "Treasure Box 1", "d_cmine_6", -874.950012, 184.050003, -970.450012, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(541, 20025, "", "d_cmine_6", -1860.952881, 316.298401, -1691.245972, 0.0, "CMINE6_RP_1_OBJ", "", "", -2, 1.0);
		AddNpc(541, 20025, "", "d_cmine_6", -1765.390869, 316.298401, -1902.164795, 0.0, "CMINE6_RP_1_OBJ", "", "", -2, 1.0);
		AddNpc(541, 20025, "", "d_cmine_6", -985.336792, 181.477234, -1393.180298, 0.0, "CMINE6_RP_1_OBJ", "", "", -2, 1.0);
		AddNpc(541, 20025, "", "d_cmine_6", -729.584106, 184.796616, -816.504456, 0.0, "CMINE6_RP_1_OBJ", "", "", -2, 1.0);
		AddNpc(541, 20025, "", "d_cmine_6", -45.712921, 183.929581, -1201.001465, 0.0, "CMINE6_RP_1_OBJ", "", "", -2, 1.0);
		AddNpc(541, 20025, "", "d_cmine_6", 117.523048, 207.985901, -1377.010864, 0.0, "CMINE6_RP_1_OBJ", "", "", -2, 1.0);
		AddNpc(541, 20025, "", "d_cmine_6", -291.390198, 186.968719, -1539.068237, 0.0, "CMINE6_RP_1_OBJ", "", "", -2, 1.0);
		AddNpc(541, 20025, "", "d_cmine_6", -1985.202881, 360.019897, -1577.897583, 0.0, "CMINE6_RP_1_OBJ", "", "", -2, 1.0);
		AddNpc(541, 20025, "", "d_cmine_6", -505.079071, 183.833374, -587.132568, 0.0, "CMINE6_RP_1_OBJ", "", "", -2, 1.0);
		AddNpc(541, 20025, "", "d_cmine_6", -736.962708, 182.454422, -232.765106, 0.0, "CMINE6_RP_1_OBJ", "", "", -2, 1.0);
		AddNpc(541, 20025, "", "d_cmine_6", -945.065063, 181.6194, -312.944244, 0.0, "CMINE6_RP_1_OBJ", "", "", -2, 1.0);
		AddNpc(541, 20025, "", "d_cmine_6", -664.112061, 181.607086, 77.923798, 0.0, "CMINE6_RP_1_OBJ", "", "", -2, 1.0);
		AddNpc(541, 20025, "", "d_cmine_6", -1236.620239, 303.485291, 75.191002, 0.0, "CMINE6_RP_1_OBJ", "", "", -2, 1.0);
		AddNpc(541, 20025, "", "d_cmine_6", -318.550201, 183.929688, -3.616026, 0.0, "CMINE6_RP_1_OBJ", "", "", -2, 1.0);
		AddNpc(541, 20025, "", "d_cmine_6", 112.760498, 183.929688, -251.7957, 0.0, "CMINE6_RP_1_OBJ", "", "", -2, 1.0);
		AddNpc(541, 20025, "", "d_cmine_6", -15.847622, 183.929581, -941.946411, 0.0, "CMINE6_RP_1_OBJ", "", "", -2, 1.0);
		AddNpc(541, 20025, "", "d_cmine_6", -926.052429, 181.962204, -1228.00647, 0.0, "CMINE6_RP_1_OBJ", "", "", -2, 1.0);
		AddNpc(541, 20025, "", "d_cmine_6", -419.00885, 184.506348, -1357.939331, 0.0, "CMINE6_RP_1_OBJ", "", "", -2, 1.0);
		AddNpc(541, 20025, "", "d_cmine_6", -537.345459, 183.929581, -1095.444702, 0.0, "CMINE6_RP_1_OBJ", "", "", -2, 1.0);
		AddNpc(543, 151006, "Purifier", "d_cmine_6", -79.47718, 183.929581, -989.842102, -25.0, "CMINE6_RP_1_NPC", "", "", -2, 40.0);
		AddNpc(544, 153166, "Magic Core(Small Version)", "d_cmine_6", 1396.073486, 151.107986, 1779.075562, 0.0, "HIDDEN_MIKO_CMINE_6_1", "", "", -2, 40.0);
		AddNpc(545, 153166, "Magic Core(Small Version)", "d_cmine_6", 1402.445068, 151.270828, 1691.67627, 0.0, "HIDDEN_MIKO_CMINE_6_2", "", "", -2, 40.0);
		AddNpc(546, 153166, "Magic Core(Small Version)", "d_cmine_6", 1428.933472, 151.029449, 1593.640747, 0.0, "HIDDEN_MIKO_CMINE_6_3", "", "", -2, 40.0);
		AddNpc(547, 153166, "Magic Core(Small Version)", "d_cmine_6", 1466.929321, 151.164825, 1504.248047, 0.0, "HIDDEN_MIKO_CMINE_6_4", "", "", -2, 40.0);
		AddNpc(548, 153166, "Magic Core(Small Version)", "d_cmine_6", 1513.86499, 151.058685, 1417.911865, 0.0, "HIDDEN_MIKO_CMINE_6_5", "", "", -2, 40.0);
		AddNpc(549, 153166, "Magic Core(Small Version)", "d_cmine_6", 1564.537354, 151.132217, 1336.668213, 0.0, "HIDDEN_MIKO_CMINE_6_6", "", "", -2, 40.0);
		AddNpc(550, 153166, "Magic Core(Small Version)", "d_cmine_6", 1618.951416, 151.115555, 1254.110107, 0.0, "HIDDEN_MIKO_CMINE_6_7", "", "", -2, 40.0);
		AddNpc(551, 40095, "", "d_cmine_6", -1245.036011, 316.298798, -1370.731201, 0.0, "", "EXPLORER_MISLE4", "", -2, 20.0);
	}
}
