// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_d_cmine_02 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(5, 20025, "", "d_cmine_02", 1732.0, -10.0, 145.0, 0.0, "BOOKSHELF_02", "", "", -2, 0.0);
		AddNpc(102, 151006, "Purifier", "d_cmine_02", -1615.406494, 72.020897, 122.423439, -60.0, "MINE_2_PURIFY_1", "", "", -2, 80.0);
		AddNpc(104, 151006, "Purifier", "d_cmine_02", -573.366394, -9.275711, 495.078522, 0.0, "MINE_2_PURIFY_3", "", "", -2, 80.0);
		AddNpc(108, 151006, "Purifier", "d_cmine_02", 524.179138, -23.383429, 364.357819, -30.0, "MINE_2_PURIFY_7", "", "", -2, 80.0);
		AddNpc(150, 20026, "", "d_cmine_02", 1023.0, -91.0, 1181.0, 0.0, "", "JOB_SWORDMAN1", "", -2, 250.0);
		AddNpc(520, 20025, "", "d_cmine_02", 1860.0, -10.0, 580.0, 0.0, "CMINE_02_HIDEMAN", "", "", -2, 30.0);
		AddNpc(521, 20025, "", "d_cmine_02", 1808.0, -11.0, 430.0, 0.0, "CMINE_FOOD_01", "", "", -2, 30.0);
		AddNpc(522, 20025, "", "d_cmine_02", 1822.0, -10.0, 89.0, 0.0, "CMINE_FOOD_04", "", "", -2, 30.0);
		AddNpc(523, 20025, "", "d_cmine_02", 1926.0, -10.0, 384.0, 0.0, "CMINE_FOOD_03", "", "", -2, 30.0);
		AddNpc(528, 20041, "", "d_cmine_02", 116.0, -34.0, 1302.0, 0.0, "", "REPEAT_MON_GEN_TRIGGER", "", -2, 30.0);
		AddNpc(529, 40070, "Bulletin Board", "d_cmine_02", 1537.0, 79.0, 417.0, 270.0, "D_CMINE_02_BOARD01", "", "", -2, 30.0);
		AddNpc(530, 20041, "", "d_cmine_02", 1567.0, 157.0, 1741.0, 0.0, "", "REPEAT_MON_GEN_TRIGGER", "", -2, 40.0);
		AddNpc(539, 20026, "", "d_cmine_02", 1876.550049, 140.449188, -1519.922729, 0.0, "", "JOB_DIEVDIRBYS2_TRIGGER", "", -2, 40.0);
		AddNpc(540, 147469, "No Shadow Npc", "d_cmine_02", -1309.59314, 80.823402, -737.355164, 0.0, "MINE_2_CRYSTAL_2_PIPE", "", "", -2, 40.0);
		AddNpc(541, 151020, "No Shadow Npc", "d_cmine_02", -1814.552612, 140.955399, 939.608948, 0.0, "MINE_2_CRYSTAL_3_PIPE", "", "", -2, 40.0);
		AddNpc(542, 20026, "", "d_cmine_02", -1555.32666, 140.955399, 894.768677, 0.0, "", "MINE_2_CRYSTAL_3_TRIGGER", "", -2, 300.0);
		AddNpc(543, 147469, "No Shadow Npc", "d_cmine_02", -789.367859, -10.0, 1148.01001, 0.0, "MINE_2_CRYSTAL_7_ENERGY", "", "", -2, 40.0);
		AddNpc(544, 20026, "", "d_cmine_02", -87.921257, -28.304369, 942.115784, 3.0, "", "MINE_2_CRYSTAL_10_TRIGGER1", "", -2, 90.0);
		AddNpc(544, 20026, "", "d_cmine_02", -156.441193, -27.372044, 1019.160278, 0.0, "", "MINE_2_CRYSTAL_10_TRIGGER1", "", -2, 90.0);
		AddNpc(545, 20026, "", "d_cmine_02", 643.967346, -83.302155, 674.879333, 0.0, "", "MINE_2_CRYSTAL_10_TRIGGER2", "", -2, 100.0);
		AddNpc(546, 147469, "No Shadow Npc", "d_cmine_02", 338.032959, -98.276901, 1095.109619, 0.0, "MINE_2_CRYSTAL_10_OIL", "", "", -2, 40.0);
		AddNpc(547, 151017, "Purifier Parts 3", "d_cmine_02", 1208.371094, -36.468353, -1067.293213, 0.0, "MINE_2_CRYSTAL_16_PART", "", "", -2, 40.0);
		AddNpc(547, 151017, "Purifier Parts 3", "d_cmine_02", 1144.432617, 36.501945, -1485.566895, 90.0, "MINE_2_CRYSTAL_16_PART", "", "", -2, 40.0);
		AddNpc(547, 151017, "Purifier Parts 3", "d_cmine_02", 2012.120605, 139.497177, -1657.708862, 180.0, "MINE_2_CRYSTAL_16_PART", "", "", -2, 40.0);
		AddNpc(547, 151017, "Purifier Parts 3", "d_cmine_02", 2066.268799, 140.431198, -982.649292, 270.0, "MINE_2_CRYSTAL_16_PART", "", "", -2, 40.0);
		AddNpc(548, 151016, "Purifier Parts 2", "d_cmine_02", 1558.728638, -29.596901, -468.105682, 0.0, "MINE_2_CRYSTAL_20_PART", "", "", -2, 40.0);
		AddNpc(549, 20026, "", "d_cmine_02", 1654.140381, -28.958553, -802.793823, 0.0, "", "MINE_2_CRYSTAL_20_TRIGGER", "", -2, 450.0);
		AddNpc(550, 147392, "Treasure Box 1", "d_cmine_02", 1509.98999, 80.690002, 853.820007, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(551, 147392, "Treasure Box 1", "d_cmine_02", -349.390015, -27.200001, 1235.150024, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(553, 147392, "Treasure Box 1", "d_cmine_02", 142.580002, 8.91, 189.009995, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(554, 20042, "", "d_cmine_02", 754.15448, -104.196129, 1028.048462, 0.0, "", "MASTER_HIGHLANDER2_3_TRIGGER", "", -2, 50.0);
		AddNpc(555, 20026, "", "d_cmine_02", 1730.302612, 80.589798, 784.862915, 0.0, "", "MASTER_CRYOMANCER2_2_TRIGGER", "", -2, 150.0);
	}
}
