// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_d_firetower_44 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(7, 147500, "Warp Portal", "d_firetower_44", 584.492615, 280.771606, -1318.889526, 0.0, "", "FIRETOWER44_TO_FIRETOWER43", "", -2, 20.0);
		AddNpc(8, 147500, "Warp Portal", "d_firetower_44", -2718.142578, 576.247498, 62.12241, 0.0, "", "FIRETOWER44_TO_FIRETOWER45", "", -2, 20.0);
		AddNpc(100, 147449, "Grita", "d_firetower_44", 527.481689, 280.69162, -1362.511108, 0.0, "FTOWER44_GRITA_01", "", "", -2, 30.0);
		AddNpc(201, 20145, "Marga", "d_firetower_44", 1262.0, 328.0, -184.0, 0.0, "FTOWER44_SQ_01", "", "", -2, 30.0);
		AddNpc(202, 20145, "Marga", "d_firetower_44", 1896.0, 505.0, 253.0, 0.0, "FTOWER44_SQ_02", "", "", -2, 30.0);
		AddNpc(203, 20026, "", "d_firetower_44", 1780.0, 510.0, 507.0, 0.0, "", "FTOWER44_SQ_03", "", -2, 70.0);
		AddNpc(204, 151050, "Sealed Stone", "d_firetower_44", 32.0, 440.0, 310.0, 0.0, "FTOWER44_SQ_04", "", "", -2, 30.0);
		AddNpc(205, 151050, "Sealed Stone", "d_firetower_44", -453.084412, 364.375305, -1449.622925, 0.0, "FTOWER44_SQ_05", "", "", -2, 30.0);
		AddNpc(207, 147372, "Empty Npc", "d_firetower_44", 158.013718, 440.057861, 113.650909, 0.0, "FTOWER44_MQ_02", "", "", -2, 40.0);
		AddNpc(211, 20026, "", "d_firetower_44", -2194.910645, 525.407532, 62.185917, 0.0, "", "FTOWER44_MQ_05_TRIGGER", "", -2, 80.0);
		AddNpc(215, 151001, "Crystal With Magic", "d_firetower_44", -391.828796, 322.33429, -617.742859, 0.0, "FTOWER44_MQ_03", "", "", -2, 40.0);
		AddNpc(215, 151001, "Crystal With Magic", "d_firetower_44", -554.451782, 322.33429, -736.581848, 0.0, "FTOWER44_MQ_03", "", "", -2, 40.0);
		AddNpc(215, 151001, "Crystal With Magic", "d_firetower_44", -495.418091, 435.382385, -1278.578857, 0.0, "FTOWER44_MQ_03", "", "", -2, 40.0);
		AddNpc(215, 151001, "Crystal With Magic", "d_firetower_44", -418.773682, 372.05249, -1561.872559, 0.0, "FTOWER44_MQ_03", "", "", -2, 40.0);
		AddNpc(215, 151001, "Crystal With Magic", "d_firetower_44", -267.794952, 364.375397, -1334.424194, 0.0, "FTOWER44_MQ_03", "", "", -2, 40.0);
		AddNpc(218, 40070, "Bulletin Board", "d_firetower_44", -568.197083, 355.718811, -367.175781, 0.0, "FTOWER_44_WARING", "", "", -2, 40.0);
		AddNpc(223, 147469, "No Shadow Npc", "d_firetower_44", -1603.0, 536.0, 614.0, 0.0, "FTOWER44_MQ_04_NPC", "", "", -2, 40.0);
		AddNpc(227, 147449, "Grita", "d_firetower_44", -1596.219971, 536.960022, 587.599976, 90.0, "FTOWER44_GRITA_REMAIN", "", "", -2, 40.0);
		AddNpc(229, 147311, "Book", "d_firetower_44", 1411.337402, 432.741943, -656.379639, 0.0, "JOB_2_PSYCHOKINO_5_1_BOOK_4", "", "", -2, 40.0);
		AddNpc(230, 147392, "Treasure Box 1", "d_firetower_44", 744.700012, 451.299988, 554.75, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(232, 152057, "No Shadow Npc Tall", "d_firetower_44", 653.940002, 310.019989, -1663.73999, 0.0, "HT2_FTOWER_44_TSCOPE", "", "", -2, 5.0);
		AddNpc(232, 152057, "No Shadow Npc Tall", "d_firetower_44", 544.099976, 310.019989, -1687.829956, 0.0, "HT2_FTOWER_44_TSCOPE", "", "", -2, 5.0);
	}
}
