// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_d_firetower_41 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(20, 147500, "Warp Portal", "d_firetower_41", -2301.328369, 1552.728516, -1410.266602, 0.0, "", "FIRETOWER41_TO_REMAINS40", "", -2, 20.0);
		AddNpc(21, 147500, "Warp Portal", "d_firetower_41", 2956.426514, 1460.48645, -1409.30249, 0.0, "", "FIRETOWER41_TO_FIRETOWER42", "", -2, 20.0);
		AddNpc(100, 147449, "Grita", "d_firetower_41", -2600.0, 1552.0, -1571.0, 0.0, "FTOWER41_GRITA_01", "", "", -2, 250.0);
		AddNpc(104, 147500, "Warp Portal", "d_firetower_41", -582.0, 1410.0, -1856.0, 0.0, "FTOWER41_MQ_03", "", "", -2, 0.0);
		AddNpc(105, 151000, "Closing Device", "d_firetower_41", 2360.0, 1335.0, -2276.0, 45.0, "FTOWER41_MQ_05", "", "", -2, 0.0);
		AddNpc(107, 20117, "Armand", "d_firetower_41", -1664.0, 1489.0, -1786.0, 0.0, "FTOWER41_SQ_01", "", "", -2, 0.0);
		AddNpc(108, 20146, "Isolde", "d_firetower_41", 491.0, 1482.0, -1696.0, 0.0, "FTOWER41_SQ_03", "", "", -2, 0.0);
		AddNpc(109, 147372, "Empty Npc", "d_firetower_41", 1199.668457, 1602.249023, -891.269958, 0.0, "FTOWER41_SQ_05_NPC", "", "", -2, 40.0);
		AddNpc(110, 20026, "", "d_firetower_41", 1860.14502, 1334.282837, -2304.492188, 0.0, "", "JOB_THAUMATURGE4_1_TRIGGER", "", -2, 150.0);
		AddNpc(112, 147500, "Warp Portal", "d_firetower_41", -1609.0, 1552.0, -1402.0, 0.0, "FTOWER41_MQ_02_NPC", "", "", -2, 40.0);
		AddNpc(120, 40095, "", "d_firetower_41", -2176.398682, 1490.140991, -2123.404785, 0.0, "FTOWER41_MQ_01_NPC", "", "", -2, 40.0);
		AddNpc(125, 147311, "Book", "d_firetower_41", 1252.079468, 1334.282715, -2282.967529, 0.0, "JOB_2_PSYCHOKINO_5_1_BOOK_1", "", "", -2, 40.0);
		AddNpc(126, 147392, "Treasure Box 1", "d_firetower_41", -2714.800049, 1552.829956, -1436.660034, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
	}
}
