// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_d_firetower_43 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(9, 147500, "Warp Portal", "d_firetower_43", 1808.939941, 526.840027, 694.109985, 0.0, "", "FIRETOWER43_TO_FIRETOWER44", "", -2, 20.0);
		AddNpc(100, 147449, "Grita", "d_firetower_43", -2555.0, 525.0, -190.0, -60.0, "FTOWER43_GRITA_01", "", "", -2, 30.0);
		AddNpc(201, 151050, "Sealed Stone", "d_firetower_43", -460.0, 322.0, -831.0, 0.0, "FTOWER43_SQ_01", "", "", -2, 30.0);
		AddNpc(202, 151050, "Sealed Stone", "d_firetower_43", 1306.0, 432.0, -910.0, 0.0, "FTOWER43_SQ_03", "", "", -2, 30.0);
		AddNpc(203, 147469, "No Shadow Npc", "d_firetower_43", 1370.0, 340.0, -225.0, 0.0, "FTOWER43_SQ_05", "", "", -2, 30.0);
		AddNpc(206, 20026, "", "d_firetower_43", -609.710022, 361.589996, 48.130001, -98.0, "", "FTOWER43_MQ_04_TRIGGER", "", -2, 90.0);
		AddNpc(208, 20026, "", "d_firetower_43", 1274.030029, 432.73999, -793.380005, 0.0, "", "FTOWER43_MQ_06_TRIGGER", "", -2, 60.0);
		AddNpc(219, 147311, "Book", "d_firetower_43", -1668.0, 537.0, 866.0, 30.0, "FTOWER43_MQ_03_BOOK", "", "", -2, 40.0);
		AddNpc(219, 147311, "Book", "d_firetower_43", -1035.0, 359.0, -147.0, 40.0, "FTOWER43_MQ_03_BOOK", "", "", -2, 40.0);
		AddNpc(219, 147311, "Book", "d_firetower_43", -1762.0, 537.0, 696.0, 90.0, "FTOWER43_MQ_03_BOOK", "", "", -2, 40.0);
		AddNpc(219, 147311, "Book", "d_firetower_43", -1524.0, 537.0, 895.0, 120.0, "FTOWER43_MQ_03_BOOK", "", "", -2, 40.0);
		AddNpc(219, 147311, "Book", "d_firetower_43", -1166.430054, 358.899994, -73.989998, 150.0, "FTOWER43_MQ_03_BOOK", "", "", -2, 40.0);
		AddNpc(219, 147311, "Book", "d_firetower_43", -947.0, 359.0, 53.0, 180.0, "FTOWER43_MQ_03_BOOK", "", "", -2, 40.0);
		AddNpc(219, 147311, "Book", "d_firetower_43", -1079.01001, 450.690002, 449.850006, -15.0, "FTOWER43_MQ_03_BOOK", "", "", -2, 40.0);
		AddNpc(219, 147311, "Book", "d_firetower_43", -1178.219971, 393.899994, 176.630005, -35.0, "FTOWER43_MQ_03_BOOK", "", "", -2, 40.0);
		AddNpc(219, 147311, "Book", "d_firetower_43", -1526.0, 536.0, 398.0, -75.0, "FTOWER43_MQ_03_BOOK", "", "", -2, 40.0);
		AddNpc(219, 147311, "Book", "d_firetower_43", -1188.97998, 379.209991, -249.919998, -150.0, "FTOWER43_MQ_03_BOOK", "", "", -2, 40.0);
		AddNpc(233, 147504, "Magic Valve", "d_firetower_43", -1598.0, 554.0, 708.0, -45.0, "FTOWER43_MQ_02_VALVE", "", "", -2, 40.0);
		AddNpc(234, 147472, "Immobile Mineloader", "d_firetower_43", 669.0, 359.0, -730.0, 176.0, "FTOWER43_MQ_05_MINENPC", "", "", -2, 40.0);
		AddNpc(239, 147311, "Book", "d_firetower_43", 1420.747314, 323.607849, -75.517204, 0.0, "JOB_2_PSYCHOKINO_5_1_BOOK_3", "", "", -2, 40.0);
		AddNpc(241, 147392, "Treasure Box 1", "d_firetower_43", -149.720001, 364.480011, -1281.469971, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
	}
}
