// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_d_firetower_42 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(8, 147500, "Warp Portal", "d_firetower_42", 2547.029297, 71.556297, -125.385811, 0.0, "", "FIRETOWER42_TO_FIRETOWER41", "", -2, 20.0);
		AddNpc(100, 147449, "Grita", "d_firetower_42", 2458.0, 70.0, -53.0, -45.0, "FTOWER42_GRITA_01", "", "", -2, 30.0);
		AddNpc(101, 20026, "", "d_firetower_42", 1931.0, 25.0, -1195.0, 0.0, "", "FTOWER42_MQ_02", "", -2, 100.0);
		AddNpc(101, 20026, "", "d_firetower_42", 2018.0, 25.0, -1558.0, 0.0, "", "FTOWER42_MQ_02", "", -2, 100.0);
		AddNpc(101, 20026, "", "d_firetower_42", 1711.0, 25.0, -1458.0, 0.0, "", "FTOWER42_MQ_02", "", -2, 100.0);
		AddNpc(101, 20026, "", "d_firetower_42", 1733.0, 25.0, -1275.0, 0.0, "", "FTOWER42_MQ_02", "", -2, 100.0);
		AddNpc(101, 20026, "", "d_firetower_42", 1532.0, 22.0, -1376.0, 0.0, "", "FTOWER42_MQ_02", "", -2, 100.0);
		AddNpc(101, 20026, "", "d_firetower_42", 1224.349365, 75.0989, -1330.708374, 0.0, "", "FTOWER42_MQ_02", "", -2, 100.0);
		AddNpc(101, 20026, "", "d_firetower_42", 1156.604248, 75.0989, -1482.164673, 0.0, "", "FTOWER42_MQ_02", "", -2, 100.0);
		AddNpc(102, 147307, "Mage Tower Offense", "d_firetower_42", -1386.0, 8.0, -2368.0, -2.0, "FTOWER42_MQ_05", "", "", -2, 1.0);
		AddNpc(201, 20026, "", "d_firetower_42", 1928.0, 28.0, -1115.0, 0.0, "", "FTOWER42_SQ_SUB", "", -2, 30.0);
		AddNpc(202, 151050, "Sealed Stone", "d_firetower_42", 2024.0, 33.0, -1564.0, 0.0, "FTOWER42_SQ_01", "", "", -2, 30.0);
		AddNpc(203, 151050, "Sealed Stone", "d_firetower_42", 1190.0, 71.0, -20.0, 0.0, "FTOWER42_SQ_02", "", "", -2, 10.0);
		AddNpc(204, 151050, "Sealed Stone", "d_firetower_42", 482.0, 73.0, -569.0, 0.0, "FTOWER42_SQ_04", "", "", -2, 10.0);
		AddNpc(205, 151050, "Sealed Stone", "d_firetower_42", -1033.0, 2.0, -674.0, 0.0, "FTOWER42_SQ_05", "", "", -2, 30.0);
		AddNpc(222, 147311, "Book", "d_firetower_42", 951.625488, 71.250702, 330.933533, 0.0, "JOB_2_PSYCHOKINO_5_1_BOOK_2", "", "", -2, 40.0);
		AddNpc(223, 147392, "Treasure Box 1", "d_firetower_42", 2066.689941, 20.58, -593.809998, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(224, 20025, "", "d_firetower_42", 874.510986, 75.0989, -1280.474121, 0.0, "SAGE_JOBQ_IN_FTOWER1", "", "", -2, 40.0);
		AddNpc(225, 20025, "", "d_firetower_42", 1044.085693, 75.0989, -1419.790283, 0.0, "SAGE_JOBQ_IN_FTOWER2", "", "", -2, 40.0);
		AddNpc(226, 20025, "", "d_firetower_42", 1069.819214, 75.0989, -1143.149414, 0.0, "SAGE_JOBQ_IN_FTOWER4", "", "", -2, 40.0);
		AddNpc(227, 20025, "", "d_firetower_42", 850.27063, 75.0989, -1502.643433, 0.0, "SAGE_JOBQ_IN_FTOWER3", "", "", -2, 40.0);
	}
}
