// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_d_firetower_45 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(10, 147500, "Warp Portal", "d_firetower_45", -1215.600586, 185.035492, -2087.143555, 0.0, "", "FIRETOWER45_TO_FIRETOWER44", "", -2, 20.0);
		AddNpc(103, 151003, "Magic Suppressor", "d_firetower_45", -576.0, 282.0, -1092.0, -90.0, "FTOWER45_MQ_01_D", "FTOWER45_MQ_01_E", "", -2, 200.0);
		AddNpc(105, 151003, "Magic Suppressor", "d_firetower_45", -501.0, 467.0, -745.0, -45.0, "FTOWER45_MQ_02_D", "FTOWER45_MQ_02_E", "", -2, 200.0);
		AddNpc(107, 151003, "Magic Suppressor", "d_firetower_45", -12.0, 378.0, 26.0, 1.0, "FTOWER45_MQ_03_D", "FTOWER45_MQ_03_E", "", -2, 200.0);
		AddNpc(109, 151003, "Magic Suppressor", "d_firetower_45", -223.0, 246.0, 1036.0, -18.0, "FTOWER45_MQ_04_D", "FTOWER45_MQ_04_E", "", -2, 200.0);
		AddNpc(110, 20026, "", "d_firetower_45", 826.441284, 254.166565, 2333.979492, 0.0, "", "FTOWER45_MQ_05_E", "", -2, 300.0);
		AddNpc(112, 147452, "Goddess Gabija", "d_firetower_45", 837.070007, 254.169998, 2330.389893, -90.0, "FTOWER45_MQ_06_D", "", "", -2, 30.0);
		AddNpc(201, 20139, "Pablo", "d_firetower_45", -1361.0, 347.0, -1314.0, 0.0, "FTOWER45_SQ_01", "", "", -2, 30.0);
		AddNpc(202, 20139, "Pablo", "d_firetower_45", -1239.0, 610.0, 24.0, 0.0, "FTOWER45_SQ_03", "", "", -2, 30.0);
		AddNpc(203, 20026, "", "d_firetower_45", -1430.0, 595.0, -193.0, 0.0, "", "FTOWER45_SQ_T", "", -2, 30.0);
		AddNpc(204, 151050, "Sealed Stone", "d_firetower_45", 599.0, 245.0, 1146.0, 0.0, "FTOWER45_SQ_04", "", "", -2, 30.0);
		AddNpc(205, 20026, "", "d_firetower_45", 197.0, 145.0, 1441.0, 0.0, "", "FTOWER45_SQ_05", "", -2, 50.0);
		AddNpc(214, 151018, "No Shadow Npc", "d_firetower_45", 839.330017, 254.270004, 2290.110107, 0.0, "FTOWER45_MQ_05_D", "", "", -2, 40.0);
		AddNpc(215, 151053, "Grita Phoenix", "d_firetower_45", 860.454834, 254.16655, 2355.367676, -90.0, "", "FTOWER45_GRITA_PHOENIX", "", -2, 40.0);
		AddNpc(218, 147311, "Book", "d_firetower_45", -117.42086, 150.23848, 1675.798462, 0.0, "JOB_2_PSYCHOKINO_5_1_BOOK_5", "", "", -2, 40.0);
		AddNpc(219, 147392, "Treasure Box 1", "d_firetower_45", -1706.060059, 607.02002, -187.25, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
	}
}
