// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_d_thorn_21 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(112, 147389, "Saule God1", "d_thorn_21", 3652.088867, 400.751587, -233.229858, -96.0, "THORN21_BELIEVER", "", "", -2, 60.0);
		AddNpc(126, 147386, "Saule Goddess 2", "d_thorn_21", 692.344238, 222.557846, -944.925537, 0.0, "THORN21_BELIEVER02", "", "", -2, 40.0);
		AddNpc(127, 147398, "Saule God2", "d_thorn_21", 1497.871094, 331.971344, 151.350235, 0.0, "THORN21_BELIEVER03", "", "", -2, 40.0);
		AddNpc(128, 147397, "Saule Goddess2", "d_thorn_21", -110.960419, 221.225403, 116.212547, 0.0, "THORN21_BELIEVER04", "", "", -2, 40.0);
		AddNpc(129, 147397, "Saule Goddess2", "d_thorn_21", 4565.750977, 333.202301, -58.034164, 0.0, "THORN21_BELIEVER04_AFTER", "", "", -2, 40.0);
		AddNpc(130, 153011, "Bramble'S Root", "d_thorn_21", 2800.0, 122.0, -1325.0, -13.0, "THORN21_BRAMBLE01_ROOT", "", "", -2, 40.0);
		AddNpc(131, 153011, "Bramble'S Root", "d_thorn_21", 3305.0, 332.372101, 1084.0, -8.0, "THORN21_BRAMBLE02_ROOT", "", "", -2, 40.0);
		AddNpc(133, 46213, "Altar", "d_thorn_21", 1012.0, 208.0, -1241.0, -107.0, "THORN21_MQ02_TRACK", "", "", -2, 40.0);
		AddNpc(134, 46213, "Altar", "d_thorn_21", 2003.0, 331.0, -3.0, 0.0, "THORN21_MQ06_TRACK", "", "", -2, 40.0);
		AddNpc(137, 20026, "", "d_thorn_21", 5306.487793, 333.202301, -165.169388, 0.0, "", "THORN21_MQ07_TRACK", "", -2, 60.0);
		AddNpc(138, 40070, "Bulletin Board", "d_thorn_21", 1085.120605, 208.071304, -1445.902954, 90.0, "UPPER_WARNING_D_THORN_21", "", "", -2, 40.0);
		AddNpc(142, 147392, "Treasure Box 1", "d_thorn_21", -456.070007, 221.330002, -407.209991, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(143, 154066, "", "d_thorn_21", 3447.996826, 401.251556, -501.949829, 0.0, "THORN21_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(143, 154066, "", "d_thorn_21", 3359.342529, 401.251556, -328.06311, 0.0, "THORN21_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(143, 154066, "", "d_thorn_21", 3107.199463, 333.272125, -107.622002, 0.0, "THORN21_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(143, 154066, "", "d_thorn_21", 3108.550293, 332.471405, 217.514221, 0.0, "THORN21_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(143, 154066, "", "d_thorn_21", 2818.709473, 332.471405, 364.677185, 0.0, "THORN21_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(143, 154066, "", "d_thorn_21", 2666.677979, 332.471405, 387.964996, 0.0, "THORN21_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(143, 154066, "", "d_thorn_21", 3630.020996, 401.251556, -476.169525, 0.0, "THORN21_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(143, 154066, "", "d_thorn_21", 3580.989258, 401.251556, -290.952484, 0.0, "THORN21_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(143, 154066, "", "d_thorn_21", 3798.958008, 364.664551, -421.090027, 0.0, "THORN21_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(143, 154066, "", "d_thorn_21", 3914.951172, 333.702301, -374.258331, 0.0, "THORN21_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(143, 154066, "", "d_thorn_21", 4041.536377, 333.702301, -476.595154, 0.0, "THORN21_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(143, 154066, "", "d_thorn_21", 4305.864258, 333.702301, -314.085205, 0.0, "THORN21_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(143, 154066, "", "d_thorn_21", 4400.649902, 333.702301, -171.634766, 0.0, "THORN21_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(143, 154066, "", "d_thorn_21", 3209.100098, 364.132721, -222.78627, 0.0, "THORN21_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(143, 154066, "", "d_thorn_21", 3129.237793, 333.004578, 46.739655, 0.0, "THORN21_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(143, 154066, "", "d_thorn_21", 2976.935547, 332.737823, 290.432983, 0.0, "THORN21_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(143, 154066, "", "d_thorn_21", 4212.356934, 333.702301, -456.004028, 0.0, "THORN21_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(144, 40095, "", "d_thorn_21", -368.967194, 221.725433, -311.757874, 0.0, "", "EXPLORER_MISLE25", "", -2, 20.0);
	}
}
