// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_d_thorn_22 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(100, 20026, "", "d_thorn_22", -1250.0, 490.0, -1900.0, 0.0, "", "THORN22_ADD_SUB_01", "", -2, 100.0);
		AddNpc(102, 20026, "", "d_thorn_22", -170.0, 560.0, -1360.0, 0.0, "", "THORN22_ADD_SUB_03", "", -2, 100.0);
		AddNpc(103, 20026, "", "d_thorn_22", 530.0, 446.0, -1420.0, 0.0, "", "THORN22_ADD_SUB_04", "", -2, 100.0);
		AddNpc(501, 20011, "Supply Soldier", "d_thorn_22", -984.778564, 485.746216, -2094.785889, 0.0, "THORN22_DOMINIC", "", "", -2, 30.0);
		AddNpc(502, 20012, "Eastern Woods Scout", "d_thorn_22", -1145.517456, 554.74292, -1475.989502, 0.0, "THORN22_SAMSON", "", "", -2, 30.0);
		AddNpc(505, 20025, "", "d_thorn_22", -1591.0, 602.0, -1782.0, 0.0, "THORN22_Q_6_TRIGGER", "", "", -2, 30.0);
		AddNpc(507, 20125, "Mid Commander (Male 2)", "d_thorn_22", -996.506348, 554.73999, -1339.73645, 0.0, "THORN22_OROURKE", "", "", -2, 30.0);
		AddNpc(508, 20107, "Mid Commander (Female)", "d_thorn_22", 13.532867, 557.611816, -1289.192749, 0.0, "THORN22_JULIAN", "", "", -2, 30.0);
		AddNpc(509, 20013, "Supply Officer", "d_thorn_22", 762.0, 626.0, -721.0, 0.0, "THORN22_POULLTER", "", "", -2, 30.0);
		AddNpc(510, 20041, "", "d_thorn_22", 419.0, 446.0, -1509.0, 0.0, "", "THORN22_Q_14_TRIGGER", "", -2, 200.0);
		AddNpc(511, 20012, "Eastern Woods Scout", "d_thorn_22", 78.696251, 401.767639, 247.378754, 0.0, "THORN22_BOSSKILL_1_TRIGGER", "", "", -2, 40.0);
		AddNpc(512, 12081, "Owl Sculpture", "d_thorn_22", 218.15799, 557.611816, -1294.213501, -95.0, "THORN22_OWL1", "", "", -2, 30.0);
		AddNpc(513, 20041, "", "d_thorn_22", -1242.855347, 553.838684, -243.198288, 0.0, "", "THORN22_Q_16_TRIGGER", "", -2, 200.0);
		AddNpc(514, 48002, "Owl Sculpture", "d_thorn_22", -1425.8927, 553.838684, -155.030533, -68.0, "THORN22_OWL2", "", "", -2, 30.0);
		AddNpc(515, 20041, "", "d_thorn_22", -1236.0, 553.0, 371.0, 0.0, "", "THORN22_Q_18_TRIGGER", "", -2, 200.0);
		AddNpc(516, 20026, "", "d_thorn_22", -780.0, 554.0, -1520.0, 0.0, "", "THORN22_Q_1_TRIGGER", "", -2, 100.0);
		AddNpc(517, 46213, "Altar", "d_thorn_22", 76.0, 539.0, -606.0, -13.0, "THORN22_Q_9_TRIGGER", "", "", -2, 100.0);
		AddNpc(603, 20013, "Supply Officer", "d_thorn_22", -1301.0, 553.0, -354.0, 0.0, "THORN22_Q_18", "", "", -2, 40.0);
		AddNpc(826, 40070, "Bulletin Board", "d_thorn_22", -2102.793213, 440.816711, -1347.919189, -88.0, "THORN22_AREA_WARING01", "", "", -2, 40.0);
		AddNpc(829, 20026, "", "d_thorn_22", 467.889038, 289.774658, 499.986481, 0.0, "", "THORN22_Q_9_TRACK", "", -2, 200.0);
		AddNpc(832, 147392, "Treasure Box 1", "d_thorn_22", 1109.280029, 446.609985, -1282.300049, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(833, 156018, "Chaplain Master", "d_thorn_22", 119.016113, 568.909973, -1162.524414, -90.0, "CHAPLAIN_MASTER", "THORN22_HIDDEN_CHAPLAIN_IN", "", -2, 40.0);
	}
}
