// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_d_thorn_19 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(28, 47121, "Magic Square Of Thorn Forest", "d_thorn_19", 108.0, 674.0, 311.0, 0.0, "THORN19_HOLY01", "", "", -2, 30.0);
		AddNpc(30, 20041, "", "d_thorn_19", -1007.359924, 525.392944, -3248.976807, 0.0, "", "JOB_PSYCHOKINESIST3_1_TRIGGER", "", -2, 250.0);
		AddNpc(601, 20041, "", "d_thorn_19", -861.0, 765.0, -2339.0, 0.0, "", "THORN19_GATEWAY_2_TRIGGER", "", -2, 150.0);
		AddNpc(618, 147398, "Saule God2", "d_thorn_19", -174.669998, 642.570007, -2745.449951, -58.0, "THORN19_BELIEVER", "", "", -2, 40.0);
		AddNpc(619, 47160, "Lost Stuff Of Vendor 1", "d_thorn_19", -733.090027, 758.710022, 285.369995, -97.0, "THORN19_CHAFER_LURE", "", "", -2, 40.0);
		AddNpc(620, 20026, "", "d_thorn_19", 166.889999, 593.859985, 1603.780029, 0.0, "", "THORN19_THORNBUSH", "", -2, 80.0);
		AddNpc(625, 47088, "Thorn Forest Gate 2", "d_thorn_19", 102.900002, 669.580017, -1817.390015, -90.0, "", "THORN_GATEWAY_1", "", -2, 30.0);
		AddNpc(626, 47090, "Thorn Forest Gate 4", "d_thorn_19", 189.139999, 607.219971, 1387.800049, -69.0, "", "THORN_GATEWAY_2", "", -2, 30.0);
		AddNpc(627, 47087, "Thorn Forest Gate 1", "d_thorn_19", 2122.889893, 502.929993, 955.780029, -72.0, "", "THORN_GATEWAY_3", "", -2, 30.0);
		AddNpc(630, 46213, "Altar", "d_thorn_19", 2040.0, 461.0, 1670.0, -97.0, "THORN19_REFINE", "", "", -2, 40.0);
		AddNpc(632, 20025, "", "d_thorn_19", 464.790009, 602.409973, 2466.540039, 0.0, "THORN19_RECHARGE1", "", "", -2, 40.0);
		AddNpc(633, 20025, "", "d_thorn_19", 770.840027, 603.48999, 2572.050049, 0.0, "THORN19_RECHARGE2", "", "", -2, 40.0);
		AddNpc(634, 20025, "", "d_thorn_19", 359.200012, 602.409973, 2768.040039, 0.0, "THORN19_RECHARGE3", "", "", -2, 40.0);
		AddNpc(635, 20025, "", "d_thorn_19", 801.030029, 603.25, 2390.659912, 0.0, "THORN19_RECHARGE4", "", "", -2, 40.0);
		AddNpc(652, 20026, "", "d_thorn_19", 151.470001, 726.619995, -1553.160034, 0.0, "", "THORN19_BLACKMAN_TRACK", "", -2, 80.0);
		AddNpc(677, 147397, "Saule Goddess2", "d_thorn_19", 163.910004, 698.869995, -631.960022, 0.0, "THORN19_BELIEVER02", "", "", -2, 40.0);
		AddNpc(678, 147389, "Saule God1", "d_thorn_19", 637.369995, 597.080017, 1949.51001, 0.0, "THORN19_BELIEVER03", "", "", -2, 40.0);
		AddNpc(679, 20026, "", "d_thorn_19", 1339.910034, 523.679993, 2478.560059, -84.0, "", "THORN_BLACKMAN_TRIGGER1", "", -2, 40.0);
		AddNpc(680, 147389, "Saule God1", "d_thorn_19", 2311.370117, 502.899994, 535.669983, -82.0, "THORN_BLACKMAN_TRIGGER2", "", "", -2, 40.0);
		AddNpc(681, 20026, "", "d_thorn_19", 2089.0, 622.0, 83.0, 0.0, "", "THORN19_MQ14_2_TRACK", "", -2, 100.0);
		AddNpc(682, 147392, "Treasure Box 1", "d_thorn_19", 1761.780029, 458.619995, 1590.109985, 90.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(683, 40095, "", "d_thorn_19", 100.669998, 666.319458, -1852.805542, 0.0, "THORN19_GATE01_OPEN", "", "", -2, 40.0);
		AddNpc(687, 147392, "Treasure Box 1", "d_thorn_19", 627.0, 600.0, 1910.0, -90.0, "TREASUREBOX_LV", "", "", -2, 0.0);
	}
}
