// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_d_thorn_20 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(3, 20041, "", "d_thorn_20", 525.142517, 490.24881, -1965.910889, 0.0, "", "JOB_QUARREL3_2_TRIGGER", "", -2, 200.0);
		AddNpc(700, 147392, "Treasure Box 1", "d_thorn_20", 656.340027, 490.350006, -1853.619995, -135.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(839, 153019, "Corrupted Altar", "d_thorn_20", 2529.129883, 489.049988, -1249.790039, -14.0, "", "THORN_MQ06MAGIC_UNHIDE", "", -2, 40.0);
		AddNpc(840, 153019, "Corrupted Altar", "d_thorn_20", 2528.409912, 488.940002, 738.830017, -14.0, "", "THORN_MQ07MAGIC_UNHIDE", "", -2, 40.0);
		AddNpc(841, 153019, "Corrupted Altar", "d_thorn_20", -1078.920044, 583.26001, -383.519989, -14.0, "", "THORN_MQ04MAGIC_UNHIDE", "", -2, 40.0);
		AddNpc(851, 147389, "Saule God1", "d_thorn_20", -732.613831, 490.24881, -1851.018677, 0.0, "THORN20_MQ01", "", "", -2, 40.0);
		AddNpc(852, 147397, "Saule Goddess2", "d_thorn_20", -98.842911, 548.70813, -260.263794, 0.0, "THORN20_MQ02_BOSS", "", "", -2, 40.0);
		AddNpc(853, 147398, "Saule God2", "d_thorn_20", -428.986359, 542.501038, 647.136475, 0.0, "THORN20_MQ03_TRACK", "", "", -2, 40.0);
		AddNpc(854, 147386, "Saule Goddess 2", "d_thorn_20", -1223.182373, 557.60791, 602.532104, 0.0, "THORN20_MQ04_TRACK", "", "", -2, 40.0);
		AddNpc(855, 147389, "Saule God1", "d_thorn_20", 2163.388916, 449.998871, -1415.439819, 0.0, "THORN20_MAGIC3STAGE", "", "", -2, 40.0);
		AddNpc(856, 147397, "Saule Goddess2", "d_thorn_20", 2315.64209, 490.149261, 58.202301, 0.0, "THORN20_MQ07_TRACK", "", "", -2, 40.0);
		AddNpc(857, 20026, "", "d_thorn_20", 2526.682373, 488.938385, 734.735046, 0.0, "", "THORN20_MQ07_TRIGGER", "", -2, 300.0);
		AddNpc(858, 20026, "", "d_thorn_20", -59.48851, 558.973022, 351.329224, 0.0, "", "THORN20_MQ02_TRACK", "", -2, 200.0);
		AddNpc(859, 20026, "", "d_thorn_20", -813.339722, 517.926819, 960.975708, 0.0, "", "THORN20_MQ03_TRIGGER", "", -2, 240.0);
		AddNpc(860, 40070, "Bulletin Board", "d_thorn_20", 1334.502808, 438.515015, -1444.386475, 0.0, "UPPER_WARNING_D_THORN_20", "", "", -2, 40.0);
		AddNpc(862, 153019, "Corrupted Altar", "d_thorn_20", -1343.0, 583.26001, 232.0, -14.0, "", "THORN_MQ04MAGIC_UNHIDE2", "", -2, 40.0);
		AddNpc(863, 153019, "Corrupted Altar", "d_thorn_20", -16.84, 558.98999, 314.329987, -14.0, "", "THORN_MQ02MAGIC_UNHIDE2", "", -2, 40.0);
		AddNpc(864, 153019, "Corrupted Altar", "d_thorn_20", -812.919983, 517.960022, 966.119995, -14.0, "", "THORN_MQ03MAGIC_UNHIDE2", "", -2, 40.0);
		AddNpc(865, 147393, "Treasure Box 3", "d_thorn_20", 580.539978, 490.350006, -2066.050049, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(866, 20024, "", "d_thorn_20", 1751.203247, 433.425201, -1363.11438, 0.0, "SAULE_PURIFICATION", "", "", -2, 40.0);
		AddNpc(869, 40095, "", "d_thorn_20", -81.175415, 560.86853, 79.367371, 0.0, "", "EXPLORER_MISLE24", "", -2, 20.0);
	}
}
