// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_d_thorn_23 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(502, 20011, "Supply Soldier", "d_thorn_23", -1578.699951, 1137.75, -2850.120117, 0.0, "THORN23_ALAN", "", "", -2, 30.0);
		AddNpc(504, 20107, "Mid Commander (Female)", "d_thorn_23", -1494.0, 965.0, -1093.0, 0.0, "THORN23_WALLACE", "", "", -2, 30.0);
		AddNpc(505, 20013, "Supply Officer", "d_thorn_23", -1887.800049, 798.140015, 337.470001, 0.0, "THORN23_WISE", "", "", -2, 30.0);
		AddNpc(509, 47223, "Firewood", "d_thorn_23", -993.0, 600.0, 290.0, 0.0, "THORN23_FIRETRIGGER", "THORN23_BONFIRE", "", -2, 280.0);
		AddNpc(510, 48004, "Owl Sculpture", "d_thorn_23", 390.0, 459.0, 312.0, -95.779999, "THORN23_OWL2", "", "", -2, 30.0);
		AddNpc(514, 12081, "Owl Sculpture", "d_thorn_23", 734.0, 515.0, -252.0, -95.779999, "THORN23_OWL3", "", "", -2, 30.0);
		AddNpc(515, 153036, "Owl Sculpture", "d_thorn_23", 1345.72998, 514.5, 164.330002, -95.779999, "THORN23_OWL4", "", "", -2, 30.0);
		AddNpc(516, 153037, "Owl Sculpture", "d_thorn_23", 1428.570313, 515.671814, -118.94043, -95.779999, "THORN23_OWL5", "", "", -2, 30.0);
		AddNpc(517, 153038, "Owl Sculpture", "d_thorn_23", 1030.351563, 515.660461, 38.841076, -74.0, "THORN23_OWL6", "", "", -2, 30.0);
		AddNpc(518, 20026, "", "d_thorn_23", 2517.446777, 288.738373, 1577.390625, 0.0, "", "THORN23_BOSS_TRIGGER", "", -2, 100.0);
		AddNpc(601, 20041, "", "d_thorn_23", -1916.869995, 1137.75, -2346.679932, 0.0, "", "THORN23_Q_4_TRIGGER", "", -2, 300.0);
		AddNpc(602, 47170, "Soldier'S Relic", "d_thorn_23", -833.40802, 1070.325562, -1295.349121, -53.0, "THORN23_Q_7_TRIGGER", "", "", -2, 40.0);
		AddNpc(629, 151000, "Closing Device", "d_thorn_23", -551.922119, 575.937195, 307.609924, 64.0, "", "", "", -2, 200.0);
		AddNpc(631, 147392, "Treasure Box 1", "d_thorn_23", -1369.76001, 1041.880005, -1847.77002, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(632, 20026, "", "d_thorn_23", -1577.77002, 1137.75, -2852.409912, 0.0, "", "HT2_THORN23_ALAN_EFFECT", "", -2, 30.0);
		AddNpc(632, 20026, "", "d_thorn_23", -1461.790039, 1137.75, -2749.699951, 0.0, "", "HT2_THORN23_ALAN_EFFECT", "", -2, 30.0);
		AddNpc(633, 20026, "", "d_thorn_23", -1494.420044, 965.380005, -1091.030029, 0.0, "", "HT2_THORN23_WALLACE_EFFECT", "", -2, 30.0);
		AddNpc(634, 20026, "", "d_thorn_23", -1881.967041, 798.140015, 339.897034, 0.0, "", "HT2_THORN23_WISE_EFFECT", "", -2, 30.0);
	}
}
