// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_d_zachariel_34 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(18, 20041, "", "d_zachariel_34", 3551.0, 418.0, 119.0, -90.0, "", "ZACHA34_ENT", "", -2, 300.0);
		AddNpc(29, 47260, "Royal Mausoleum Guardian", "d_zachariel_34", 2163.0, 322.0, 89.0, -90.0, "ZACHA3F_MQ", "", "", -2, 0.0);
		AddNpc(30, 47257, "Jar", "d_zachariel_34", 829.0, 280.0, 354.0, 0.0, "ZACHA3F_POT", "", "", -2, 0.0);
		AddNpc(31, 20026, "", "d_zachariel_34", -2667.0, 296.0, 133.0, 0.0, "", "ZACHA3F_MQ_04", "", -2, 150.0);
		AddNpc(3000, 151022, "Shrine Offering Tools", "d_zachariel_34", 2507.0, 310.0, -47.0, 0.0, "ZACHA3F_SQ_01", "", "", -2, 0.0);
		AddNpc(3000, 151022, "Shrine Offering Tools", "d_zachariel_34", 2606.0, 319.0, 30.0, 0.0, "ZACHA3F_SQ_01", "", "", -2, 0.0);
		AddNpc(3000, 151022, "Shrine Offering Tools", "d_zachariel_34", 2445.0, 321.0, -144.0, 0.0, "ZACHA3F_SQ_01", "", "", -2, 0.0);
		AddNpc(3000, 151022, "Shrine Offering Tools", "d_zachariel_34", 2168.0, 321.0, -149.0, 0.0, "ZACHA3F_SQ_01", "", "", -2, 0.0);
		AddNpc(3000, 151022, "Shrine Offering Tools", "d_zachariel_34", 2289.0, 306.0, 37.0, 0.0, "ZACHA3F_SQ_01", "", "", -2, 0.0);
		AddNpc(3000, 151022, "Shrine Offering Tools", "d_zachariel_34", 2108.780518, 323.274597, 49.854786, 0.0, "ZACHA3F_SQ_01", "", "", -2, 0.0);
		AddNpc(3000, 151022, "Shrine Offering Tools", "d_zachariel_34", 1958.592529, 309.257111, -177.022141, 0.0, "ZACHA3F_SQ_01", "", "", -2, 0.0);
		AddNpc(3000, 151022, "Shrine Offering Tools", "d_zachariel_34", 1854.0, 308.0, 222.0, 0.0, "ZACHA3F_SQ_01", "", "", -2, 0.0);
		AddNpc(3001, 47253, "Royal Mausoleum Stone Lantern", "d_zachariel_34", -342.0, 247.0, 208.0, -90.0, "ZACHA3F_SQ_02", "", "", -2, 0.0);
		AddNpc(3002, 47253, "Royal Mausoleum Stone Lantern", "d_zachariel_34", -1214.0, 313.0, 1150.0, -90.0, "ZACHA3F_SQ_03", "", "", -2, 0.0);
		AddNpc(3003, 47106, "Canyon Area Device 5", "d_zachariel_34", -1504.260742, 288.28299, -1104.690308, -90.0, "ZACHA3F_SQ_04", "", "", -2, 0.0);
		AddNpc(3003, 47106, "Canyon Area Device 5", "d_zachariel_34", -1370.449951, 288.28299, -1102.105591, -90.0, "ZACHA3F_SQ_04", "", "", -2, 0.0);
		AddNpc(3004, 47260, "Royal Mausoleum Guardian", "d_zachariel_34", -389.200012, 289.130005, 974.01001, 0.0, "ZACHA3F_MQ03_MQ04", "", "", -2, 40.0);
		AddNpc(3005, 47260, "Royal Mausoleum Guardian", "d_zachariel_34", -382.10968, 289.561798, -292.108643, 0.0, "ZACHA3F_SQ02_GUARD", "", "", -2, 40.0);
		AddNpc(3006, 47260, "Royal Mausoleum Guardian", "d_zachariel_34", -1540.0, 298.0, -865.0, 0.0, "ZACHA3F_SQ04_GUARD", "", "", -2, 40.0);
		AddNpc(3007, 47260, "Royal Mausoleum Guardian", "d_zachariel_34", -2209.560059, 293.869995, 100.519997, 4.0, "ZACHA3F_MQ04_GUARD", "", "", -2, 40.0);
		AddNpc(3015, 47257, "Jar", "d_zachariel_34", 903.0, 280.0, 184.0, 0.0, "ZACHA3F_POT", "", "", -2, 0.0);
		AddNpc(3016, 47257, "Jar", "d_zachariel_34", 1048.0, 280.0, 351.0, 0.0, "ZACHA3F_POT", "", "", -2, 0.0);
		AddNpc(3017, 47257, "Jar", "d_zachariel_34", 1118.0, 280.0, 176.0, 0.0, "ZACHA3F_POT", "", "", -2, 0.0);
		AddNpc(3018, 47257, "Jar", "d_zachariel_34", 348.0, 286.0, 153.0, 0.0, "ZACHA3F_POT", "", "", -2, 0.0);
		AddNpc(3019, 47257, "Jar", "d_zachariel_34", 67.0, 286.0, 248.0, 0.0, "ZACHA3F_POT", "", "", -2, 0.0);
		AddNpc(3020, 47257, "Jar", "d_zachariel_34", -153.020004, 288.529999, 143.559998, 0.0, "ZACHA3F_POT", "", "", -2, 0.0);
		AddNpc(3021, 47257, "Jar", "d_zachariel_34", -634.0, 289.0, 264.0, 0.0, "ZACHA3F_POT", "", "", -2, 0.0);
		AddNpc(3022, 47257, "Jar", "d_zachariel_34", -1035.0, 286.0, 165.0, 0.0, "ZACHA3F_POT", "", "", -2, 0.0);
		AddNpc(3027, 147392, "Treasure Box 1", "d_zachariel_34", -3221.719971, 296.98999, -22.040001, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(3029, 40095, "", "d_zachariel_34", 789.876709, 273.453339, 386.479797, 0.0, "", "EXPLORER_MISLE45", "", -2, 20.0);
	}
}
