// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_d_zachariel_33 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(13, 47252, "Royal Mausoleum Tombstone02", "d_zachariel_33", 31.752308, 720.203979, 1219.775391, -90.0, "ZACHA2F_MQ_05", "", "", -2, 60.0);
		AddNpc(14, 20041, "", "d_zachariel_33", -92.0, 646.0, -2579.0, -90.0, "", "ZACHA33_ENT", "", -2, 300.0);
		AddNpc(26, 147469, "No Shadow Npc", "d_zachariel_33", -1671.0, 720.0, 173.0, -90.0, "ZACHA2F_SQ_01", "", "", -2, 30.0);
		AddNpc(26, 147469, "No Shadow Npc", "d_zachariel_33", -562.0, 716.0, 111.0, -90.0, "ZACHA2F_SQ_01", "", "", -2, 30.0);
		AddNpc(26, 147469, "No Shadow Npc", "d_zachariel_33", -858.0, 704.0, 296.0, -90.0, "ZACHA2F_SQ_01", "", "", -2, 30.0);
		AddNpc(26, 147469, "No Shadow Npc", "d_zachariel_33", -1546.0, 720.0, 370.0, -90.0, "ZACHA2F_SQ_01", "", "", -2, 30.0);
		AddNpc(26, 147469, "No Shadow Npc", "d_zachariel_33", -1321.0, 720.0, 318.0, -90.0, "ZACHA2F_SQ_01", "", "", -2, 30.0);
		AddNpc(26, 147469, "No Shadow Npc", "d_zachariel_33", -1528.0, 720.0, 157.0, -90.0, "ZACHA2F_SQ_01", "", "", -2, 30.0);
		AddNpc(26, 147469, "No Shadow Npc", "d_zachariel_33", -1103.0, 716.0, 206.0, -90.0, "ZACHA2F_SQ_01", "", "", -2, 30.0);
		AddNpc(26, 147469, "No Shadow Npc", "d_zachariel_33", -878.0, 715.0, 134.0, -90.0, "ZACHA2F_SQ_01", "", "", -2, 30.0);
		AddNpc(30, 47252, "Royal Mausoleum Tombstone02", "d_zachariel_33", -182.0, 711.0, -67.0, -79.0, "ZACHA2F_MQ_04", "", "", -2, 150.0);
		AddNpc(611, 47260, "Royal Mausoleum Guardian", "d_zachariel_33", -139.0, 648.0, -2186.0, 0.0, "ZACHARIEL33_GUARDIAN1", "", "", -2, 35.0);
		AddNpc(612, 47260, "Royal Mausoleum Guardian", "d_zachariel_33", -188.0, 645.0, -1420.0, 0.0, "ZACHARIEL33_GUARDIAN2", "", "", -2, 35.0);
		AddNpc(614, 47260, "Royal Mausoleum Guardian", "d_zachariel_33", 372.9133, 717.024292, 250.473709, -97.0, "ZACHA2F_SQ_03", "", "", -2, 35.0);
		AddNpc(3000, 47254, "Royal Mausoleum Desk", "d_zachariel_33", -1118.0, 716.0, 318.0, -90.0, "ZACHA2F_SQ", "", "", -2, 0.0);
		AddNpc(3001, 47253, "Royal Mausoleum Stone Lantern", "d_zachariel_33", 2108.0, 750.0, 470.0, -90.0, "ZACHA2F_SQ_04", "", "", -2, 0.0);
		AddNpc(3002, 147307, "Mage Tower Offense", "d_zachariel_33", 2098.0, 714.0, -244.0, 4.0, "", "", "", -2, 0.0);
		AddNpc(3002, 147307, "Mage Tower Offense", "d_zachariel_33", 2225.0, 714.0, -244.0, 4.0, "", "", "", -2, 0.0);
		AddNpc(3004, 20026, "", "d_zachariel_33", -1543.0, 650.0, -545.0, 0.0, "", "ZACHA2F_SQ_02", "", -2, 150.0);
		AddNpc(3006, 47253, "Royal Mausoleum Stone Lantern", "d_zachariel_33", -210.0, 649.0, -882.0, -90.0, "", "ZACHA2F_MQ02_HIDENPC", "", -2, 40.0);
		AddNpc(3006, 47253, "Royal Mausoleum Stone Lantern", "d_zachariel_33", -379.0, 649.0, -723.0, -90.0, "", "ZACHA2F_MQ02_HIDENPC", "", -2, 40.0);
		AddNpc(3006, 47253, "Royal Mausoleum Stone Lantern", "d_zachariel_33", -208.0, 649.0, -566.0, -90.0, "", "ZACHA2F_MQ02_HIDENPC", "", -2, 40.0);
		AddNpc(3006, 47253, "Royal Mausoleum Stone Lantern", "d_zachariel_33", 3.0, 649.0, -722.0, -90.0, "", "ZACHA2F_MQ02_HIDENPC", "", -2, 40.0);
		AddNpc(3008, 45320, "Holy Ark", "d_zachariel_33", -2087.159424, 640.275574, -823.125366, 1.0, "ZACHA2F_SQ02_TREASURE", "", "", -2, 40.0);
		AddNpc(3009, 47260, "Royal Mausoleum Guardian", "d_zachariel_33", 2284.15625, 714.302185, 111.48748, -71.0, "ZACHA2F_SQ_05", "", "", -2, 40.0);
		AddNpc(3010, 20026, "", "d_zachariel_33", 2291.610596, 714.302185, -68.005539, 0.0, "", "ZACHA2F_SQ_05_TRIGGER", "", -2, 80.0);
		AddNpc(3024, 147392, "Treasure Box 1", "d_zachariel_33", -1956.069946, 721.25, 242.440002, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(3026, 47260, "Royal Mausoleum Guardian", "d_zachariel_33", 932.228699, 671.4375, -637.05072, 0.0, "ZACHA33_RP_1_NPC", "", "", -2, 40.0);
	}
}
