// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_d_zachariel_36 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(9, 47261, "Royal Mausoleum Cube", "d_zachariel_36", -2495.0, 326.0, -3600.0, 0.0, "ZACHA5F_MQ_02", "", "", -2, 30.0);
		AddNpc(9, 47261, "Royal Mausoleum Cube", "d_zachariel_36", -2284.0, 327.0, -3354.0, 0.0, "ZACHA5F_MQ_02", "", "", -2, 30.0);
		AddNpc(9, 47261, "Royal Mausoleum Cube", "d_zachariel_36", -2310.0, 326.0, -3653.0, 0.0, "ZACHA5F_MQ_02", "", "", -2, 30.0);
		AddNpc(9, 47261, "Royal Mausoleum Cube", "d_zachariel_36", -2470.0, 326.0, -3975.0, 0.0, "ZACHA5F_MQ_02", "", "", -2, 30.0);
		AddNpc(9, 47261, "Royal Mausoleum Cube", "d_zachariel_36", -2611.0, 326.0, -3854.0, 0.0, "ZACHA5F_MQ_02", "", "", -2, 30.0);
		AddNpc(9, 47261, "Royal Mausoleum Cube", "d_zachariel_36", -2694.0, 326.0, -3530.0, 0.0, "ZACHA5F_MQ_02", "", "", -2, 30.0);
		AddNpc(9, 47261, "Royal Mausoleum Cube", "d_zachariel_36", -2620.0, 326.0, -3374.0, 0.0, "ZACHA5F_MQ_02", "", "", -2, 30.0);
		AddNpc(9, 47261, "Royal Mausoleum Cube", "d_zachariel_36", -2653.0, 326.0, -3745.0, 0.0, "ZACHA5F_MQ_02", "", "", -2, 30.0);
		AddNpc(10, 20025, "", "d_zachariel_36", -2503.0, 334.0, -2600.0, 0.0, "ZACHA5F_MQ_03", "", "", -2, 30.0);
		AddNpc(11, 147467, "Royal Mausoleum Guardian", "d_zachariel_36", -2491.0, 363.0, -1092.0, -86.0, "ZACHA5F_MQ_04", "", "", -2, 30.0);
		AddNpc(12, 147467, "Royal Mausoleum Guardian", "d_zachariel_36", -2600.238037, 329.475311, -5617.058105, -34.0, "ZACHARIEL_GUARDIAN", "", "", -2, 30.0);
		AddNpc(706, 47256, "Jar", "d_zachariel_36", -2767.376953, 323.957886, -4617.751465, 0.0, "ZACHA36_POT1_NPC", "", "", -2, 50.0);
		AddNpc(707, 47257, "Jar", "d_zachariel_36", -2646.041748, 323.957886, -4287.453125, 0.0, "ZACHA36_POT1_NPC", "", "", -2, 50.0);
		AddNpc(708, 47258, "Jar", "d_zachariel_36", -2319.45752, 323.957886, -4666.115234, 0.0, "ZACHA36_POT1_NPC", "", "", -2, 50.0);
		AddNpc(3003, 47257, "Jar", "d_zachariel_36", -2290.02417, 323.957886, -4325.253418, 0.0, "ZACHA36_POT1_NPC", "", "", -2, 40.0);
		AddNpc(3004, 47256, "Jar", "d_zachariel_36", -2627.564697, 323.957886, -4842.287598, 0.0, "ZACHA36_POT1_NPC", "", "", -2, 40.0);
		AddNpc(3005, 47257, "Jar", "d_zachariel_36", -2446.748047, 323.957886, -4408.289551, 0.0, "ZACHA36_POT1_NPC", "", "", -2, 40.0);
		AddNpc(3012, 47254, "Royal Mausoleum Desk", "d_zachariel_36", -3440.148926, 296.004791, -2584.216064, -2.0, "ZACHA5F_EQ_04", "", "", -2, 40.0);
		AddNpc(3014, 40035, "Treasure Chest", "d_zachariel_36", -1517.0, 334.0, -2627.0, 178.0, "ZACHA5F_EQ_03", "", "", -2, 40.0);
		AddNpc(3015, 47260, "Royal Mausoleum Guardian", "d_zachariel_36", -2509.0, 326.0, -4762.0, -89.0, "ZACHA5F_EQ_01", "", "", -2, 40.0);
		AddNpc(3016, 47260, "Royal Mausoleum Guardian", "d_zachariel_36", -2509.0, 326.0, -3858.0, -87.0, "ZACHA5F_EQ_02", "", "", -2, 40.0);
		AddNpc(3017, 47260, "Royal Mausoleum Guardian", "d_zachariel_36", -2511.0, 334.0, -2872.0, -91.0, "ZACHA5F_EQ_05", "", "", -2, 40.0);
		AddNpc(3019, 147469, "No Shadow Npc", "d_zachariel_36", -2656.428711, 453.203094, 490.975769, 0.0, "ZACHARIEL36_ROKAS31", "", "", -2, 30.0);
		AddNpc(3024, 153024, "Great King Zachariel'S Coffin", "d_zachariel_36", -3018.780029, 448.929993, 493.320007, -90.0, "ZACHA5F_MQ_05", "", "", -2, 40.0);
		AddNpc(3025, 147392, "Treasure Box 1", "d_zachariel_36", -2772.169922, 324.059998, -4747.02002, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(3027, 40095, "", "d_zachariel_36", -2891.703369, 458.279602, 181.375107, 0.0, "", "EXPLORER_MISLE47", "", -2, 20.0);
	}
}
