// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_d_zachariel_32 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(17, 47262, "Royal Mausoleum Cube", "d_zachariel_32", -871.803711, 252.763794, -844.14917, 0.0, "ZACHA1F_MQ_01_MON", "", "", -2, 80.0);
		AddNpc(17, 47262, "Royal Mausoleum Cube", "d_zachariel_32", -1145.665161, 252.763794, -840.389282, 88.0, "ZACHA1F_MQ_01_MON", "", "", -2, 80.0);
		AddNpc(17, 47262, "Royal Mausoleum Cube", "d_zachariel_32", -1154.030273, 252.763794, -1105.388184, 88.0, "ZACHA1F_MQ_01_MON", "", "", -2, 80.0);
		AddNpc(17, 47262, "Royal Mausoleum Cube", "d_zachariel_32", -869.809937, 252.763794, -1113.927979, 87.0, "ZACHA1F_MQ_01_MON", "", "", -2, 80.0);
		AddNpc(504, 147467, "Royal Mausoleum Guardian", "d_zachariel_32", 37.35041, 261.640594, -2046.594727, -90.0, "ZACHA1F_MQ_01", "", "", -2, 50.0);
		AddNpc(505, 47252, "Royal Mausoleum Tombstone02", "d_zachariel_32", -567.0, 252.0, -929.0, -90.0, "ZACHA1F_MQ_02", "", "", -2, 50.0);
		AddNpc(506, 47252, "Royal Mausoleum Tombstone02", "d_zachariel_32", -1020.0, 252.0, -477.0, -90.0, "ZACHA1F_MQ_03", "", "", -2, 50.0);
		AddNpc(507, 47252, "Royal Mausoleum Tombstone02", "d_zachariel_32", -530.0, 341.0, 176.0, -80.0, "ZACHA1F_MQ_04", "", "", -2, 50.0);
		AddNpc(508, 20026, "", "d_zachariel_32", 50.0, 330.0, 1191.0, 0.0, "", "ZACHA1F_MQ_05", "", -2, 150.0);
		AddNpc(1006, 40064, "Grill", "d_zachariel_32", 57.0, 336.0, 332.0, 0.0, "ZACHA32_MQ_04_D", "", "", -2, 50.0);
		AddNpc(1006, 40064, "Grill", "d_zachariel_32", 43.0, 336.0, -70.0, 0.0, "ZACHA32_MQ_04_D", "", "", -2, 50.0);
		AddNpc(1018, 45324, "Holy Ark", "d_zachariel_32", 1474.380005, 267.329987, -2200.649902, 178.0, "ZACHA32_DEVICE_1_2", "", "", -2, 20.0);
		AddNpc(1019, 47102, "Canyon Area Device 1", "d_zachariel_32", -1031.0, 267.0, -2204.0, 0.0, "ZACHA32_DEVICE02", "", "", -2, 30.0);
		AddNpc(3000, 47254, "Royal Mausoleum Desk", "d_zachariel_32", 856.0, 335.0, 222.0, -50.0, "ZACHA1F_SQ_01", "", "", -2, 0.0);
		AddNpc(3001, 47253, "Royal Mausoleum Stone Lantern", "d_zachariel_32", 1111.0, 253.0, -757.0, -90.0, "ZACHA1F_SQ_02", "", "", -2, 0.0);
		AddNpc(3002, 47254, "Royal Mausoleum Desk", "d_zachariel_32", -95.0, 335.0, 280.0, -90.0, "ZACHA1F_SQ_03", "", "", -2, 0.0);
		AddNpc(3003, 47261, "Royal Mausoleum Cube", "d_zachariel_32", -1006.0, 332.0, 1408.0, 0.0, "ZACHA1F_SQ_04", "", "", -2, 0.0);
		AddNpc(3004, 47261, "Royal Mausoleum Cube", "d_zachariel_32", 1112.0, 331.0, 1408.0, 0.0, "ZACHA1F_SQ_05", "", "", -2, 0.0);
		AddNpc(3016, 47251, "Royal Mausoleum Tombstone01", "d_zachariel_32", 159.718048, 326.631989, 762.732117, -84.0, "ZACHA1F_MQ_05_NPC", "", "", -2, 40.0);
		AddNpc(3017, 47253, "Royal Mausoleum Stone Lantern", "d_zachariel_32", -1054.0, 334.0, 383.0, -90.0, "", "ZACHA1F_MQ_03_LANTERN", "", -2, 40.0);
		AddNpc(3017, 47253, "Royal Mausoleum Stone Lantern", "d_zachariel_32", -943.0, 334.0, 383.0, -90.0, "", "ZACHA1F_MQ_03_LANTERN", "", -2, 40.0);
		AddNpc(3023, 147392, "Treasure Box 1", "d_zachariel_32", 862.070007, 335.549988, 414.350006, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(3025, 47260, "Royal Mausoleum Guardian", "d_zachariel_32", 50.283882, 371.338501, 1806.078125, -91.0, "ZACHA32_RP_1_NPC", "", "", -2, 40.0);
		AddNpc(3026, 40095, "", "d_zachariel_32", -1271.534424, 343.115143, 1422.721436, 0.0, "", "EXPLORER_MISLE44", "", -2, 20.0);
	}
}
