// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_d_zachariel_35 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(9, 47254, "Royal Mausoleum Desk", "d_zachariel_35", 1154.0, -52.0, -1341.0, -80.0, "ZACHA4F_MQ", "", "", -2, 0.0);
		AddNpc(10, 20026, "", "d_zachariel_35", 927.0, -53.0, -1257.0, 0.0, "", "ZACHA4F_MQ_01", "", -2, 150.0);
		AddNpc(11, 47252, "Royal Mausoleum Tombstone02", "d_zachariel_35", 1161.140015, -52.880001, -292.089996, -74.0, "ZACHA4F_MQ_02", "", "", -2, 150.0);
		AddNpc(12, 20026, "", "d_zachariel_35", 436.420013, -51.139999, 1268.349976, 0.0, "", "ZACHA4F_MQ_03_TRACK", "", -2, 150.0);
		AddNpc(13, 47252, "Royal Mausoleum Tombstone02", "d_zachariel_35", 109.809998, -27.09, -30.09, -45.0, "ZACHA4F_MQ_04", "", "", -2, 150.0);
		AddNpc(14, 20026, "", "d_zachariel_35", -305.0, -24.0, 1276.0, 0.0, "", "ZACHA4F_MQ_05_TRACK", "", -2, 150.0);
		AddNpc(101, 20026, "", "d_zachariel_35", 732.0, -51.0, 850.0, 0.0, "", "ZACHA4F_MQ_01", "", -2, 150.0);
		AddNpc(601, 20026, "", "d_zachariel_35", 1152.0, -22.0, -46.0, 0.0, "", "ZACHA35_SACRIFICE", "", -2, 50.0);
		AddNpc(602, 20026, "", "d_zachariel_35", 425.0, -46.0, 1338.0, 0.0, "", "ZACHA35_TRICK", "", -2, 50.0);
		AddNpc(603, 20026, "", "d_zachariel_35", 349.0, -26.0, -28.0, 0.0, "", "ZACHA35_LETHALBLOW", "", -2, 25.0);
		AddNpc(604, 20026, "", "d_zachariel_35", -842.0, -52.0, -10.0, 0.0, "", "ZACHA35_TRAP", "", -2, 40.0);
		AddNpc(605, 20026, "", "d_zachariel_35", 150.0, -26.0, -1517.0, 0.0, "", "ZACHA35_IDENTIFY", "", -2, 40.0);
		AddNpc(606, 20026, "", "d_zachariel_35", 18.0, -26.0, -1402.0, 0.0, "", "ZACHA35_DESTINY", "", -2, 30.0);
		AddNpc(3000, 47254, "Royal Mausoleum Desk", "d_zachariel_35", 739.0, -54.0, -1529.0, -90.0, "ZACHA4F_SQ_01", "", "", -2, 0.0);
		AddNpc(3002, 47254, "Royal Mausoleum Desk", "d_zachariel_35", -1288.459961, -22.48, -15.26, -6.0, "ZACHA4F_SQ_03", "", "", -2, 0.0);
		AddNpc(3004, 47254, "Royal Mausoleum Desk", "d_zachariel_35", -859.0, -52.0, -1088.0, 0.0, "ZACHA4F_SQ_05", "", "", -2, 0.0);
		AddNpc(3007, 47260, "Royal Mausoleum Guardian", "d_zachariel_35", -26.0, -27.0, -33.0, -1.0, "ZACHA4F_GUARDIAN01", "", "", -2, 40.0);
		AddNpc(3008, 47260, "Royal Mausoleum Guardian", "d_zachariel_35", 241.460007, -27.09, -31.610001, 3.0, "ZACHA4F_GUARDIAN02", "", "", -2, 40.0);
		AddNpc(3014, 47260, "Royal Mausoleum Guardian", "d_zachariel_35", -364.399994, -53.869999, 1599.689941, -90.0, "ZACHA4F_MQ05", "", "", -2, 40.0);
		AddNpc(3015, 47254, "Royal Mausoleum Desk", "d_zachariel_35", 792.849976, -51.139999, 1545.109985, 0.0, "ZACHA4F_MQ_03", "", "", -2, 40.0);
		AddNpc(3018, 47260, "Royal Mausoleum Guardian", "d_zachariel_35", 1142.709961, -22.780001, -39.5, -4.4, "ZACHA4F_MQ_02_HIDE", "", "", -2, 40.0);
		AddNpc(3019, 47261, "Royal Mausoleum Cube", "d_zachariel_35", 530.76001, -83.110001, 1085.030029, 0.0, "", "ZACHA4F_MQ_03_HIDE01", "", -2, 40.0);
		AddNpc(3020, 47254, "Royal Mausoleum Desk", "d_zachariel_35", 361.029999, -51.130001, 1086.030029, 0.0, "", "ZACHA4F_MQ_03_HIDE02", "", -2, 40.0);
		AddNpc(3020, 47254, "Royal Mausoleum Desk", "d_zachariel_35", 529.820007, -51.549999, 927.599976, 89.0, "", "ZACHA4F_MQ_03_HIDE02", "", -2, 40.0);
		AddNpc(3020, 47254, "Royal Mausoleum Desk", "d_zachariel_35", 530.440002, -51.139999, 1241.869995, -95.0, "", "ZACHA4F_MQ_03_HIDE02", "", -2, 40.0);
		AddNpc(3020, 47254, "Royal Mausoleum Desk", "d_zachariel_35", 742.169983, -51.130001, 1087.5, 172.0, "", "ZACHA4F_MQ_03_HIDE02", "", -2, 40.0);
		AddNpc(3023, 20170, "Search Trigger", "d_zachariel_35", -1094.209961, -52.080002, -1382.680054, 0.0, "", "", "", -2, 15.0);
		AddNpc(3026, 147392, "Treasure Box 1", "d_zachariel_35", -110.82, -53.77, 1350.0, 180.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(3032, 152077, "Mausoleum Cube 0", "d_zachariel_35", -17.139999, -26.83, -1556.439941, 0.0, "HT_ZACHA_CUBE01", "", "", -2, 40.0);
		AddNpc(3033, 47254, "Royal Mausoleum Desk", "d_zachariel_35", -190.070007, -26.83, -1669.560059, 0.0, "HT_ZACHA_DESK01", "", "", -2, 40.0);
		AddNpc(3034, 40095, "", "d_zachariel_35", 701.484009, -52.878616, 1279.807495, 0.0, "", "EXPLORER_MISLE46", "", -2, 20.0);
	}
}
