// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_flash_59 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(10, 147416, "Sentinel Woman 3", "f_flash_59", -200.826614, 109.316902, 726.734436, 170.0, "FLASH59_RETIA", "", "", -2, 40.0);
		AddNpc(14, 20117, "Armand", "f_flash_59", -843.279602, 188.837006, -382.094025, 0.0, "FLASH59_HUBERTAS", "", "", -2, 40.0);
		AddNpc(16, 20026, "", "f_flash_59", -307.542328, 109.416901, 738.258667, 0.0, "", "FLASH59_SQ_01", "", -2, 180.0);
		AddNpc(19, 154025, "Petrification Detector", "f_flash_59", -112.086403, 134.875702, 494.363739, 0.0, "FLASH59_SQ_03_1", "", "", -2, 1.0);
		AddNpc(20, 154025, "Petrification Detector", "f_flash_59", -915.52948, 109.3918, 443.894287, 0.0, "FLASH59_SQ_03_2", "", "", -2, 40.0);
		AddNpc(21, 154025, "Petrification Detector", "f_flash_59", -1648.630249, 109.337402, -265.154968, 0.0, "FLASH59_SQ_03_3", "", "", -2, 40.0);
		AddNpc(22, 154025, "Petrification Detector", "f_flash_59", -712.094299, 109.222, -257.116852, 0.0, "FLASH59_SQ_03_4", "", "", -2, 40.0);
		AddNpc(23, 154025, "Petrification Detector", "f_flash_59", -39.386581, 109.222, -220.869629, 0.0, "FLASH59_SQ_03_5", "", "", -2, 40.0);
		AddNpc(24, 154035, "Petrified Box", "f_flash_59", -1627.440186, 109.337402, -351.646515, 90.0, "FLASH59_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(24, 154035, "Petrified Box", "f_flash_59", -1564.032837, 109.337402, -307.169067, 90.0, "FLASH59_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(24, 154035, "Petrified Box", "f_flash_59", -1435.138794, 109.337402, -271.560364, 90.0, "FLASH59_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(24, 154035, "Petrified Box", "f_flash_59", -1415.386475, 109.337402, -407.035645, 90.0, "FLASH59_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(24, 154035, "Petrified Box", "f_flash_59", -1236.095581, 109.337402, -423.914856, 90.0, "FLASH59_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(24, 154035, "Petrified Box", "f_flash_59", -1118.078247, 109.337402, -475.283112, 90.0, "FLASH59_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(24, 154035, "Petrified Box", "f_flash_59", -1216.74353, 109.337402, -262.52475, 90.0, "FLASH59_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(24, 154035, "Petrified Box", "f_flash_59", -1073.998535, 109.337402, -237.741425, 90.0, "FLASH59_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(24, 154035, "Petrified Box", "f_flash_59", -948.072144, 109.337402, -272.24295, 90.0, "FLASH59_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(29, 147372, "Empty Npc", "f_flash_59", 30.262199, 134.875702, 99.932106, 0.0, "", "", "", -2, 40.0);
		AddNpc(29, 147372, "Empty Npc", "f_flash_59", -96.155045, 134.875702, 299.522522, 0.0, "", "", "", -2, 40.0);
		AddNpc(29, 147372, "Empty Npc", "f_flash_59", 120.643646, 134.875702, 309.377472, 0.0, "", "", "", -2, 40.0);
		AddNpc(29, 147372, "Empty Npc", "f_flash_59", 330.097809, 134.875702, 259.005188, 0.0, "", "", "", -2, 40.0);
		AddNpc(29, 147372, "Empty Npc", "f_flash_59", 305.517731, 134.875702, 156.372101, 0.0, "", "", "", -2, 40.0);
		AddNpc(29, 147372, "Empty Npc", "f_flash_59", 202.284714, 134.875702, 99.999481, 0.0, "", "", "", -2, 40.0);
		AddNpc(29, 147372, "Empty Npc", "f_flash_59", 318.783569, 134.875702, 457.68927, 0.0, "", "", "", -2, 40.0);
		AddNpc(29, 147372, "Empty Npc", "f_flash_59", 161.055588, 134.875702, 550.069641, 0.0, "", "", "", -2, 40.0);
		AddNpc(29, 147372, "Empty Npc", "f_flash_59", 6.102762, 134.875702, 493.781616, 0.0, "", "", "", -2, 40.0);
		AddNpc(1000, 147392, "Treasure Box 1", "f_flash_59", 818.070007, 61.830002, 798.190002, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
	}
}
