// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_gele_57_1 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(104, 147406, "Paladin Follower B4", "f_gele_57_1", -352.0, 168.0, -564.0, 0.0, "GELE571_NPC_GILBERT", "", "", -2, 40.0);
		AddNpc(117, 47204, "Siauliai Discolored Grass4", "f_gele_57_1", -1385.329956, 276.339996, 683.5, 0.0, "GELE571_MQ_03", "", "", -2, 40.0);
		AddNpc(117, 47204, "Siauliai Discolored Grass4", "f_gele_57_1", -1227.540039, 276.339996, 118.290001, 0.0, "GELE571_MQ_03", "", "", -2, 40.0);
		AddNpc(117, 47204, "Siauliai Discolored Grass4", "f_gele_57_1", -1200.75, 276.339996, 512.950012, 0.0, "GELE571_MQ_03", "", "", -2, 40.0);
		AddNpc(117, 47204, "Siauliai Discolored Grass4", "f_gele_57_1", -1501.949951, 276.339996, 399.630005, 0.0, "GELE571_MQ_03", "", "", -2, 40.0);
		AddNpc(117, 47204, "Siauliai Discolored Grass4", "f_gele_57_1", -1506.592041, 276.342499, 76.214905, 0.0, "GELE571_MQ_03", "", "", -2, 40.0);
		AddNpc(117, 47204, "Siauliai Discolored Grass4", "f_gele_57_1", -1192.193848, 276.342499, -129.76683, 0.0, "GELE571_MQ_03", "", "", -2, 40.0);
		AddNpc(117, 47204, "Siauliai Discolored Grass4", "f_gele_57_1", -1480.809814, 276.342499, -180.435333, 0.0, "GELE571_MQ_03", "", "", -2, 40.0);
		AddNpc(117, 47204, "Siauliai Discolored Grass4", "f_gele_57_1", -1392.776367, 276.342499, 130.346741, 0.0, "GELE571_MQ_03", "", "", -2, 40.0);
		AddNpc(117, 47204, "Siauliai Discolored Grass4", "f_gele_57_1", -1538.045166, 276.342499, -71.390366, 0.0, "GELE571_MQ_03", "", "", -2, 40.0);
		AddNpc(136, 147451, "Baby Panto", "f_gele_57_1", 607.159973, 95.989998, 528.5, 0.0, "GELE571_NPC_PANTO", "", "", -2, 1.0);
		AddNpc(136, 147451, "Baby Panto", "f_gele_57_1", 757.719971, 95.989998, 568.460022, 0.0, "GELE571_NPC_PANTO", "", "", -2, 1.0);
		AddNpc(136, 147451, "Baby Panto", "f_gele_57_1", 832.190002, 95.989998, 389.369995, 0.0, "GELE571_NPC_PANTO", "", "", -2, 1.0);
		AddNpc(136, 147451, "Baby Panto", "f_gele_57_1", 779.140015, 95.989998, 312.720001, 0.0, "GELE571_NPC_PANTO", "", "", -2, 1.0);
		AddNpc(136, 147451, "Baby Panto", "f_gele_57_1", 681.049988, 95.989998, 297.299988, 0.0, "GELE571_NPC_PANTO", "", "", -2, 1.0);
		AddNpc(136, 147451, "Baby Panto", "f_gele_57_1", 565.130005, 95.989998, 280.519989, 0.0, "GELE571_NPC_PANTO", "", "", -2, 1.0);
		AddNpc(136, 147451, "Baby Panto", "f_gele_57_1", 411.600006, 95.989998, 323.869995, 0.0, "GELE571_NPC_PANTO", "", "", -2, 1.0);
		AddNpc(136, 147451, "Baby Panto", "f_gele_57_1", 376.720001, 95.989998, 559.830017, 0.0, "GELE571_NPC_PANTO", "", "", -2, 1.0);
		AddNpc(137, 147421, "Paladin Follower No Instrument C1", "f_gele_57_1", -401.0, 168.0, -642.0, -16.0, "GELE571_NPC_MATTHEW", "", "", -2, 40.0);
		AddNpc(138, 147423, "Paladin Follower No Instrument C3", "f_gele_57_1", -257.98999, 95.989998, 283.709991, 33.0, "GELE571_NPC_MARLEY", "", "", -2, 40.0);
		AddNpc(145, 40070, "Bulletin Board", "f_gele_57_1", -1496.0, 168.0, -968.0, 0.0, "GELE1_BOARD01", "", "", -2, 10.0);
		AddNpc(146, 47203, "Large Discolored Grass Of Siauliai", "f_gele_57_1", 793.0, 368.0, -1362.0, 36.0, "GELE571_MQ_05", "", "", -2, 1.0);
		AddNpc(147, 147451, "Baby Panto", "f_gele_57_1", 980.0, 253.0, 961.0, 0.0, "GELE571_MQ_07", "", "", -2, 1.0);
		AddNpc(148, 147451, "Baby Panto", "f_gele_57_1", 950.0, 266.0, 963.0, 180.0, "", "GELE571_MQ_07_1", "", -2, 1.0);
		AddNpc(148, 147451, "Baby Panto", "f_gele_57_1", 999.0, 251.0, 995.0, 45.0, "", "GELE571_MQ_07_1", "", -2, 1.0);
		AddNpc(148, 147451, "Baby Panto", "f_gele_57_1", 980.0, 264.0, 1025.0, 135.0, "", "GELE571_MQ_07_1", "", -2, 1.0);
		AddNpc(154, 20170, "Search Trigger", "f_gele_57_1", 1482.459961, 224.830002, -752.669983, 0.0, "", "", "", -2, 15.0);
		AddNpc(155, 20024, "", "f_gele_57_1", -1542.497925, 168.823334, -1083.210327, 0.0, "PARTY_Q3_GELE01", "", "", -2, 40.0);
		AddNpc(157, 20024, "", "f_gele_57_1", 1929.394043, 166.813446, 79.72261, 0.0, "PARTY_Q3_GELE02", "", "", -2, 40.0);
		AddNpc(158, 147392, "Treasure Box 1", "f_gele_57_1", 22.0, 168.919998, -979.039978, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 1461.145996, 166.813446, 384.514771, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 1247.689209, 166.813446, 626.081055, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 1321.018433, 166.813446, 463.783112, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 1560.62085, 166.813446, 501.187653, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 1625.515991, 166.813446, 721.466431, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 1484.598511, 166.813446, 924.055542, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 1370.013428, 166.813446, 921.286987, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 1201.996582, 167.15802, 969.878113, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 1003.929321, 229.147797, 889.204956, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 758.898987, 267.467743, 893.620544, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 572.595215, 267.467743, 932.108582, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 465.37323, 267.467743, 992.330505, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 448.743469, 267.467743, 1161.481445, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 434.14801, 267.467743, 1290.530273, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 802.425049, 267.467743, 1411.518311, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 934.828491, 267.467743, 1316.140259, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 922.610046, 267.467743, 1127.583008, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 1027.951538, 251.102554, 1048.904907, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 1586.069458, 166.813446, 67.582085, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 1665.071777, 166.813446, -46.446289, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 1848.490112, 166.813446, -62.989464, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 1960.662231, 166.813446, 62.02409, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 1570.407227, 166.813446, 217.951309, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 1917.5271, 166.813446, 207.245834, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(159, 47201, "Discolored Grass Of Siauliai", "f_gele_57_1", 1810.396484, 166.813446, 314.759003, 0.0, "GELE571_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(160, 20026, "", "f_gele_57_1", -141.156006, 95.989105, 405.886749, 0.0, "", "GELE571_MQ_04_TGT", "", -2, 300.0);
		AddNpc(160, 20026, "", "f_gele_57_1", 1045.46936, 140.286774, 628.811768, 0.0, "", "GELE571_MQ_04_TGT", "", -2, 300.0);
		AddNpc(160, 20026, "", "f_gele_57_1", 306.586731, 95.989098, 409.658081, 0.0, "", "GELE571_MQ_04_TGT", "", -2, 300.0);
		AddNpc(160, 20026, "", "f_gele_57_1", 737.128052, 95.989098, 431.842133, 0.0, "", "GELE571_MQ_04_TGT", "", -2, 300.0);
	}
}
