// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_gele_57_2 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(104, 147405, "Paladin Follower B3", "f_gele_57_2", -137.54689, 375.389587, -432.8909, -74.0, "GELE572_NPC_BASIL", "", "", -2, 40.0);
		AddNpc(105, 20026, "", "f_gele_57_2", -79.04425, 375.389587, -871.472107, 0.0, "", "GELE572_MQ_01", "", -2, 200.0);
		AddNpc(131, 147450, "Wild Carnivore", "f_gele_57_2", 1014.0, 462.0, 1678.0, -90.0, "GELE572_MQ_07", "", "", -2, 40.0);
		AddNpc(137, 147404, "Paladin Follower B2", "f_gele_57_2", 193.133362, 375.389587, -428.808044, -76.0, "GELE572_NPC_MORI", "", "", -2, 40.0);
		AddNpc(138, 153067, "Bright Thorny Flower", "f_gele_57_2", 983.677429, 503.8573, -1148.678345, 0.0, "", "GELE572_MQ_05_001", "", -2, 40.0);
		AddNpc(139, 153068, "Big Bright Thorny Flower", "f_gele_57_2", 975.066345, 503.8573, -1131.041992, 12.0, "GELE572_MQ_05", "", "", -2, 40.0);
		AddNpc(144, 147462, "Mushcaria", "f_gele_57_2", -1136.0, 462.0, 417.0, -71.0, "GELE572_MQ_09", "", "", -2, 1.0);
		AddNpc(150, 147394, "Treasure Box 4", "f_gele_57_2", -659.0, 418.98999, -72.389999, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(153, 147392, "Treasure Box 1", "f_gele_57_2", -1049.219971, 418.98999, -641.809998, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
	}
}
