// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_katyn_13 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(95, 12081, "Owl Sculpture", "f_katyn_13", -663.0, 238.0, -797.0, -90.0, "KATYN13_1_OWLBOSS", "", "", -2, 25.0);
		AddNpc(96, 48004, "Owl Sculpture", "f_katyn_13", -353.0, 120.0, -2081.0, -90.0, "KATYN13_1_KEYNPC", "", "", -2, 25.0);
		AddNpc(97, 48004, "Owl Sculpture", "f_katyn_13", 809.0, 239.0, -960.0, -90.0, "KATYN13_1_OWLJUNIOR1", "", "", -2, 25.0);
		AddNpc(98, 48004, "Owl Sculpture", "f_katyn_13", 909.0, 239.0, 1010.0, -90.0, "KATYN13_1_OWLJUNIOR2", "", "", -2, 25.0);
		AddNpc(99, 48024, "Katyn13 1 Owljunior3", "f_katyn_13", -1180.0, 238.0, 977.0, -90.0, "KATYN13_1_OWLJUNIOR3", "", "", -2, 25.0);
		AddNpc(701, 20041, "", "f_katyn_13", -665.666992, 238.810196, -1326.814087, -95.0, "", "KATYN13_1_KEY_SUB1_TRIGGER", "", -2, 10.0);
		AddNpc(702, 20041, "", "f_katyn_13", 1188.0, 239.0, 303.0, -90.0, "", "KATYN13_1_TO_OWLJUNIOR2_S1_TRIGGER", "", -2, 200.0);
		AddNpc(704, 20041, "", "f_katyn_13", -897.228455, 237.826294, 202.159912, -90.0, "", "KATYN13_1_TO_OWLJUNIOR3_S1_TRIGGER", "", -2, 10.0);
		AddNpc(711, 48023, "Katyn13 Addquest3 Npc", "f_katyn_13", 8.0, 240.0, 1440.0, -60.0, "KATYN13_ADDQUEST3_NPC", "", "", -2, 1.0);
		AddNpc(712, 48024, "Katyn13 Addquest3 Npc", "f_katyn_13", 14.0, 239.0, 1455.0, -40.0, "KATYN13_ADDQUEST3_NPC", "", "", -2, 1.0);
		AddNpc(713, 48021, "Katyn13 Addquest3 Npc", "f_katyn_13", 25.0, 240.0, 1441.0, 70.0, "KATYN13_ADDQUEST3_NPC", "", "", -2, 1.0);
		AddNpc(717, 46212, "Box", "f_katyn_13", -1330.0, 237.0, 255.0, 90.0, "KATYN13_ADDQUEST4_NPC", "KATYN13_ADDQUEST4_TRIGGER", "", -2, 350.0);
		AddNpc(718, 46212, "Box", "f_katyn_13", -1336.0, 237.0, 274.0, 90.0, "KATYN13_ADDQUEST4_NPC", "KATYN13_ADDQUEST4_TRIGGER", "", -2, 350.0);
		AddNpc(719, 46212, "Box", "f_katyn_13", -1321.0, 237.0, 269.0, 90.0, "KATYN13_ADDQUEST4_NPC", "KATYN13_ADDQUEST4_TRIGGER", "", -2, 350.0);
		AddNpc(723, 40095, "", "f_katyn_13", 20.360001, 240.759995, 1426.140015, -90.0, "KATYN13_ADDQUEST8_NPC", "KATYN13_ADDQUEST3_TRIGGER1", "", -2, 350.0);
		AddNpc(750, 20041, "", "f_katyn_13", -985.0, 199.0, -2369.0, -90.0, "", "KATYN13_1_TO_2_TRIGGER", "", -2, 300.0);
		AddNpc(754, 48004, "Owl Sculpture", "f_katyn_13", -1180.0, 238.0, 977.0, -90.0, "KATYN13_1_OWLJUNIOR3_AFTER", "", "", -2, 40.0);
		AddNpc(761, 20026, "", "f_katyn_13", -1211.791626, 288.182098, 1237.366699, 0.0, "", "JOB_THAUELE5_1_TRIGGER", "", -2, 220.0);
		AddNpc(766, 147392, "Treasure Box 1", "f_katyn_13", -752.208191, 237.826294, 218.062744, -90.0, "KATYN13_1_TO_OWLJUNIOR3_S1_BOX", "", "", -2, 40.0);
		AddNpc(767, 147372, "Empty Npc", "f_katyn_13", -737.901367, 238.810196, -1405.335571, 0.0, "KATYN13_1_KEY_SUB1_TRUFFLE", "", "", -2, 10.0);
		AddNpc(768, 153059, "Closing Device", "f_katyn_13", 719.216248, 288.663116, -367.085602, -134.0, "PARTY_Q7_DEVICE", "", "", -2, 40.0);
		AddNpc(769, 147369, "Party Q7 Device02", "f_katyn_13", 718.771362, 288.662964, -368.155945, -129.0, "", "PARTY_Q7_DEVICE02", "", -2, 40.0);
		AddNpc(773, 147392, "Treasure Box 1", "f_katyn_13", -1017.590027, 237.899994, -1066.069946, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(774, 155041, "Village Lada3 Down", "f_katyn_13", 1987.850708, 238.989502, -252.836578, 0.0, "CHAR120_MSTEP5_NPC1", "CHAR120_MSTEP5_NPC1_IN", "", -2, 150.0);
		AddNpc(775, 152002, "Old Man", "f_katyn_13", 1930.830933, 238.989502, -236.807907, -21.0, "CHAR120_MSTEP6_1_NPC1", "", "", -2, 40.0);
		AddNpc(776, 20138, "Cedric", "f_katyn_13", 1896.36377, 238.989502, -260.493042, 0.0, "CHAR120_MSTEP6_1_NPC2", "", "", -2, 40.0);
		AddNpc(777, 20154, "Gentleman 8", "f_katyn_13", 1923.415283, 238.989502, -189.967453, -43.0, "CHAR120_MSTEP6_1_NPC3", "", "", -2, 40.0);
		AddNpc(778, 152001, "Ordinary Wife", "f_katyn_13", 2014.0, 238.0, -226.0, -43.0, "CHAR120_MSTEP5_2_NPC3", "", "", -2, 40.0);
		AddNpc(780, 147481, "Nalia", "f_katyn_13", 1987.850708, 238.989502, -252.836578, 0.0, "CHAR120_MSTEP5_NPC2", "", "", -2, 40.0);
		AddNpc(781, 20026, "", "f_katyn_13", 1066.655273, 238.611511, -827.727234, 0.0, "", "CHAR220_MSETP2_2_1_GEN_INIT", "", -2, 40.0);
	}
}
