// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_katyn_45_2 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(10, 155051, "Plateau Magic Circle Activation Device", "f_katyn_45_2", 1980.953857, 20.594999, 754.661682, 0.0, "DTACURLING", "", "", -2, 40.0);
		AddNpc(11, 155051, "Plateau Magic Circle Activation Device", "f_katyn_45_2", -759.319214, 202.37915, -940.178833, 0.0, "KATYN_45_2_NUMBER_BASEBALL", "", "", -2, 40.0);
		AddNpc(12, 147501, "Broken Obelisk", "f_katyn_45_2", 872.940552, 118.260696, 4.663696, -35.0, "MONSTER_PAIR_GIMMICK", "", "", -2, 40.0);
		AddNpc(14, 157004, "Dievdirbys Male2", "f_katyn_45_2", -838.852661, 328.979889, 1759.452515, -98.0, "KATYN_45_2_AJEL1", "", "", -2, 40.0);
		AddNpc(15, 157004, "Dievdirbys Male2", "f_katyn_45_2", 1320.712524, 118.540192, -397.539612, -156.0, "KATYN_45_2_AJEL2", "", "", -2, 40.0);
		AddNpc(16, 48004, "Owl Sculpture", "f_katyn_45_2", 104.657433, 198.536697, -381.359955, -63.0, "KATYN_45_2_OWL1", "", "", -2, 40.0);
		AddNpc(17, 48004, "Owl Sculpture", "f_katyn_45_2", 414.268494, 233.895813, 1118.299683, -72.0, "KATYN_45_2_OWL2", "", "", -2, 40.0);
		AddNpc(18, 48004, "Owl Sculpture", "f_katyn_45_2", 1272.419678, 118.4599, -413.683807, -75.0, "KATYN_45_2_OWL3", "", "", -2, 40.0);
		AddNpc(19, 48004, "Owl Sculpture", "f_katyn_45_2", 1801.720703, 119.4319, -1679.902344, -52.0, "KATYN_45_2_OWL4", "", "", -2, 40.0);
		AddNpc(20, 156005, "Dievdirbys", "f_katyn_45_2", -712.923218, 328.979889, 1680.219116, -106.0, "KATYN_45_2_ESOL", "", "", -2, 40.0);
		AddNpc(21, 157005, "Dievdirbys Male3", "f_katyn_45_2", -775.414246, 328.979889, 1558.860474, -18.0, "KATYN_45_2_SCULPTOR1", "", "", -2, 40.0);
		AddNpc(22, 156005, "Dievdirbys", "f_katyn_45_2", -20.052444, 244.818985, 994.082458, -94.0, "KATYN_45_2_SCULPTOR2", "", "", -2, 40.0);
		AddNpc(24, 154064, "", "f_katyn_45_2", 1218.498779, 118.3778, -433.981812, 0.0, "KATYN_45_2_SQ_5_DARK", "", "", -2, 40.0);
		AddNpc(24, 154064, "", "f_katyn_45_2", 1334.068359, 118.358467, -331.757568, 0.0, "KATYN_45_2_SQ_5_DARK", "", "", -2, 40.0);
		AddNpc(24, 154064, "", "f_katyn_45_2", 1318.22522, 118.941231, -499.601563, 0.0, "KATYN_45_2_SQ_5_DARK", "", "", -2, 40.0);
		AddNpc(24, 154064, "", "f_katyn_45_2", 1244.593262, 118.260696, -298.777832, 0.0, "KATYN_45_2_SQ_5_DARK", "", "", -2, 40.0);
		AddNpc(24, 154064, "", "f_katyn_45_2", 1118.487671, 118.260696, -428.254639, 0.0, "KATYN_45_2_SQ_5_DARK", "", "", -2, 40.0);
		AddNpc(24, 154064, "", "f_katyn_45_2", 1409.325806, 118.537697, -459.742615, 0.0, "KATYN_45_2_SQ_5_DARK", "", "", -2, 40.0);
		AddNpc(25, 151031, "Piece Of Wood", "f_katyn_45_2", -49.413086, 244.813629, 1047.550537, -149.0, "", "", "", -2, 40.0);
		AddNpc(25, 151031, "Piece Of Wood", "f_katyn_45_2", -33.378082, 244.818817, 1056.720947, -149.0, "", "", "", -2, 40.0);
		AddNpc(25, 151031, "Piece Of Wood", "f_katyn_45_2", -18.397589, 244.823654, 1065.179077, -149.0, "", "", "", -2, 40.0);
		AddNpc(25, 151031, "Piece Of Wood", "f_katyn_45_2", 7.983742, 244.830688, 1055.301758, 133.0, "", "", "", -2, 40.0);
		AddNpc(25, 151031, "Piece Of Wood", "f_katyn_45_2", 19.043488, 244.83316, 1042.573975, 133.0, "", "", "", -2, 40.0);
		AddNpc(26, 47202, "Discolored Grass Of Siauliai", "f_katyn_45_2", 334.309906, 167.725708, 839.118042, 0.0, "KATYN_45_2_SQ_9_HERB", "", "", -2, 40.0);
		AddNpc(26, 47202, "Discolored Grass Of Siauliai", "f_katyn_45_2", 677.446289, 166.561096, 871.305176, 0.0, "KATYN_45_2_SQ_9_HERB", "", "", -2, 40.0);
		AddNpc(26, 47202, "Discolored Grass Of Siauliai", "f_katyn_45_2", 1139.037231, 119.168694, 560.510925, 0.0, "KATYN_45_2_SQ_9_HERB", "", "", -2, 40.0);
		AddNpc(26, 47202, "Discolored Grass Of Siauliai", "f_katyn_45_2", 906.166443, 119.54245, 194.254257, 0.0, "KATYN_45_2_SQ_9_HERB", "", "", -2, 40.0);
		AddNpc(26, 47202, "Discolored Grass Of Siauliai", "f_katyn_45_2", 546.165894, 118.597847, 198.52655, 0.0, "KATYN_45_2_SQ_9_HERB", "", "", -2, 40.0);
		AddNpc(26, 47202, "Discolored Grass Of Siauliai", "f_katyn_45_2", 101.804176, 118.260696, 76.914856, 0.0, "KATYN_45_2_SQ_9_HERB", "", "", -2, 40.0);
		AddNpc(27, 20026, "", "f_katyn_45_2", 442.227142, 165.728699, 1684.955811, 0.0, "", "KATYN_45_2_SQ_13", "", -2, 200.0);
		AddNpc(30, 157004, "Dievdirbys Male2", "f_katyn_45_2", 1817.139038, 119.4319, -1656.538452, -80.0, "KATYN_45_2_AJEL3", "", "", -2, 40.0);
		AddNpc(1000, 147392, "Treasure Box 1", "f_katyn_45_2", 339.440002, 165.830002, 1384.530029, 45.0, "TREASUREBOX_LV", "", "", -2, 0.0);
	}
}
