// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_katyn_14 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(1, 20107, "Mid Commander (Female)", "f_katyn_14", 2598.085938, 81.894798, -881.26947, 37.0, "KATYN14_LAIMUNAS", "", "", -2, 30.0);
		AddNpc(2, 20012, "Eastern Woods Scout", "f_katyn_14", 2579.814453, 81.894798, -913.585083, 91.0, "KATYN14_LAIMUNAS_SOL", "KATYN14_LAIMUNAS_SOL", "", -2, 30.0);
		AddNpc(2, 20012, "Eastern Woods Scout", "f_katyn_14", 2637.586914, 81.894798, -935.36377, 102.0, "KATYN14_LAIMUNAS_SOL", "KATYN14_LAIMUNAS_SOL", "", -2, 30.0);
		AddNpc(3, 20125, "Mid Commander (Male 2)", "f_katyn_14", -61.0, 176.0, -526.0, -10.62, "KATYN14_VACENIN", "", "", -2, 30.0);
		AddNpc(5, 20107, "Mid Commander (Female)", "f_katyn_14", 2630.0, 81.0, -1979.0, -90.0, "KATYN14_SUPP", "KATYN14_GOBACK", "", -2, 50.0);
		AddNpc(7, 20016, "Western Woods Scout", "f_katyn_14", 1134.0, 83.0, -1070.0, -90.0, "KATYN14_ROY", "", "", -2, 30.0);
		AddNpc(10, 20015, "View", "f_katyn_14", -1118.955688, 321.305145, 1101.80896, -90.0, "KATYN14_JOHN", "", "", -2, 30.0);
		AddNpc(11, 20020, "Fallen Soldier", "f_katyn_14", -1619.949951, 420.140533, 888.568481, -90.0, "KATYN14_JOHN_SOL", "", "", -2, 30.0);
		AddNpc(11, 20020, "Fallen Soldier", "f_katyn_14", -1890.822632, 464.38974, 1107.384033, -45.0, "KATYN14_JOHN_SOL", "", "", -2, 30.0);
		AddNpc(11, 20020, "Fallen Soldier", "f_katyn_14", -2032.244751, 466.371277, 869.353943, 0.0, "KATYN14_JOHN_SOL", "", "", -2, 30.0);
		AddNpc(11, 20020, "Fallen Soldier", "f_katyn_14", -1576.653198, 466.319977, 1210.506592, 0.0, "KATYN14_JOHN_SOL", "", "", -2, 30.0);
		AddNpc(11, 20020, "Fallen Soldier", "f_katyn_14", -1822.628662, 420.108765, 665.497314, 45.0, "KATYN14_JOHN_SOL", "", "", -2, 30.0);
		AddNpc(15, 20125, "Mid Commander (Male 2)", "f_katyn_14", -964.789978, 227.869995, -1107.689941, -90.0, "KATYN14_VACENIN_AFTER", "", "", -2, 30.0);
		AddNpc(16, 20026, "", "f_katyn_14", 989.0, 83.0, -64.0, -90.0, "", "KATYN14_PREBOSS", "", -2, 250.0);
		AddNpc(17, 20026, "", "f_katyn_14", -1442.0, 228.0, -1178.0, -90.0, "", "KATYN14_BOSS", "", -2, 180.0);
		AddNpc(21, 20026, "", "f_katyn_14", 2367.0, 83.0, -37.0, -90.0, "", "KATYN14_SUB_01", "", -2, 180.0);
		AddNpc(22, 20026, "", "f_katyn_14", 2067.0, 82.0, -1920.0, -90.0, "", "KATYN14_SUB_02", "", -2, 180.0);
		AddNpc(23, 20026, "", "f_katyn_14", 1663.0, 83.0, -1058.0, -90.0, "", "KATYN14_SUB_03", "", -2, 180.0);
		AddNpc(24, 20026, "", "f_katyn_14", 698.0, 130.0, -1238.0, -90.0, "", "KATYN14_SUB_04", "", -2, 180.0);
		AddNpc(25, 20026, "", "f_katyn_14", -311.0, 322.0, -82.0, -90.0, "", "KATYN14_SUB_05", "", -2, 180.0);
		AddNpc(26, 20026, "", "f_katyn_14", -887.0, 323.0, 314.0, -90.0, "", "KATYN14_SUB_06", "", -2, 10.0);
		AddNpc(27, 20026, "", "f_katyn_14", -1967.0, 421.0, 498.0, -90.0, "", "KATYN14_SUB_07", "", -2, 180.0);
		AddNpc(28, 20026, "", "f_katyn_14", -2999.0, 422.0, 1321.0, -90.0, "", "KATYN14_SUB_08", "", -2, 50.0);
		AddNpc(29, 20016, "Western Woods Scout", "f_katyn_14", 2199.020752, 81.351822, 476.997375, -99.0, "KATYN14_VACENIN_CHASE", "", "", -2, 30.0);
		AddNpc(30, 47161, "Lost Stuff Of Vendor 2", "f_katyn_14", 2836.0, 80.0, -1994.0, -90.0, "KATYN14_MQ_05_ITEM", "", "", -2, 180.0);
		AddNpc(30, 47161, "Lost Stuff Of Vendor 2", "f_katyn_14", 2958.0, 80.0, -1987.0, -90.0, "KATYN14_MQ_05_ITEM", "", "", -2, 180.0);
		AddNpc(30, 47161, "Lost Stuff Of Vendor 2", "f_katyn_14", 3045.0, 80.0, -2227.0, -90.0, "KATYN14_MQ_05_ITEM", "", "", -2, 180.0);
		AddNpc(30, 47161, "Lost Stuff Of Vendor 2", "f_katyn_14", 3013.0, 81.0, -2319.0, -90.0, "KATYN14_MQ_05_ITEM", "", "", -2, 180.0);
		AddNpc(30, 47161, "Lost Stuff Of Vendor 2", "f_katyn_14", 3017.0, 80.0, -2116.0, -90.0, "KATYN14_MQ_05_ITEM", "", "", -2, 180.0);
		AddNpc(30, 47161, "Lost Stuff Of Vendor 2", "f_katyn_14", 2848.0, 81.0, -2283.0, -90.0, "KATYN14_MQ_05_ITEM", "", "", -2, 180.0);
		AddNpc(30, 47161, "Lost Stuff Of Vendor 2", "f_katyn_14", 2833.0, 81.0, -2193.0, -90.0, "KATYN14_MQ_05_ITEM", "", "", -2, 180.0);
		AddNpc(509, 20016, "Western Woods Scout", "f_katyn_14", -28.0, 177.0, -453.0, -45.0, "KATYN14_PIL_SOL", "", "", -2, 20.0);
		AddNpc(509, 20016, "Western Woods Scout", "f_katyn_14", -97.0, 177.0, -394.0, 0.0, "KATYN14_PIL_SOL", "", "", -2, 20.0);
		AddNpc(509, 20016, "Western Woods Scout", "f_katyn_14", -47.0, 177.0, -370.0, -90.0, "KATYN14_PIL_SOL", "", "", -2, 20.0);
		AddNpc(584, 47170, "Soldier'S Relic", "f_katyn_14", -2724.932617, 422.170105, 1381.919678, 20.0, "KATYN14_SUB_WOLF", "KATYN14_SUB_08", "", -2, 100.0);
		AddNpc(586, 147461, "Small Griba", "f_katyn_14", 1879.08374, 81.894951, -1287.695923, -35.0, "KATYN14_SUB_02_MUSH", "", "", -2, 10.0);
		AddNpc(586, 147461, "Small Griba", "f_katyn_14", 1877.881958, 81.894913, -1275.425537, -79.0, "KATYN14_SUB_02_MUSH", "", "", -2, 10.0);
		AddNpc(586, 147461, "Small Griba", "f_katyn_14", 1884.231201, 81.895027, -1301.561157, 0.0, "KATYN14_SUB_02_MUSH", "", "", -2, 10.0);
		AddNpc(586, 147461, "Small Griba", "f_katyn_14", 1883.367676, 81.894936, -1271.412964, 0.0, "KATYN14_SUB_02_MUSH", "", "", -2, 10.0);
		AddNpc(586, 147461, "Small Griba", "f_katyn_14", 1891.089478, 81.894966, -1263.63916, 0.0, "KATYN14_SUB_02_MUSH", "", "", -2, 10.0);
		AddNpc(586, 147461, "Small Griba", "f_katyn_14", 1890.190552, 81.895035, -1289.267578, 0.0, "KATYN14_SUB_02_MUSH", "", "", -2, 10.0);
		AddNpc(586, 147461, "Small Griba", "f_katyn_14", 1902.48938, 81.895042, -1274.450562, 0.0, "KATYN14_SUB_02_MUSH", "", "", -2, 10.0);
		AddNpc(586, 147461, "Small Griba", "f_katyn_14", 1908.02063, 81.895119, -1297.113281, 0.0, "KATYN14_SUB_02_MUSH", "", "", -2, 10.0);
		AddNpc(586, 147461, "Small Griba", "f_katyn_14", 1897.696411, 81.895103, -1301.853149, 0.0, "KATYN14_SUB_02_MUSH", "", "", -2, 10.0);
		AddNpc(587, 40110, "Statue Of Goddess Zemyna", "f_katyn_14", -2765.0, 306.0, -1058.0, -50.0, "F_KATYN_14_EV_55_001", "F_KATYN_14_EV_55_001", "F_KATYN_14_EV_55_001", -2, 150.0);
		AddNpc(589, 151051, "Black Crystal", "f_katyn_14", 2147.652344, 81.895149, -908.13501, 0.0, "", "", "", -2, 40.0);
		AddNpc(601, 147392, "Treasure Box 1", "f_katyn_14", -379.140015, 248.789993, -1016.75, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(602, 20135, "Foreseeing Owl", "f_katyn_14", -3166.663818, 422.170013, 1573.605835, -82.0, "HTA_KATYN_14_OWL", "", "", -2, 5.0);
	}
}
