// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_katyn_18 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(4, 154017, "Ghost Soldier", "f_katyn_18", 1940.119263, 373.189148, -2119.98291, 0.0, "KATYN_18_RE_SQ_NPC_1", "", "", -2, 40.0);
		AddNpc(5, 155131, "Ghost Soldier2", "f_katyn_18", 840.306763, 524.621765, -564.850037, 0.0, "KATYN_18_RE_SQ_NPC_2", "", "", -2, 40.0);
		AddNpc(6, 155132, "Ghost Soldier3", "f_katyn_18", 721.443176, 373.189148, -2327.269775, 0.0, "KATYN_18_RE_SQ_NPC_3", "", "", -2, 40.0);
		AddNpc(7, 151067, "Small Wooden Chest", "f_katyn_18", 2192.732178, 373.189148, -1692.007813, 45.0, "KATYN_18_RE_SQ_OBJ_1", "", "", -2, 40.0);
		AddNpc(7, 151067, "Small Wooden Chest", "f_katyn_18", 2474.205322, 373.200928, -1691.229126, 0.0, "KATYN_18_RE_SQ_OBJ_1", "", "", -2, 40.0);
		AddNpc(7, 151067, "Small Wooden Chest", "f_katyn_18", 2464.908936, 373.189148, -2173.476563, 90.0, "KATYN_18_RE_SQ_OBJ_1", "", "", -2, 40.0);
		AddNpc(8, 46212, "Box", "f_katyn_18", 2621.12915, 373.189148, -1835.958984, 90.0, "KATYN_18_RE_SQ_OBJ_1", "", "", -2, 40.0);
		AddNpc(8, 46212, "Box", "f_katyn_18", 2281.90918, 373.189148, -2228.958008, 90.0, "KATYN_18_RE_SQ_OBJ_1", "", "", -2, 40.0);
		AddNpc(8, 46212, "Box", "f_katyn_18", 2396.672852, 373.197754, -1877.274414, 90.0, "KATYN_18_RE_SQ_OBJ_1", "", "", -2, 40.0);
		AddNpc(9, 155005, "Old Bag", "f_katyn_18", 1861.888184, 426.268982, 140.900787, 0.0, "KATYN_18_RE_SQ_OBJ_2", "", "", -2, 40.0);
		AddNpc(9, 155005, "Old Bag", "f_katyn_18", 1760.405273, 426.268982, -450.662781, 0.0, "KATYN_18_RE_SQ_OBJ_2", "", "", -2, 40.0);
		AddNpc(9, 155005, "Old Bag", "f_katyn_18", 1502.821411, 525.10437, -79.644791, 0.0, "KATYN_18_RE_SQ_OBJ_2", "", "", -2, 40.0);
		AddNpc(10, 47160, "Lost Stuff Of Vendor 1", "f_katyn_18", 2188.105957, 426.268982, -27.578386, 0.0, "KATYN_18_RE_SQ_OBJ_2", "", "", -2, 40.0);
		AddNpc(10, 47160, "Lost Stuff Of Vendor 1", "f_katyn_18", 2003.99585, 426.268982, -246.878967, 0.0, "KATYN_18_RE_SQ_OBJ_2", "", "", -2, 40.0);
		AddNpc(10, 47160, "Lost Stuff Of Vendor 1", "f_katyn_18", 1521.627563, 571.308777, 273.368195, 0.0, "KATYN_18_RE_SQ_OBJ_2", "", "", -2, 40.0);
		AddNpc(10, 47160, "Lost Stuff Of Vendor 1", "f_katyn_18", 1547.166992, 522.959656, -449.560303, 0.0, "KATYN_18_RE_SQ_OBJ_2", "", "", -2, 40.0);
		AddNpc(10, 47160, "Lost Stuff Of Vendor 1", "f_katyn_18", 1268.801636, 571.394104, -94.241013, 0.0, "KATYN_18_RE_SQ_OBJ_2", "", "", -2, 40.0);
		AddNpc(11, 147469, "No Shadow Npc", "f_katyn_18", 642.038391, 524.814636, -940.860291, 0.0, "KATYN_18_RE_SQ_OBJ_3_DUMMY", "", "", -2, 40.0);
		AddNpc(11, 147469, "No Shadow Npc", "f_katyn_18", 625.821655, 526.289795, -449.653381, 0.0, "KATYN_18_RE_SQ_OBJ_3_DUMMY", "", "", -2, 40.0);
		AddNpc(11, 147469, "No Shadow Npc", "f_katyn_18", 428.795593, 524.960876, -414.107849, 0.0, "KATYN_18_RE_SQ_OBJ_3_DUMMY", "", "", -2, 40.0);
		AddNpc(11, 147469, "No Shadow Npc", "f_katyn_18", 403.498718, 524.960876, -54.556713, 0.0, "KATYN_18_RE_SQ_OBJ_3_DUMMY", "", "", -2, 40.0);
		AddNpc(11, 147469, "No Shadow Npc", "f_katyn_18", 493.839355, 550.514526, -663.959778, 0.0, "KATYN_18_RE_SQ_OBJ_3_DUMMY", "", "", -2, 40.0);
		AddNpc(11, 147469, "No Shadow Npc", "f_katyn_18", 385.57312, 552.625244, -1035.882446, 0.0, "KATYN_18_RE_SQ_OBJ_3_DUMMY", "", "", -2, 40.0);
		AddNpc(11, 147469, "No Shadow Npc", "f_katyn_18", 129.152191, 552.625244, -207.780472, 0.0, "KATYN_18_RE_SQ_OBJ_3_DUMMY", "", "", -2, 40.0);
		AddNpc(12, 151018, "No Shadow Npc", "f_katyn_18", 19.0, 552.625244, -565.0, 0.0, "KATYN_18_RE_SQ_OBJ_3_1", "", "", -2, 40.0);
		AddNpc(13, 151018, "No Shadow Npc", "f_katyn_18", 160.0, 552.625244, -690.0, 0.0, "KATYN_18_RE_SQ_OBJ_3_2", "", "", -2, 40.0);
		AddNpc(14, 151018, "No Shadow Npc", "f_katyn_18", 5.0, 552.625244, -747.0, 0.0, "KATYN_18_RE_SQ_OBJ_3_3", "", "", -2, 40.0);
		AddNpc(15, 147469, "No Shadow Npc", "f_katyn_18", 62.0, 552.625244, -653.0, 0.0, "KATYN_18_RE_SQ_OBJ_3", "", "", -2, 40.0);
		AddNpc(16, 155005, "Old Bag", "f_katyn_18", 62.0, 552.625244, -653.0, 0.0, "", "KATYN_18_RE_SQ_OBJ_3_KEEP", "", -2, 40.0);
		AddNpc(17, 20026, "", "f_katyn_18", 19.0, 552.625244, -565.0, 0.0, "", "KATYN_18_RE_SQ_OBJ_3_EFFECT", "", -2, 40.0);
		AddNpc(17, 20026, "", "f_katyn_18", 160.0, 552.625244, -690.0, 0.0, "", "KATYN_18_RE_SQ_OBJ_3_EFFECT", "", -2, 40.0);
		AddNpc(17, 20026, "", "f_katyn_18", 5.0, 552.625244, -747.0, 0.0, "", "KATYN_18_RE_SQ_OBJ_3_EFFECT", "", -2, 40.0);
		AddNpc(18, 151019, "No Shadow Npc", "f_katyn_18", 18.348349, 417.787201, -2562.615723, 0.0, "KATYN_18_RE_SQ_OBJ_4", "", "", -2, 40.0);
		AddNpc(18, 151019, "No Shadow Npc", "f_katyn_18", -64.339645, 450.864868, -2249.016357, 0.0, "KATYN_18_RE_SQ_OBJ_4", "", "", -2, 40.0);
		AddNpc(18, 151019, "No Shadow Npc", "f_katyn_18", 80.579422, 491.027283, -1866.233765, 0.0, "KATYN_18_RE_SQ_OBJ_4", "", "", -2, 40.0);
		AddNpc(18, 151019, "No Shadow Npc", "f_katyn_18", 186.646332, 413.93988, -2165.960205, 0.0, "KATYN_18_RE_SQ_OBJ_4", "", "", -2, 40.0);
		AddNpc(18, 151019, "No Shadow Npc", "f_katyn_18", 427.884705, 372.96463, -2014.906372, 0.0, "KATYN_18_RE_SQ_OBJ_4", "", "", -2, 40.0);
		AddNpc(18, 151019, "No Shadow Npc", "f_katyn_18", 342.616913, 373.05481, -2425.142578, 0.0, "KATYN_18_RE_SQ_OBJ_4", "", "", -2, 40.0);
		AddNpc(19, 147417, "Altar", "f_katyn_18", -1039.0, 500.280914, -183.0, -90.0, "KATYN_18_RE_SQ_OBJ_5", "", "", -2, 40.0);
		AddNpc(20, 20026, "", "f_katyn_18", -1039.0, 500.280914, -183.0, 0.0, "", "KATYN_18_RE_SQ_OBJ_5_EFFECT", "", -2, 40.0);
		AddNpc(1000, 147392, "Treasure Box 1", "f_katyn_18", 1898.660034, 373.290009, -1206.72998, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
	}
}
