// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_katyn_7_2 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(3, 48002, "Owl Sculpture", "f_katyn_7_2", 1902.0, 282.0, -3093.0, -90.0, "KATYN72_SECTOR_01", "", "", -2, 40.0);
		AddNpc(4, 48004, "Owl Sculpture", "f_katyn_7_2", 1517.0, 297.0, -752.0, -90.0, "KATYN72_SECTOR_02", "", "", -2, 40.0);
		AddNpc(5, 48002, "Owl Sculpture", "f_katyn_7_2", 1845.0, 295.0, 658.0, -90.0, "KATYN72_SECTOR_03", "", "", -2, 40.0);
		AddNpc(6, 48002, "Owl Sculpture", "f_katyn_7_2", 1794.0, 298.0, 1971.0, -90.0, "KATYN72_SECTOR_04", "", "", -2, 40.0);
		AddNpc(7, 20019, "Western Woods Scout", "f_katyn_7_2", 639.0, 441.0, 2021.0, -45.0, "KATYN72_BOSS", "", "", -2, 40.0);
		AddNpc(10, 20019, "Western Woods Scout", "f_katyn_7_2", 2450.0, 184.0, -2727.0, -90.0, "KATYN72_CORPSE", "", "", -2, 40.0);
		AddNpc(11, 153054, "Wide Leaf Vine Blue", "f_katyn_7_2", 3229.0, 184.0, -4562.0, -90.0, "KATYN72_RASSFLY", "", "", -2, 40.0);
		AddNpc(12, 20019, "Western Woods Scout", "f_katyn_7_2", 3856.0, 197.0, 1393.0, -90.0, "KATYN72_TIED", "", "", -2, 40.0);
		AddNpc(13, 20020, "Fallen Soldier", "f_katyn_7_2", 2520.0, 298.0, 2356.0, -90.0, "KATYN72_GHOST", "", "", -2, 40.0);
		AddNpc(14, 20020, "Fallen Soldier", "f_katyn_7_2", 2561.120117, 297.720001, 2305.379883, -90.0, "", "", "", -2, 40.0);
		AddNpc(22, 20026, "", "f_katyn_7_2", 3690.819824, 183.039627, -3878.824707, -90.0, "", "KATYN72_SUB_03", "", -2, 50.0);
		AddNpc(28, 20026, "", "f_katyn_7_2", 3868.834473, 229.694794, -277.313843, -90.0, "", "KATYN7_2_ADD_BOSS_01", "", -2, 10.0);
		AddNpc(29, 147338, "Boulder", "f_katyn_7_2", 3974.0, 182.0, -4449.0, 0.0, "", "KATYN7_2_BLOCK", "", -2, 110.0);
		AddNpc(30, 20019, "Western Woods Scout", "f_katyn_7_2", 1728.0, 329.0, -2797.0, -45.0, "KATYN72_CORPSE", "", "", -2, 40.0);
		AddNpc(31, 20019, "Western Woods Scout", "f_katyn_7_2", 1864.0, 329.0, -2613.0, 0.0, "KATYN72_CORPSE", "", "", -2, 40.0);
		AddNpc(32, 20019, "Western Woods Scout", "f_katyn_7_2", 2227.0, 329.0, -2436.0, 45.0, "KATYN72_CORPSE", "", "", -2, 40.0);
		AddNpc(33, 20019, "Western Woods Scout", "f_katyn_7_2", 2691.0, 184.0, -2528.0, 90.0, "KATYN72_CORPSE", "", "", -2, 40.0);
		AddNpc(34, 20019, "Western Woods Scout", "f_katyn_7_2", 2827.0, 184.0, -2899.0, -90.0, "KATYN72_CORPSE", "", "", -2, 40.0);
		AddNpc(35, 20019, "Western Woods Scout", "f_katyn_7_2", 2694.0, 184.0, -3215.0, -45.0, "KATYN72_CORPSE", "", "", -2, 40.0);
		AddNpc(36, 20019, "Western Woods Scout", "f_katyn_7_2", 2454.0, 184.0, -3146.0, 0.0, "KATYN72_CORPSE", "", "", -2, 40.0);
		AddNpc(37, 20019, "Western Woods Scout", "f_katyn_7_2", 2535.0, 184.0, -3298.0, -90.0, "KATYN72_CORPSE", "", "", -2, 40.0);
		AddNpc(38, 20019, "Western Woods Scout", "f_katyn_7_2", 2230.0, 281.0, -3166.0, -90.0, "KATYN72_CORPSE", "", "", -2, 40.0);
		AddNpc(40, 153054, "Wide Leaf Vine Blue", "f_katyn_7_2", 3363.790039, 183.0, -4412.350098, -90.0, "KATYN72_RASSFLY", "", "", -2, 40.0);
		AddNpc(41, 153054, "Wide Leaf Vine Blue", "f_katyn_7_2", 3564.47998, 183.0, -4689.390137, -90.0, "KATYN72_RASSFLY", "", "", -2, 40.0);
		AddNpc(42, 153054, "Wide Leaf Vine Blue", "f_katyn_7_2", 3667.340088, 183.029999, -4398.580078, -90.0, "KATYN72_RASSFLY", "", "", -2, 40.0);
		AddNpc(43, 153054, "Wide Leaf Vine Blue", "f_katyn_7_2", 3774.449951, 183.0, -4530.77002, -90.0, "KATYN72_RASSFLY", "", "", -2, 40.0);
		AddNpc(50, 20019, "Western Woods Scout", "f_katyn_7_2", 3890.0, 197.0, 1223.0, -90.0, "KATYN72_TIED", "", "", -2, 40.0);
		AddNpc(51, 20019, "Western Woods Scout", "f_katyn_7_2", 3929.0, 197.0, 1056.0, -90.0, "KATYN72_TIED", "", "", -2, 40.0);
		AddNpc(52, 20019, "Western Woods Scout", "f_katyn_7_2", 3899.0, 197.0, 867.0, -90.0, "KATYN72_TIED", "", "", -2, 40.0);
		AddNpc(53, 20019, "Western Woods Scout", "f_katyn_7_2", 3800.0, 197.0, 674.0, -90.0, "KATYN72_TIED", "", "", -2, 40.0);
		AddNpc(54, 20019, "Western Woods Scout", "f_katyn_7_2", 3590.0, 197.0, 791.0, -90.0, "KATYN72_TIED", "", "", -2, 40.0);
		AddNpc(55, 20019, "Western Woods Scout", "f_katyn_7_2", 3520.0, 268.0, 894.0, -90.0, "KATYN72_TIED", "", "", -2, 40.0);
		AddNpc(56, 20019, "Western Woods Scout", "f_katyn_7_2", 3395.0, 294.0, 725.0, -90.0, "KATYN72_TIED", "", "", -2, 40.0);
		AddNpc(57, 20019, "Western Woods Scout", "f_katyn_7_2", 2885.0, 343.0, 1089.0, -90.0, "KATYN72_TIED", "", "", -2, 40.0);
		AddNpc(58, 20019, "Western Woods Scout", "f_katyn_7_2", 3230.0, 297.0, 1143.0, -90.0, "KATYN72_TIED", "", "", -2, 40.0);
		AddNpc(60, 20020, "Fallen Soldier", "f_katyn_7_2", 2528.600098, 297.720001, 2437.409912, -90.0, "", "", "", -2, 40.0);
		AddNpc(61, 20020, "Fallen Soldier", "f_katyn_7_2", 2584.679932, 297.720001, 2347.780029, -90.0, "", "", "", -2, 40.0);
		AddNpc(62, 20020, "Fallen Soldier", "f_katyn_7_2", 2645.110107, 297.720001, 2362.620117, -90.0, "", "", "", -2, 40.0);
		AddNpc(10001, 20025, "", "f_katyn_7_2", -390.0, 257.0, -2288.0, 0.0, "F_KATYN_7_2_HIDDENNPC_BOARD", "", "", -2, 30.0);
		AddNpc(10018, 20150, "Veteran Miner 2", "f_katyn_7_2", 2444.800049, 345.059998, -243.169998, 0.0, "KATYN_7_2_HQ01_NPC02", "", "", -2, 40.0);
		AddNpc(10019, 20026, "", "f_katyn_7_2", 2118.97998, 305.470001, -769.719971, 0.0, "", "KATYN_7_2_HQ01_NPC01", "", -2, 60.0);
		AddNpc(10024, 147372, "Empty Npc", "f_katyn_7_2", 3580.670166, 229.694794, -478.870758, 0.0, "KATYN7_2_FALL", "", "", -2, 40.0);
		AddNpc(10025, 147460, "Little Golem", "f_katyn_7_2", 3624.385986, 182.995331, -3687.739014, 151.0, "KATYN72_GOLEMLET", "", "", -2, 40.0);
		AddNpc(10026, 20026, "", "f_katyn_7_2", 3758.962891, 229.694794, -578.988831, 0.0, "", "KATYN_7_2_JOB_4", "", -2, 300.0);
		AddNpc(10027, 47190, "Literature 1", "f_katyn_7_2", 545.986267, 296.359985, -3200.732422, 12.0, "KATYN7_2_HIDDEN_EVENT", "", "", -2, 40.0);
		AddNpc(10029, 147392, "Treasure Box 1", "f_katyn_7_2", 3396.75, 183.100006, -4706.589844, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
	}
}
