// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_katyn_13_2 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(201, 20026, "", "f_katyn_13_2", -227.259995, 198.199997, -1965.170044, 0.0, "KATYN_13_2_HQ_01", "KATYN_13_2_HQ_01_TRIGGER01", "KATYN_13_2_HQ_01_TRIGGER02", -2, 300.0);
		AddNpc(202, 20023, "Swordsman Master", "f_katyn_13_2", -403.0, 198.199997, -1878.910034, 0.0, "KATYN_13_2_HQ_01_SMASTER", "", "", -2, 40.0);
		AddNpc(203, 20022, "Archer Master", "f_katyn_13_2", -313.730011, 198.199997, -2113.530029, 0.0, "KATYN_13_2_HQ_01_AMASTER", "", "", -2, 40.0);
		AddNpc(204, 20021, "Wizard Master", "f_katyn_13_2", -312.73999, 198.199997, -1747.030029, -74.480003, "KATYN_13_2_HQ_01_WMASTER", "", "", -2, 40.0);
		AddNpc(205, 20112, "Cleric Master", "f_katyn_13_2", -192.130005, 198.199997, -2135.659912, 0.0, "KATYN_13_2_HQ_01_CMASTER", "", "", -2, 40.0);
	}
}
