// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_katyn_7 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(3, 20026, "", "f_katyn_7", 976.0, 296.0, 187.0, -90.0, "", "KATYN7_PREBOSS", "", -2, 160.0);
		AddNpc(5, 12081, "Owl Sculpture", "f_katyn_7", -1270.0, 296.0, 1330.0, -90.0, "KATYN71_OWL_01", "", "", -2, 100.0);
		AddNpc(8, 20107, "Mid Commander (Female)", "f_katyn_7", -1280.0, 296.0, 1240.0, -90.0, "KATYN71_OFFICER", "", "", -2, 20.0);
		AddNpc(10, 20107, "Mid Commander (Female)", "f_katyn_7", -420.0, 296.0, 3440.0, -90.0, "KATYN71_OFFICER_AFTER", "", "", -2, 20.0);
		AddNpc(107, 20129, "Vacenin", "f_katyn_7", 761.0, 295.0, -3576.0, -90.0, "KATYN7_KEYNPC_1", "", "", -2, 20.0);
		AddNpc(108, 20026, "", "f_katyn_7", 1026.0, 295.0, -3727.0, -90.0, "", "KATYN7_KEYNPC_1_TRIGGER", "", -2, 200.0);
		AddNpc(506, 20107, "Mid Commander (Female)", "f_katyn_7", -1237.0, 418.0, -1204.0, -90.0, "KATYN7_KEYNPC_4", "", "", -2, 20.0);
		AddNpc(515, 20016, "Western Woods Scout", "f_katyn_7", 672.0, 295.0, -3810.0, 0.0, "KATYN_SUCH_POINT_01_SOLDIER", "", "", -2, 20.0);
		AddNpc(10002, 40070, "Bulletin Board", "f_katyn_7", 616.0, 296.0, -1575.0, 270.0, "F_KATYN_7_BOARD02", "", "", -2, 30.0);
		AddNpc(10006, 20041, "", "f_katyn_7", -124.0, 247.0, 1592.0, 0.0, "", "REPEAT_MON_GEN_TRIGGER", "", -2, 30.0);
		AddNpc(10006, 20041, "", "f_katyn_7", 190.0, 418.0, -3513.0, 0.0, "", "REPEAT_MON_GEN_TRIGGER", "", -2, 30.0);
		AddNpc(10006, 20041, "", "f_katyn_7", 372.0, 295.0, -3562.0, 0.0, "", "REPEAT_MON_GEN_TRIGGER", "", -2, 30.0);
		AddNpc(10006, 20041, "", "f_katyn_7", 329.0, 295.0, -933.0, 0.0, "", "REPEAT_MON_GEN_TRIGGER", "", -2, 30.0);
		AddNpc(10016, 20025, "", "f_katyn_7", -917.451355, 295.702423, 3306.63501, 0.0, "KATYN7_MQ06_TRACK", "", "", -2, 40.0);
		AddNpc(10018, 20016, "Western Woods Scout", "f_katyn_7", -1621.0, 295.0, 3900.0, 81.0, "KATYN71_SOLDIER01_1", "KATYN71_SOLDIER01", "", -2, 40.0);
		AddNpc(10019, 20016, "Western Woods Scout", "f_katyn_7", -1572.675415, 295.718475, 3929.487793, 129.0, "KATYN71_BOSS", "", "", -2, 40.0);
		AddNpc(10020, 20016, "Western Woods Scout", "f_katyn_7", -1542.71582, 295.718475, 3990.158447, 157.0, "KATYN71_SOLDIER01_2", "KATYN71_SOLDIER02", "", -2, 40.0);
		AddNpc(10021, 20016, "Western Woods Scout", "f_katyn_7", 994.42804, 295.707947, -3990.510742, 0.0, "KATYN7_KEYNPC_5", "", "", -2, 40.0);
		AddNpc(10023, 20026, "", "f_katyn_7", -321.417511, 247.955994, 1961.274292, 0.0, "", "JOB_ROGUE4_1_TRIGGER", "", -2, 300.0);
		AddNpc(10025, 147392, "Treasure Box 1", "f_katyn_7", -2082.189941, 344.769989, 1663.050049, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
	}
}
