// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_pilgrimroad_47 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(4, 20026, "", "f_pilgrimroad_47", -838.0, 143.0, -1050.0, 0.0, "", "REQ_SEMPLE_02_01", "", -2, 100.0);
		AddNpc(5, 20026, "", "f_pilgrimroad_47", -943.0, 154.0, 947.0, 0.0, "", "REQ_SEMPLE_02_02", "", -2, 100.0);
		AddNpc(6, 20026, "", "f_pilgrimroad_47", 461.0, 136.0, -107.0, 0.0, "", "REQ_SEMPLE_02_03", "", -2, 100.0);
		AddNpc(12, 147312, "Dropped Paper", "f_pilgrimroad_47", -843.3396, 143.383102, -1286.590942, 0.0, "PILGRIM47_DMSG", "", "", -2, 40.0);
		AddNpc(13, 155031, "Mutated Tree Root Crystal", "f_pilgrimroad_47", -2224.717041, 44.515499, -1564.577759, 126.0, "PILGRIM47_CRYST01", "", "", -2, 30.0);
		AddNpc(14, 155031, "Mutated Tree Root Crystal", "f_pilgrimroad_47", -253.722153, 136.991592, -144.190735, 126.0, "PILGRIM47_CRYST02", "PILGRIM47_CRYST02_E", "", -2, 100.0);
		AddNpc(15, 155031, "Mutated Tree Root Crystal", "f_pilgrimroad_47", -1742.006836, 195.312241, 141.472412, 126.0, "PILGRIM47_CRYST03", "", "", -2, 40.0);
		AddNpc(16, 155031, "Mutated Tree Root Crystal", "f_pilgrimroad_47", 224.80127, 44.515564, 1481.556152, 126.0, "PILGRIM47_CRYST04", "", "", -2, 40.0);
		AddNpc(17, 155031, "Mutated Tree Root Crystal", "f_pilgrimroad_47", 1766.774048, 44.514931, -931.340271, 126.0, "PILGRIM47_CRYST05", "", "", -2, 40.0);
		AddNpc(18, 155031, "Mutated Tree Root Crystal", "f_pilgrimroad_47", 1870.297363, 137.64296, 967.205872, 126.0, "PILGRIM47_CRYST06", "", "", -2, 40.0);
		AddNpc(19, 155032, "Mutated Tree Root Crystal 2", "f_pilgrimroad_47", 1500.485229, 246.81575, 1817.772827, 126.0, "PILGRIM47_CRYST07", "", "", -2, 40.0);
		AddNpc(21, 20026, "", "f_pilgrimroad_47", -1847.134155, 44.5154, -1463.063599, 0.0, "", "PILGRIM47_CURSE01", "", -2, 40.0);
		AddNpc(21, 20026, "", "f_pilgrimroad_47", -1828.317749, 44.5154, -1669.839233, 0.0, "", "PILGRIM47_CURSE01", "", -2, 40.0);
		AddNpc(21, 20026, "", "f_pilgrimroad_47", -2009.570557, 44.51548, -1980.121338, 0.0, "", "PILGRIM47_CURSE01", "", -2, 40.0);
		AddNpc(21, 20026, "", "f_pilgrimroad_47", -1838.284424, 44.5154, -1850.567139, 0.0, "", "PILGRIM47_CURSE01", "", -2, 40.0);
		AddNpc(21, 20026, "", "f_pilgrimroad_47", -2336.344727, 44.515415, -1913.020874, 0.0, "", "PILGRIM47_CURSE01", "", -2, 40.0);
		AddNpc(21, 20026, "", "f_pilgrimroad_47", -1706.937256, 44.515457, -1699.455078, 0.0, "", "PILGRIM47_CURSE01", "", -2, 40.0);
		AddNpc(22, 147469, "No Shadow Npc", "f_pilgrimroad_47", 1535.789063, 44.514957, -954.676392, 0.0, "", "PILGRIM47_CURSE02", "", -2, 25.0);
		AddNpc(22, 147469, "No Shadow Npc", "f_pilgrimroad_47", 1433.952759, 44.515232, -709.195496, 0.0, "", "PILGRIM47_CURSE02", "", -2, 25.0);
		AddNpc(22, 147469, "No Shadow Npc", "f_pilgrimroad_47", 1727.271729, 44.515007, -630.302734, 0.0, "", "PILGRIM47_CURSE02", "", -2, 25.0);
		AddNpc(22, 147469, "No Shadow Npc", "f_pilgrimroad_47", 1330.19165, 44.515202, -405.483521, 0.0, "", "PILGRIM47_CURSE02", "", -2, 25.0);
		AddNpc(22, 147469, "No Shadow Npc", "f_pilgrimroad_47", 2023.123901, 44.514946, -696.090088, 0.0, "", "PILGRIM47_CURSE02", "", -2, 25.0);
		AddNpc(22, 147469, "No Shadow Npc", "f_pilgrimroad_47", 1035.728149, 44.515182, -770.83374, 0.0, "", "PILGRIM47_CURSE02", "", -2, 25.0);
		AddNpc(23, 151001, "Crystal With Magic", "f_pilgrimroad_47", -81.731743, 136.991592, -353.933868, 0.0, "", "PILGRIM47_CRY_CORE", "", -2, 20.0);
		AddNpc(23, 151001, "Crystal With Magic", "f_pilgrimroad_47", 150.663025, 136.991592, -459.11969, 0.0, "", "PILGRIM47_CRY_CORE", "", -2, 20.0);
		AddNpc(23, 151001, "Crystal With Magic", "f_pilgrimroad_47", 392.186523, 136.991592, -388.747223, 0.0, "", "PILGRIM47_CRY_CORE", "", -2, 20.0);
		AddNpc(23, 151001, "Crystal With Magic", "f_pilgrimroad_47", 142.341644, 136.991592, -142.551849, 0.0, "", "PILGRIM47_CRY_CORE", "", -2, 20.0);
		AddNpc(23, 151001, "Crystal With Magic", "f_pilgrimroad_47", 40.967354, 136.991592, 134.160828, 0.0, "", "PILGRIM47_CRY_CORE", "", -2, 20.0);
		AddNpc(23, 151001, "Crystal With Magic", "f_pilgrimroad_47", 526.134521, 136.991592, -31.353481, 0.0, "", "PILGRIM47_CRY_CORE", "", -2, 20.0);
		AddNpc(23, 151001, "Crystal With Magic", "f_pilgrimroad_47", -534.397583, 143.383102, -1107.334717, 0.0, "", "PILGRIM47_CRY_CORE", "", -2, 20.0);
		AddNpc(23, 151001, "Crystal With Magic", "f_pilgrimroad_47", -732.215088, 143.383102, -1343.163208, 0.0, "", "PILGRIM47_CRY_CORE", "", -2, 20.0);
		AddNpc(23, 151001, "Crystal With Magic", "f_pilgrimroad_47", -1085.746582, 143.383102, -1330.137695, 0.0, "", "PILGRIM47_CRY_CORE", "", -2, 20.0);
		AddNpc(23, 151001, "Crystal With Magic", "f_pilgrimroad_47", -1110.06311, 143.383102, -955.353394, 0.0, "", "PILGRIM47_CRY_CORE", "", -2, 20.0);
		AddNpc(23, 151001, "Crystal With Magic", "f_pilgrimroad_47", -913.056885, 143.383102, -1482.169434, 0.0, "", "PILGRIM47_CRY_CORE", "", -2, 20.0);
		AddNpc(23, 151001, "Crystal With Magic", "f_pilgrimroad_47", -809.667786, 143.383102, -1053.415039, 0.0, "", "PILGRIM47_CRY_CORE", "", -2, 20.0);
		AddNpc(25, 155031, "Mutated Tree Root Crystal", "f_pilgrimroad_47", 1670.981201, 137.643066, 884.874573, 126.0, "PILGRIM47_SQ_060_SUM", "", "", -2, 40.0);
		AddNpc(25, 155031, "Mutated Tree Root Crystal", "f_pilgrimroad_47", 1469.446777, 137.643082, 1050.664307, 126.0, "PILGRIM47_SQ_060_SUM", "", "", -2, 40.0);
		AddNpc(25, 155031, "Mutated Tree Root Crystal", "f_pilgrimroad_47", 1220.578125, 137.643112, 835.539978, 126.0, "PILGRIM47_SQ_060_SUM", "", "", -2, 40.0);
		AddNpc(25, 155031, "Mutated Tree Root Crystal", "f_pilgrimroad_47", 1406.348022, 137.643021, 414.606232, 126.0, "PILGRIM47_SQ_060_SUM", "", "", -2, 40.0);
		AddNpc(25, 155031, "Mutated Tree Root Crystal", "f_pilgrimroad_47", 1637.943359, 137.643005, 220.906113, 126.0, "PILGRIM47_SQ_060_SUM", "", "", -2, 40.0);
		AddNpc(25, 155031, "Mutated Tree Root Crystal", "f_pilgrimroad_47", 1829.405762, 95.771019, 31.433455, 126.0, "PILGRIM47_SQ_060_SUM", "", "", -2, 40.0);
		AddNpc(25, 155031, "Mutated Tree Root Crystal", "f_pilgrimroad_47", 1376.139648, 168.294479, 1235.78186, 126.0, "PILGRIM47_SQ_060_SUM", "", "", -2, 40.0);
		AddNpc(25, 155031, "Mutated Tree Root Crystal", "f_pilgrimroad_47", 1194.942139, 137.643143, 975.910034, 126.0, "PILGRIM47_SQ_060_SUM", "", "", -2, 40.0);
		AddNpc(25, 155031, "Mutated Tree Root Crystal", "f_pilgrimroad_47", 1924.449219, 137.64299, 495.583527, 126.0, "PILGRIM47_SQ_060_SUM", "", "", -2, 40.0);
		AddNpc(26, 147392, "Treasure Box 1", "f_pilgrimroad_47", -1489.341797, 154.589203, 1074.924805, -4.0, "PILGRIM47_SQ_080_BOX", "", "", -2, 100.0);
		AddNpc(27, 147312, "Dropped Paper", "f_pilgrimroad_47", 875.900818, 67.85833, -371.413239, 0.0, "PILGRIM47_DMSG02", "", "", -2, 40.0);
		AddNpc(28, 147312, "Dropped Paper", "f_pilgrimroad_47", -910.302551, 154.589188, 918.705017, 0.0, "PILGRIM47_DMSG03", "", "", -2, 40.0);
		AddNpc(29, 147312, "Dropped Paper", "f_pilgrimroad_47", 1516.238525, 137.642975, 655.031311, 0.0, "PILGRIM47_DMSG04", "", "", -2, 40.0);
		AddNpc(30, 155031, "Mutated Tree Root Crystal", "f_pilgrimroad_47", 1342.40918, 44.515194, -181.141327, 126.0, "PILGRIM47_CRYST08", "PILGRIM47_CRYST08", "", -2, 40.0);
		AddNpc(31, 153057, "Fluttering Paper", "f_pilgrimroad_47", 1370.745239, 44.515182, -161.382553, 0.0, "PILGRIM47_DMSG05", "", "", -2, 40.0);
		AddNpc(32, 153057, "Fluttering Paper", "f_pilgrimroad_47", -1692.048706, 195.316971, 119.216667, 0.0, "PILGRIM47_DMSG06", "", "", -2, 40.0);
		AddNpc(40, 147392, "Treasure Box 1", "f_pilgrimroad_47", 221.460007, 137.089996, 219.429993, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
	}
}
