// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_pilgrimroad_50 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(4, 20026, "", "f_pilgrimroad_50", 891.0, 507.0, -746.0, 0.0, "", "REQ_SEMPLE_03_01", "", -2, 100.0);
		AddNpc(5, 20026, "", "f_pilgrimroad_50", -681.0, 557.0, 740.0, 0.0, "", "REQ_SEMPLE_03_02", "", -2, 100.0);
		AddNpc(6, 20026, "", "f_pilgrimroad_50", -1667.0, 507.0, -361.0, 0.0, "", "REQ_SEMPLE_03_03", "", -2, 100.0);
		AddNpc(10, 155036, "Pilgrim (M) 1 - Existing Hair 1", "f_pilgrimroad_50", -87.669998, 507.359985, -457.269989, 0.0, "PILGRIM50_NPC01", "", "", -2, 40.0);
		AddNpc(11, 152006, "Half-Destroyed Altar", "f_pilgrimroad_50", -1935.657593, 507.3573, 350.641815, -86.0, "PILGRIM50_ALTAR01", "", "", -2, 40.0);
		AddNpc(12, 152006, "Half-Destroyed Altar", "f_pilgrimroad_50", 1917.300049, 507.359985, -805.450012, -95.0, "PILGRIM50_ALTAR02", "", "", -2, 40.0);
		AddNpc(14, 147469, "No Shadow Npc", "f_pilgrimroad_50", -412.769989, 580.880005, 1035.430054, 0.0, "PILGRIM50_ANGRY01", "", "", -2, 40.0);
		AddNpc(15, 147469, "No Shadow Npc", "f_pilgrimroad_50", 461.570007, 640.690002, 1695.430054, -53.0, "PILGRIM50_ANGRY02", "", "", -2, 40.0);
		AddNpc(16, 147469, "No Shadow Npc", "f_pilgrimroad_50", 1038.659058, 680.330566, 55.030262, 112.0, "PILGRIM50_ANGRY03", "", "", -2, 30.0);
		AddNpc(17, 147412, "Large Spiny Flower", "f_pilgrimroad_50", -998.77002, 557.880005, 860.710022, 1.0, "PILGRIM50_FLOWER", "", "", -2, 40.0);
		AddNpc(17, 147412, "Large Spiny Flower", "f_pilgrimroad_50", -988.780029, 557.880005, 552.98999, 1.0, "PILGRIM50_FLOWER", "", "", -2, 40.0);
		AddNpc(17, 147412, "Large Spiny Flower", "f_pilgrimroad_50", -363.01001, 557.880005, 674.590027, 1.0, "PILGRIM50_FLOWER", "", "", -2, 40.0);
		AddNpc(17, 147412, "Large Spiny Flower", "f_pilgrimroad_50", 527.429993, 609.690002, 1363.72998, 1.0, "PILGRIM50_FLOWER", "", "", -2, 40.0);
		AddNpc(17, 147412, "Large Spiny Flower", "f_pilgrimroad_50", 475.160004, 609.690002, 1078.380005, 1.0, "PILGRIM50_FLOWER", "", "", -2, 40.0);
		AddNpc(17, 147412, "Large Spiny Flower", "f_pilgrimroad_50", -28.709999, 609.690002, 1570.619995, 1.0, "PILGRIM50_FLOWER", "", "", -2, 40.0);
		AddNpc(18, 147412, "Large Spiny Flower", "f_pilgrimroad_50", -833.849976, 557.880005, 1122.060059, 1.0, "PILGRIM50_FLOWER", "", "", -2, 40.0);
		AddNpc(18, 147412, "Large Spiny Flower", "f_pilgrimroad_50", -370.0, 557.880005, 444.619995, 1.0, "PILGRIM50_FLOWER", "", "", -2, 40.0);
		AddNpc(18, 147412, "Large Spiny Flower", "f_pilgrimroad_50", 161.880005, 609.690002, 858.22998, 1.0, "PILGRIM50_FLOWER", "", "", -2, 40.0);
		AddNpc(19, 147469, "No Shadow Npc", "f_pilgrimroad_50", -102.25, 524.0, -496.01001, 0.0, "PILGRIM50_ALTAR", "", "", -2, 40.0);
		AddNpc(21, 155034, "Pilgrim (M) 1 - New Hair 1", "f_pilgrimroad_50", 465.0, 635.690002, 1693.0, -36.0, "PILGRIM50_GHOST2", "", "", -2, 40.0);
		AddNpc(22, 147312, "Dropped Paper", "f_pilgrimroad_50", 1077.776733, 657.345337, 78.387497, 0.0, "", "PILGRIM50_BIBLE", "", -2, 20.0);
		AddNpc(24, 155038, "Pilgrim (M) 1 - Existing Hair 3", "f_pilgrimroad_50", -1923.521729, 507.3573, 323.575226, -45.0, "PILGRIM50_GHOST4", "", "", -2, 40.0);
		AddNpc(27, 152017, "Big Bouquet1", "f_pilgrimroad_50", -429.413727, 557.883423, 1029.636963, 45.0, "", "PILGRIM50_BUNT_1", "", -2, 40.0);
		AddNpc(28, 152017, "Big Bouquet1", "f_pilgrimroad_50", -395.483368, 557.883423, 1020.972229, 0.0, "", "PILGRIM50_BUNT_2", "", -2, 40.0);
		AddNpc(29, 152018, "Big Bouquet2", "f_pilgrimroad_50", -405.174011, 557.883423, 990.127197, 0.0, "", "PILGRIM50_BUNT_3", "", -2, 40.0);
		AddNpc(30, 152018, "Big Bouquet2", "f_pilgrimroad_50", -354.078003, 557.972351, 996.836426, 55.0, "", "PILGRIM50_BUNT_4", "", -2, 40.0);
		AddNpc(31, 152018, "Big Bouquet2", "f_pilgrimroad_50", -413.213867, 557.883423, 1026.172241, 0.0, "", "PILGRIM50_BUNT_5", "", -2, 40.0);
		AddNpc(32, 152006, "Half-Destroyed Altar", "f_pilgrimroad_50", 927.811584, 507.3573, -943.499695, -71.0, "PILGRIM50_ALTAR03", "", "", -2, 40.0);
		AddNpc(33, 153014, "Book", "f_pilgrimroad_50", -1612.0, 507.0, -872.0, 0.0, "PILGRIM50_DIARY", "", "", -2, 40.0);
		AddNpc(34, 147312, "Dropped Paper", "f_pilgrimroad_50", 959.421021, 507.3573, -890.085815, 0.0, "PILGRIM50_LOSTPAPER", "", "", -2, 40.0);
		AddNpc(41, 147392, "Treasure Box 1", "f_pilgrimroad_50", -969.97998, 557.97998, 1142.72998, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(42, 20026, "", "f_pilgrimroad_50", 588.186951, 657.326782, 77.753563, 0.0, "", "JOB_PIED_PIPER_Q1_OBJ", "", -2, 150.0);
	}
}
