// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_pilgrimroad_55 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(12, 20156, "Gentleman 10", "f_pilgrimroad_55", 1374.248169, 242.419998, -773.202087, 53.0, "", "", "", -2, 100.0);
		AddNpc(16, 147386, "Saule Goddess 2", "f_pilgrimroad_55", -696.963745, 331.856415, 593.109436, -94.0, "", "", "", -2, 100.0);
		AddNpc(17, 47252, "Royal Mausoleum Tombstone02", "f_pilgrimroad_55", -320.462952, 242.418793, -615.255798, -40.0, "", "", "", -2, 100.0);
		AddNpc(24, 147398, "Saule God2", "f_pilgrimroad_55", -470.790314, 242.418793, -322.623413, 9.0, "", "", "", -2, 100.0);
	}
}
