// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_remains_40 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(103, 20118, "Tobias", "f_remains_40", -502.0, 304.0, -2059.0, 0.0, "REMAINS_40_DRUNK_01", "", "", -2, 30.0);
		AddNpc(104, 20118, "Tobias", "f_remains_40", 1791.0, 515.0, 1195.0, 0.0, "REMAINS_40_DRUNK_02", "", "", -2, 30.0);
		AddNpc(105, 20118, "Tobias", "f_remains_40", 3016.0, 645.0, 2916.0, 0.0, "REMAINS_40_DRUNK_03", "", "", -2, 30.0);
		AddNpc(106, 20156, "Gentleman 10", "f_remains_40", -645.0, 304.0, -1898.0, 6.0, "REMAINS_40_CANOLIN_01", "", "", -2, 30.0);
		AddNpc(107, 147473, "Mira", "f_remains_40", -242.0, 311.0, -1931.0, -82.0, "REMAINS_40_TARA_01", "", "", -2, 30.0);
		AddNpc(108, 147473, "Mira", "f_remains_40", 1723.0, 515.0, 1564.0, -78.0, "REMAINS_40_TARA_02", "", "", -2, 30.0);
		AddNpc(200, 47191, "Literature 2", "f_remains_40", -121.0, 642.0, -17.0, -47.0, "REMAINS_40_MQ_02", "", "", -2, 0.0);
		AddNpc(201, 47191, "Literature 2", "f_remains_40", 867.0, 596.0, -273.0, 2.0, "REMAINS_40_MQ_03", "", "", -2, 0.0);
		AddNpc(202, 47191, "Literature 2", "f_remains_40", 884.0, 459.0, 784.0, -13.13, "REMAINS_40_MQ_04", "", "", -2, 0.0);
		AddNpc(203, 47191, "Literature 2", "f_remains_40", 2168.0, 515.0, 1372.0, 86.0, "REMAINS_40_MQ_05", "", "", -2, 0.0);
		AddNpc(204, 47191, "Literature 2", "f_remains_40", 2419.0, 640.0, 3792.0, -43.0, "REMAINS_40_MQ_06", "", "", -2, 0.0);
		AddNpc(205, 47191, "Literature 2", "f_remains_40", 3660.0, 645.0, 2624.0, 12.0, "REMAINS_40_MQ_07", "", "", -2, 0.0);
		AddNpc(207, 46212, "Box", "f_remains_40", -1716.0, 340.0, -800.0, 89.0, "REMAINS_40_MQ_01", "", "", -2, 10.0);
		AddNpc(207, 46212, "Box", "f_remains_40", -1723.0, 340.0, -590.0, 89.0, "REMAINS_40_MQ_01", "", "", -2, 10.0);
		AddNpc(207, 46212, "Box", "f_remains_40", -1719.0, 340.0, -482.0, 89.0, "REMAINS_40_MQ_01", "", "", -2, 10.0);
		AddNpc(207, 46212, "Box", "f_remains_40", -1414.0, 340.0, -517.0, 89.0, "REMAINS_40_MQ_01", "", "", -2, 10.0);
		AddNpc(207, 46212, "Box", "f_remains_40", -1415.0, 303.0, -1087.0, 89.0, "REMAINS_40_MQ_01", "", "", -2, 10.0);
		AddNpc(207, 46212, "Box", "f_remains_40", -1288.0, 303.0, -924.0, 89.0, "REMAINS_40_MQ_01", "", "", -2, 10.0);
		AddNpc(207, 46212, "Box", "f_remains_40", -1495.0, 340.0, -577.0, 89.0, "REMAINS_40_MQ_01", "", "", -2, 10.0);
		AddNpc(207, 46212, "Box", "f_remains_40", -1042.0, 340.0, -768.0, 89.0, "REMAINS_40_MQ_01", "", "", -2, 10.0);
		AddNpc(207, 46212, "Box", "f_remains_40", -2036.0, 368.0, -55.0, 89.0, "REMAINS_40_MQ_01", "", "", -2, 10.0);
		AddNpc(207, 46212, "Box", "f_remains_40", -1847.0, 368.0, -164.0, 89.0, "REMAINS_40_MQ_01", "", "", -2, 10.0);
		AddNpc(208, 20026, "", "f_remains_40", -1744.0, 315.0, -3502.0, 0.0, "", "REMAINS40_SQ_02", "", -2, 250.0);
		AddNpc(400, 147449, "Grita", "f_remains_40", 3510.0, 645.0, 2864.0, -69.68, "REMAINS40_GRITA", "", "", -2, 0.0);
		AddNpc(405, 20026, "", "f_remains_40", -1704.869995, 315.339996, -3474.179932, 0.0, "", "JOB_PELTASTA4_3", "", -2, 250.0);
		AddNpc(406, 20026, "", "f_remains_40", 1051.109985, 459.459991, 594.890015, 0.0, "", "JOB_PARDONER4_2_TRIGGER", "", -2, 200.0);
		AddNpc(407, 20026, "", "f_remains_40", 2531.290039, 640.27002, 3537.320068, 0.0, "", "JOB_JOB_SORCERER4_1_TRIGGER", "", -2, 250.0);
		AddNpc(408, 40030, "Treasure Chest", "f_remains_40", -466.0, 557.0, 139.0, 0.0, "REMAINS_40_HQ_01_TB", "", "", -2, 30.0);
		AddNpc(412, 40080, "Warning", "f_remains_40", -2412.679932, 315.339996, -1452.839966, 16.0, "REMAINS40_BOARD01", "", "", -2, 40.0);
		AddNpc(417, 40095, "", "f_remains_40", 1419.225342, 643.302673, 3288.158447, 0.0, "HIDDEN_TRESURE01", "", "", -2, 40.0);
		AddNpc(418, 40095, "", "f_remains_40", 2201.091064, 515.572021, 1223.319092, 0.0, "HIDDEN_TRESURE02", "", "", -2, 40.0);
		AddNpc(419, 40095, "", "f_remains_40", -286.168304, 642.735474, -38.632946, 0.0, "HIDDEN_TRESURE03", "", "", -2, 40.0);
		AddNpc(420, 40095, "", "f_remains_40", -2108.472656, 315.337494, -3445.791748, 0.0, "HIDDEN_TRESURE04", "", "", -2, 40.0);
		AddNpc(421, 40034, "Treasure Chest", "f_remains_40", 1420.62793, 643.302673, 3287.51416, 0.0, "TRESURE01_BOX", "", "", -2, 40.0);
		AddNpc(422, 40034, "Treasure Chest", "f_remains_40", 2203.431641, 515.572021, 1219.97644, 0.0, "TRESURE01_BOX", "", "", -2, 40.0);
		AddNpc(423, 40034, "Treasure Chest", "f_remains_40", -282.455292, 642.735474, -47.10638, 0.0, "TRESURE01_BOX", "", "", -2, 40.0);
		AddNpc(424, 40034, "Treasure Chest", "f_remains_40", -2105.209717, 315.337494, -3446.358887, 0.0, "TRESURE01_BOX", "", "", -2, 40.0);
		AddNpc(425, 47192, "Literature 3", "f_remains_40", 1572.494995, 460.883331, 890.381287, -24.0, "REMAINS40_HIDDEN_EVENT", "", "", -2, 40.0);
		AddNpc(427, 147392, "Treasure Box 1", "f_remains_40", -1601.48999, 315.440002, -3954.919922, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(429, 155043, "Monk2", "f_remains_40", -601.038452, 304.527893, -1757.153564, -83.0, "CATACOMB_25_4_LAIMIS", "", "", -2, 40.0);
		AddNpc(430, 152057, "No Shadow Npc Tall", "f_remains_40", -1181.339966, 304.019989, -1134.369995, 0.0, "HTA_REMAINS_40_WATERPOT", "", "", -2, 5.0);
		AddNpc(431, 152057, "No Shadow Npc Tall", "f_remains_40", -2129.304688, 315.339996, -3577.366699, 0.0, "HTA_REMAINS_40_SMOKE", "", "", -2, 5.0);
		AddNpc(445, 40095, "", "f_remains_40", -1913.317993, 315.477692, -2708.283936, 0.0, "", "MASTER_PELTASTA2_3_TRACK", "", -2, 150.0);
		AddNpc(446, 153159, "Magic Power Hack", "f_remains_40", -1979.486206, 368.920471, 69.632713, 0.0, "EXORCIST_MASTER_STEP33_NPC1", "EXORCIST_MASTER_STEP33_NPC1_IN", "", -2, 100.0);
		AddNpc(447, 20025, "", "f_remains_40", -1964.656616, 368.920471, 63.33947, 0.0, "EXORCIST_MASTER_STEP33_NPC2", "", "", -2, 40.0);
	}
}
