// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_remains_38 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(9, 47190, "Literature 1", "f_remains_38", -756.440002, 260.420013, -967.869995, 120.0, "REMAIN38_MQ_MONUMENT1", "", "", -2, 30.0);
		AddNpc(11, 47190, "Literature 1", "f_remains_38", -715.380005, 422.890015, -438.790009, 6.0, "REMAIN38_MQ_MONUMENT2", "", "", -2, 30.0);
		AddNpc(13, 47190, "Literature 1", "f_remains_38", 211.759995, 244.119995, -1346.689941, 22.0, "REMAIN38_MQ_MONUMENT3", "", "", -2, 30.0);
		AddNpc(16, 47190, "Literature 1", "f_remains_38", 1296.550049, 329.059998, -674.72998, -2.0, "REMAIN38_MQ_MONUMENT4", "", "", -2, 30.0);
		AddNpc(20, 47190, "Literature 1", "f_remains_38", 1429.0, 371.0, 908.0, -7.0, "REMAIN38_MQ_MONUMENT5", "", "", -2, 50.0);
		AddNpc(21, 147436, "Fletcher Master", "f_remains_38", 234.390091, 277.946198, -530.264526, 0.0, "MASTER_FLETCHER", "", "", -2, 40.0);
		AddNpc(22, 57225, "Monk Master", "f_remains_38", 263.396423, 277.946198, -307.814087, -90.0, "JOB_MONK4_1", "", "", -2, 40.0);
		AddNpc(58, 47160, "Lost Stuff Of Vendor 1", "f_remains_38", -1346.752319, 325.94101, -1724.12854, 0.0, "REMAIN38_SQ01", "", "", -2, 30.0);
		AddNpc(61, 154022, "Alchemist Saliamonas", "f_remains_38", -1053.0, 260.0, -1249.0, 18.0, "REMAIN38_SQ_DRASIUS", "", "", -2, 30.0);
		AddNpc(73, 20026, "", "f_remains_38", 161.559998, 479.0, 1048.969971, 0.0, "", "JOB_CHROSOC5_1_TRIGGER", "", -2, 300.0);
		AddNpc(78, 47245, "Hunter", "f_remains_38", 562.669983, 277.950012, -302.920013, -77.0, "REMAIN38_HUNTER", "", "", -2, 1.0);
		AddNpc(79, 47258, "Jar", "f_remains_38", -78.0, 423.0, 424.0, -72.0, "REMAIN38_SQ06", "", "", -2, 1.0);
		AddNpc(81, 47202, "Discolored Grass Of Siauliai", "f_remains_38", 346.839996, 210.369995, -876.25, 0.0, "REMAIN38_SQ02", "", "", -2, 0.0);
		AddNpc(81, 47202, "Discolored Grass Of Siauliai", "f_remains_38", 244.419998, 210.369995, -814.280029, 0.0, "REMAIN38_SQ02", "", "", -2, 0.0);
		AddNpc(81, 47202, "Discolored Grass Of Siauliai", "f_remains_38", 130.740005, 210.369995, -761.530029, 0.0, "REMAIN38_SQ02", "", "", -2, 0.0);
		AddNpc(81, 47202, "Discolored Grass Of Siauliai", "f_remains_38", -103.040001, 210.369995, -740.690002, 0.0, "REMAIN38_SQ02", "", "", -2, 0.0);
		AddNpc(81, 47202, "Discolored Grass Of Siauliai", "f_remains_38", 76.599998, 210.369995, -665.219971, 0.0, "REMAIN38_SQ02", "", "", -2, 0.0);
		AddNpc(81, 47202, "Discolored Grass Of Siauliai", "f_remains_38", 0.19, 210.369995, -714.52002, 0.0, "REMAIN38_SQ02", "", "", -2, 0.0);
		AddNpc(81, 47202, "Discolored Grass Of Siauliai", "f_remains_38", 467.309998, 210.369995, -845.809998, 0.0, "REMAIN38_SQ02", "", "", -2, 0.0);
		AddNpc(81, 47202, "Discolored Grass Of Siauliai", "f_remains_38", 453.230011, 210.369995, -979.97998, 0.0, "REMAIN38_SQ02", "", "", -2, 0.0);
		AddNpc(81, 47202, "Discolored Grass Of Siauliai", "f_remains_38", 471.440002, 210.369995, -1071.52002, 0.0, "REMAIN38_SQ02", "", "", -2, 0.0);
		AddNpc(81, 47202, "Discolored Grass Of Siauliai", "f_remains_38", 563.789978, 210.369995, -804.539978, 0.0, "REMAIN38_SQ02", "", "", -2, 0.0);
		AddNpc(81, 47202, "Discolored Grass Of Siauliai", "f_remains_38", 600.880005, 210.369995, -702.690002, 0.0, "REMAIN38_SQ02", "", "", -2, 0.0);
		AddNpc(81, 47202, "Discolored Grass Of Siauliai", "f_remains_38", 702.049988, 210.369995, -586.630005, 0.0, "REMAIN38_SQ02", "", "", -2, 0.0);
		AddNpc(81, 47202, "Discolored Grass Of Siauliai", "f_remains_38", 751.340027, 210.369995, -451.76001, 0.0, "REMAIN38_SQ02", "", "", -2, 0.0);
		AddNpc(81, 47202, "Discolored Grass Of Siauliai", "f_remains_38", 677.830017, 210.369995, -486.51001, 0.0, "REMAIN38_SQ02", "", "", -2, 0.0);
		AddNpc(86, 147393, "Treasure Box 3", "f_remains_38", 973.320007, 244.220001, -1043.329956, -90.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(87, 20026, "", "f_remains_38", 1261.508789, 313.065613, -947.629761, 0.0, "", "REMAINS_38_JOB_SPARRING_TRIGGER", "", -2, 250.0);
		AddNpc(88, 147392, "Treasure Box 1", "f_remains_38", 1725.469971, 370.309998, 1206.890015, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(90, 151106, "Rune Caster Master", "f_remains_38", 681.306396, 244.120605, -1351.379028, 0.0, "RUNECASTER_MASTER", "", "", -2, 40.0);
		AddNpc(91, 153149, "Stone", "f_remains_38", -100.230682, 478.997009, 1241.677612, 0.0, "REMAINS38_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(91, 153149, "Stone", "f_remains_38", -219.757233, 478.997009, 1229.370117, 0.0, "REMAINS38_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(91, 153149, "Stone", "f_remains_38", -40.765591, 478.997009, 1000.205017, 0.0, "REMAINS38_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(91, 153149, "Stone", "f_remains_38", 215.023788, 478.997009, 1215.322144, 0.0, "REMAINS38_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(91, 153149, "Stone", "f_remains_38", 346.817902, 478.997009, 1155.583618, 0.0, "REMAINS38_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(91, 153149, "Stone", "f_remains_38", 437.504669, 478.99704, 1035.808472, 0.0, "REMAINS38_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(91, 153149, "Stone", "f_remains_38", 359.538666, 478.997009, 1002.570679, 0.0, "REMAINS38_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(91, 153149, "Stone", "f_remains_38", 288.461273, 478.997009, 901.739746, 0.0, "REMAINS38_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(91, 153149, "Stone", "f_remains_38", 298.926941, 478.997009, 836.440002, 0.0, "REMAINS38_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(91, 153149, "Stone", "f_remains_38", 67.060684, 478.997009, 861.65863, 0.0, "REMAINS38_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(91, 153149, "Stone", "f_remains_38", 186.38063, 471.365417, 764.642334, 0.0, "REMAINS38_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(91, 153149, "Stone", "f_remains_38", 230.429291, 422.887512, 571.067017, 0.0, "REMAINS38_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(91, 153149, "Stone", "f_remains_38", 66.437637, 422.887512, 473.271271, 0.0, "REMAINS38_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(91, 153149, "Stone", "f_remains_38", 271.141479, 422.887512, 435.602661, 0.0, "REMAINS38_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(91, 153149, "Stone", "f_remains_38", 351.696686, 422.887512, 251.860855, 0.0, "REMAINS38_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(91, 153149, "Stone", "f_remains_38", 298.327942, 422.887512, 337.943726, 0.0, "REMAINS38_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(91, 153149, "Stone", "f_remains_38", 192.361267, 422.887512, 33.845123, 0.0, "REMAINS38_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(91, 153149, "Stone", "f_remains_38", 106.466766, 422.887512, 53.113632, 0.0, "REMAINS38_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(91, 153149, "Stone", "f_remains_38", 248.012787, 422.887512, 71.675568, 0.0, "REMAINS38_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(91, 153149, "Stone", "f_remains_38", 126.936249, 422.887512, 559.489258, 0.0, "REMAINS38_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(91, 153149, "Stone", "f_remains_38", -116.869873, 422.887512, 222.297516, 0.0, "REMAINS38_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(91, 153149, "Stone", "f_remains_38", -142.443192, 422.887512, 310.900818, 0.0, "REMAINS38_RP_1_OBJ", "", "", -2, 40.0);
		AddNpc(93, 40095, "", "f_remains_38", -216.160309, 210.370102, -691.27478, 0.0, "HIDDEN_WATER_REMAINS", "HIDDEN_WATER_REMAINS_IN", "", -2, 90.0);
		AddNpc(94, 154025, "Petrification Detector", "f_remains_38", 897.382996, 244.120605, -1188.845581, 0.0, "JOB_PLAGUEDOCTOR71_NPC3", "", "", -2, 40.0);
	}
}
