// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_remains_39 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(8, 47191, "Literature 2", "f_remains_39", -623.0, 194.0, -377.0, -10.0, "REMAINS39_MQ_MONUMENT1", "", "", -2, 0.0);
		AddNpc(9, 47191, "Literature 2", "f_remains_39", -611.0, 194.0, 214.0, -10.0, "REMAINS39_MQ_MONUMENT2", "", "", -2, 0.0);
		AddNpc(10, 47191, "Literature 2", "f_remains_39", 156.240005, 193.080002, 172.229996, -59.0, "REMAINS39_MQ_MONUMENT3", "", "", -2, 0.0);
		AddNpc(11, 47191, "Literature 2", "f_remains_39", 930.0, 174.0, -98.0, -10.0, "REMAINS39_MQ_MONUMENT4", "", "", -2, 0.0);
		AddNpc(12, 47191, "Literature 2", "f_remains_39", 881.0, 174.0, 467.0, -10.0, "REMAINS39_MQ_MONUMENT5", "", "", -2, 0.0);
		AddNpc(13, 47191, "Literature 2", "f_remains_39", 1001.0, 175.0, 1294.0, -10.0, "REMAINS39_MQ_MONUMENT6", "", "", -2, 0.0);
		AddNpc(14, 47161, "Lost Stuff Of Vendor 2", "f_remains_39", -765.504028, 194.768997, 413.126434, -30.0, "REMAINS39_GHOST_BAG_1", "", "", -2, 0.0);
		AddNpc(15, 20138, "Cedric", "f_remains_39", 175.229996, 193.080002, 59.549999, 69.0, "REMAINS39_PEAPLE", "", "", -2, 0.0);
		AddNpc(26, 154017, "Ghost Soldier", "f_remains_39", -644.49176, 194.768997, 479.10025, 0.0, "REMAINS39_GHOST", "", "", -2, 80.0);
		AddNpc(31, 20118, "Tobias", "f_remains_39", 363.0, 195.0, 144.0, 0.0, "REMAIN39_SQ_MOJE", "", "", -2, 30.0);
		AddNpc(37, 20154, "Gentleman 8", "f_remains_39", 211.0, 193.0, 425.0, 0.0, "REMAIN39_SQ_MAN", "", "", -2, 30.0);
		AddNpc(38, 20025, "", "f_remains_39", 428.0, 192.0, 209.0, 0.0, "REMAIN39_SQ_WOOD", "", "", -2, 30.0);
		AddNpc(43, 20026, "", "f_remains_39", 1046.25, 174.259995, 1282.890015, 0.0, "", "JOB_WARLOCK4_1_TRIGGER", "", -2, 300.0);
		AddNpc(52, 47160, "Lost Stuff Of Vendor 1", "f_remains_39", -1385.0, 195.0, -194.0, 0.0, "REMAINS39_GHOST_BAG_2", "", "", -2, 40.0);
		AddNpc(55, 147392, "Treasure Box 1", "f_remains_39", 479.869995, 193.179993, 656.23999, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(56, 20158, "Gentleman 12", "f_remains_39", -1265.142822, 232.126694, 507.496643, -83.0, "REMAINS39_RP_1_NPC", "", "", -2, 40.0);
		AddNpc(58, 20152, "Gentleman 6", "f_remains_39", 429.982605, 193.0811, 421.219727, -93.0, "REMAINS39_CHAR119_MSTEP2_1", "", "", -2, 40.0);
		AddNpc(59, 20151, "Gentleman 5", "f_remains_39", 41.704815, 193.081085, 341.038147, 0.0, "REMAINS39_CHAR119_MSTEP2_2", "", "", -2, 40.0);
		AddNpc(60, 20156, "Gentleman 10", "f_remains_39", 82.47789, 193.083572, 163.924728, 0.0, "REMAINS39_CHAR119_MSTEP2_3", "", "", -2, 40.0);
	}
}
