// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_remains_37 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(1, 40095, "", "f_remains_37", 1807.0, 1094.0, 906.0, 0.0, "REMAINS37_STONE1", "", "", -2, 30.0);
		AddNpc(17, 47192, "Literature 3", "f_remains_37", 433.0, 1427.0, 2880.0, 95.0, "REMAIN37_SQ07", "", "", -2, 1.0);
		AddNpc(25, 20157, "Gentleman 11", "f_remains_37", 439.380005, 1008.659973, -1642.780029, 27.0, "REMAIN37_RAYMOND", "", "", -2, 1.0);
		AddNpc(33, 20117, "Armand", "f_remains_37", 410.149994, 1123.97998, 35.080002, 73.0, "REMAIN37_SQ6_UNCLE1", "", "", -2, 1.0);
		AddNpc(40, 20025, "", "f_remains_37", 1701.0, 1094.0, 1.0, 0.0, "", "REMAIN37_BLOCK", "", -2, 40.0);
		AddNpc(42, 20158, "Gentleman 12", "f_remains_37", 317.609985, 1426.839966, 2902.300049, 20.0, "REMAIN37_SMEADE", "", "", -2, 1.0);
		AddNpc(50, 147448, "Chronomancer Master", "f_remains_37", 438.709991, 1017.929993, -1775.920044, -16.0, "MASTER_CHRONO", "", "", -2, 1.0);
		AddNpc(51, 151049, "Falconer Master", "f_remains_37", 593.386047, 1009.879883, -1594.42395, -90.0, "MASTER_FALCONER", "", "", -2, 1.0);
		AddNpc(55, 147465, "Firewood", "f_remains_37", 542.150024, 1021.369995, -1094.890015, -27.0, "REMAIN37_MQ05", "", "", -2, 1.0);
		AddNpc(55, 147465, "Firewood", "f_remains_37", 629.130005, 1021.369995, -1095.959961, -69.0, "REMAIN37_MQ05", "", "", -2, 1.0);
		AddNpc(55, 147465, "Firewood", "f_remains_37", 535.340027, 1021.369995, -1171.959961, -60.0, "REMAIN37_MQ05", "", "", -2, 1.0);
		AddNpc(55, 147465, "Firewood", "f_remains_37", 635.789978, 1021.369995, -1180.199951, -45.0, "REMAIN37_MQ05", "", "", -2, 1.0);
		AddNpc(56, 147463, "Stone Slabs", "f_remains_37", 1203.0, 1057.0, -2149.0, 39.0, "REMAIN37_MQ03", "", "", -2, 40.0);
		AddNpc(57, 147464, "Stone Slabs", "f_remains_37", 837.23999, 1035.660034, -1128.050049, -48.0, "REMAIN37_MQ04", "", "", -2, 1.0);
		AddNpc(57, 147464, "Stone Slabs", "f_remains_37", 848.780029, 1035.660034, -967.549988, -99.0, "REMAIN37_MQ04", "", "", -2, 1.0);
		AddNpc(57, 147464, "Stone Slabs", "f_remains_37", 770.929993, 1035.660034, -862.429993, 33.0, "REMAIN37_MQ04", "", "", -2, 1.0);
		AddNpc(57, 147464, "Stone Slabs", "f_remains_37", 529.190002, 1035.660034, -897.580017, 78.0, "REMAIN37_MQ04", "", "", -2, 1.0);
		AddNpc(57, 147464, "Stone Slabs", "f_remains_37", 643.159973, 1035.660034, -897.469971, 84.0, "REMAIN37_MQ04", "", "", -2, 1.0);
		AddNpc(57, 147464, "Stone Slabs", "f_remains_37", 419.630005, 1035.670044, -921.169983, 64.0, "REMAIN37_MQ04", "", "", -2, 1.0);
		AddNpc(57, 147464, "Stone Slabs", "f_remains_37", 398.480011, 1035.670044, -1080.630005, 15.0, "REMAIN37_MQ04", "", "", -2, 1.0);
		AddNpc(57, 147464, "Stone Slabs", "f_remains_37", 380.649994, 1035.670044, -1213.0, -14.0, "REMAIN37_MQ04", "", "", -2, 1.0);
		AddNpc(57, 147464, "Stone Slabs", "f_remains_37", 390.799988, 1035.670044, -1357.619995, 25.0, "REMAIN37_MQ04", "", "", -2, 1.0);
		AddNpc(57, 147464, "Stone Slabs", "f_remains_37", 480.170013, 1035.670044, -1390.369995, 17.0, "REMAIN37_MQ04", "", "", -2, 1.0);
		AddNpc(57, 147464, "Stone Slabs", "f_remains_37", 533.98999, 1035.660034, -1316.76001, -8.0, "REMAIN37_MQ04", "", "", -2, 1.0);
		AddNpc(57, 147464, "Stone Slabs", "f_remains_37", 671.580017, 1035.660034, -1335.400024, 0.0, "REMAIN37_MQ04", "", "", -2, 1.0);
		AddNpc(57, 147464, "Stone Slabs", "f_remains_37", 780.340027, 1035.660034, -1290.27002, 0.0, "REMAIN37_MQ04", "", "", -2, 1.0);
		AddNpc(57, 147464, "Stone Slabs", "f_remains_37", 755.52002, 1035.660034, -1197.369995, 62.0, "REMAIN37_MQ04", "", "", -2, 1.0);
		AddNpc(57, 147464, "Stone Slabs", "f_remains_37", 755.140015, 1035.660034, -1066.969971, 114.0, "REMAIN37_MQ04", "", "", -2, 1.0);
		AddNpc(57, 147464, "Stone Slabs", "f_remains_37", 793.440002, 1035.660034, -961.869995, 51.0, "REMAIN37_MQ04", "", "", -2, 1.0);
		AddNpc(57, 147464, "Stone Slabs", "f_remains_37", 840.929993, 1035.660034, -1204.26001, 20.0, "REMAIN37_MQ04", "", "", -2, 1.0);
		AddNpc(57, 147464, "Stone Slabs", "f_remains_37", 416.450012, 1035.670044, -988.599976, 149.0, "REMAIN37_MQ04", "", "", -2, 1.0);
		AddNpc(57, 147464, "Stone Slabs", "f_remains_37", 639.140015, 1035.660034, -958.890015, 41.0, "REMAIN37_MQ04", "", "", -2, 1.0);
		AddNpc(57, 147464, "Stone Slabs", "f_remains_37", 701.960022, 1035.660034, -812.869995, -1.0, "REMAIN37_MQ04", "", "", -2, 1.0);
		AddNpc(58, 147380, "Empty Npc 2 Times", "f_remains_37", 1593.589966, 1094.280029, 698.97998, 0.0, "REMAIN37_SQ04", "", "", -2, 1.0);
		AddNpc(58, 147380, "Empty Npc 2 Times", "f_remains_37", 1340.699951, 1094.280029, 740.880005, 0.0, "REMAIN37_SQ04", "", "", -2, 1.0);
		AddNpc(58, 147380, "Empty Npc 2 Times", "f_remains_37", 1292.680054, 1094.280029, 450.48999, 0.0, "REMAIN37_SQ04", "", "", -2, 1.0);
		AddNpc(58, 147380, "Empty Npc 2 Times", "f_remains_37", 1356.48999, 1094.280029, 216.539993, 0.0, "REMAIN37_SQ04", "", "", -2, 1.0);
		AddNpc(58, 147380, "Empty Npc 2 Times", "f_remains_37", 1479.449951, 1094.280029, 199.169998, 0.0, "REMAIN37_SQ04", "", "", -2, 1.0);
		AddNpc(58, 147380, "Empty Npc 2 Times", "f_remains_37", 1570.75, 1094.280029, 276.700012, 0.0, "REMAIN37_SQ04", "", "", -2, 1.0);
		AddNpc(58, 147380, "Empty Npc 2 Times", "f_remains_37", 1598.75, 1094.280029, 458.649994, 0.0, "REMAIN37_SQ04", "", "", -2, 1.0);
		AddNpc(58, 147380, "Empty Npc 2 Times", "f_remains_37", 1443.939941, 1094.280029, 572.359985, 0.0, "REMAIN37_SQ04", "", "", -2, 1.0);
		AddNpc(58, 147380, "Empty Npc 2 Times", "f_remains_37", 1252.400024, 1094.280029, 656.530029, 0.0, "REMAIN37_SQ04", "", "", -2, 1.0);
		AddNpc(58, 147380, "Empty Npc 2 Times", "f_remains_37", 1380.130005, 1094.280029, 418.880005, 0.0, "REMAIN37_SQ04", "", "", -2, 1.0);
		AddNpc(58, 147380, "Empty Npc 2 Times", "f_remains_37", 1483.25, 1094.280029, 383.029999, 0.0, "REMAIN37_SQ04", "", "", -2, 1.0);
		AddNpc(58, 147380, "Empty Npc 2 Times", "f_remains_37", 1529.699951, 1094.280029, 535.97998, 0.0, "REMAIN37_SQ04", "", "", -2, 1.0);
		AddNpc(58, 147380, "Empty Npc 2 Times", "f_remains_37", 1504.02002, 1094.280029, 742.0, 0.0, "REMAIN37_SQ04", "", "", -2, 1.0);
		AddNpc(58, 147380, "Empty Npc 2 Times", "f_remains_37", 1664.300049, 1094.280029, 814.859985, 0.0, "REMAIN37_SQ04", "", "", -2, 1.0);
		AddNpc(58, 147380, "Empty Npc 2 Times", "f_remains_37", 1734.75, 1094.280029, 721.099976, 0.0, "REMAIN37_SQ04", "", "", -2, 1.0);
		AddNpc(58, 147380, "Empty Npc 2 Times", "f_remains_37", 1459.060059, 1094.280029, 695.409973, 0.0, "REMAIN37_SQ04", "", "", -2, 1.0);
		AddNpc(58, 147380, "Empty Npc 2 Times", "f_remains_37", 1343.050049, 1094.280029, 345.329987, 0.0, "REMAIN37_SQ04", "", "", -2, 1.0);
		AddNpc(58, 147380, "Empty Npc 2 Times", "f_remains_37", 1518.0, 1094.280029, 320.579987, 0.0, "REMAIN37_SQ04", "", "", -2, 1.0);
		AddNpc(58, 147380, "Empty Npc 2 Times", "f_remains_37", 1251.77002, 1094.280029, 524.97998, 0.0, "REMAIN37_SQ04", "", "", -2, 1.0);
		AddNpc(63, 151061, "Hawk", "f_remains_37", 595.868652, 1008.388489, -1572.822388, -90.0, "", "", "", -2, 40.0);
		AddNpc(64, 147392, "Treasure Box 1", "f_remains_37", -62.380001, 1300.630005, 2786.76001, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(66, 20016, "Western Woods Scout", "f_remains_37", 939.400024, 1141.390015, 485.109985, 48.0, "JOB_MATADOR1_NPC", "", "", -2, 40.0);
		AddNpc(67, 47106, "Canyon Area Device 5", "f_remains_37", 298.382355, 1178.064819, 706.730347, 0.0, "", "JOB_MATADOR1_Q_OBJ", "", -2, 40.0);
		AddNpc(67, 47106, "Canyon Area Device 5", "f_remains_37", 394.694641, 1178.064819, 610.394958, 0.0, "", "JOB_MATADOR1_Q_OBJ", "", -2, 40.0);
		AddNpc(67, 47106, "Canyon Area Device 5", "f_remains_37", 437.459869, 1178.064819, 752.416321, 0.0, "", "JOB_MATADOR1_Q_OBJ", "", -2, 40.0);
	}
}
