// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_rokas_31 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(601, 47413, "Human Rexipher", "f_rokas_31", 656.0, 107.0, -1211.0, 0.0, "ROKAS31_PACT_END", "", "", -2, 50.0);
		AddNpc(602, 47413, "Human Rexipher", "f_rokas_31", -159.312347, 107.103897, -501.168854, 0.0, "ROKAS31_REXITHER2", "", "", -2, 50.0);
		AddNpc(605, 20026, "", "f_rokas_31", -1100.0, 236.0, 280.0, 0.0, "", "ROKAS31_REXITHER3TRACK", "", -2, 150.0);
		AddNpc(611, 47192, "Literature 3", "f_rokas_31", -1229.0, 217.0, 576.0, 110.0, "ROKAS31_RECORD", "", "", -2, 30.0);
		AddNpc(613, 147345, "Cyrenia Odell", "f_rokas_31", -127.129997, 107.099998, -373.190002, -90.0, "ROKAS31_ODEL2", "", "", -2, 0.0);
		AddNpc(617, 47107, "Canyon Area Device 6", "f_rokas_31", 57.366791, 107.103897, -750.576965, 0.0, "ROKAS31_REXITHER1", "", "", -2, 40.0);
		AddNpc(618, 147392, "Treasure Box 1", "f_rokas_31", -736.157043, 107.103897, -1088.933228, -90.0, "ROKAS31_SUB_01_BOX", "", "", -2, 40.0);
		AddNpc(619, 147410, "Female Guard", "f_rokas_31", 508.942627, 107.103897, 84.364807, -86.0, "ROKAS31_SUB", "", "", -2, 40.0);
		AddNpc(621, 40110, "Statue Of Goddess Zemyna", "f_rokas_31", 496.0, 107.0, -27.0, -100.0, "F_ROKAS_31_EV_55_001", "F_ROKAS_31_EV_55_001", "F_ROKAS_31_EV_55_001", -2, 150.0);
		AddNpc(623, 151051, "Black Crystal", "f_rokas_31", -500.403442, 107.103882, -1023.291504, 0.0, "", "", "", -2, 40.0);
		AddNpc(629, 147392, "Treasure Box 1", "f_rokas_31", -736.0, 107.099998, -1088.0, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(630, 40095, "", "f_rokas_31", -381.611664, 205.764587, 143.396271, 0.0, "", "EXPLORER_MISLE30", "", -2, 20.0);
	}
}
