// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_rokas_29 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(602, 20041, "", "f_rokas_29", 1561.0, 642.0, -923.0, 0.0, "", "ROKAS29_INITIATING1_1", "", -2, 120.0);
		AddNpc(604, 47413, "Human Rexipher", "f_rokas_29", -770.0, 617.0, -1564.0, 0.0, "ROKAS29_HALF_SUCCESS1", "ROKAS29_HALF_SUCCESS1_1", "", -2, 130.0);
		AddNpc(605, 152000, "Ordinary Husband", "f_rokas_29", 1641.212769, 470.820221, 757.552124, 270.0, "VACYS_LIVE", "", "", -2, 130.0);
		AddNpc(606, 47161, "Lost Stuff Of Vendor 2", "f_rokas_29", 2265.0, 472.0, 220.0, 0.0, "ROKAS29_BAG", "", "", -2, 130.0);
		AddNpc(607, 20123, "Rexipher Human(Data Exchange Required)", "f_rokas_29", 163.0, 681.0, 769.0, 0.0, "ROKAS29_FIRE", "", "", -2, 130.0);
		AddNpc(608, 152000, "Ordinary Husband", "f_rokas_29", 168.589996, 681.0, 792.080017, 270.0, "VACYS_SOUL", "", "", -2, 130.0);
		AddNpc(609, 20041, "", "f_rokas_29", 1549.0, 471.0, 539.0, 0.0, "", "VACYS_LIVE_ENTER", "", -2, 200.0);
		AddNpc(610, 155026, "Valley Area Soil", "f_rokas_29", -1184.0, 681.0, 320.0, 0.0, "ROKAS29_SLATE1", "", "", -2, 30.0);
		AddNpc(611, 155026, "Valley Area Soil", "f_rokas_29", -1746.236572, 784.016296, 700.191345, 0.0, "ROKAS29_SLATE2", "", "", -2, 30.0);
		AddNpc(612, 155026, "Valley Area Soil", "f_rokas_29", -792.0, 680.0, -567.0, 0.0, "ROKAS29_SLATE3", "", "", -2, 30.0);
		AddNpc(613, 47413, "Human Rexipher", "f_rokas_29", 2332.0, 468.0, 666.0, 0.0, "ROKAS29_MQ_REXITHER1", "", "", -2, 0.0);
		AddNpc(614, 47413, "Human Rexipher", "f_rokas_29", -384.291077, 680.630737, -413.119324, 0.0, "ROKAS29_MQ_REXITHER6", "", "", -2, 0.0);
		AddNpc(622, 47413, "Human Rexipher", "f_rokas_29", 1080.552246, 657.834229, -785.350281, -67.0, "ROKAS29_MQ_REXITHER2", "", "", -2, 0.0);
		AddNpc(623, 47413, "Human Rexipher", "f_rokas_29", 1764.482788, 470.820221, 464.243195, 270.0, "ROKAS29_MQ_REXITHER3", "", "", -2, 0.0);
		AddNpc(624, 47413, "Human Rexipher", "f_rokas_29", -66.241295, 681.778748, 574.990967, 0.0, "ROKAS29_MQ_REXITHER4", "", "", -2, 0.0);
		AddNpc(625, 47413, "Human Rexipher", "f_rokas_29", -666.393555, 681.691528, 389.688507, 0.0, "ROKAS29_MQ_REXITHER5", "", "", -2, 0.0);
		AddNpc(627, 20026, "", "f_rokas_29", -368.212158, 680.630554, -428.273163, 0.0, "", "ROKAS29_MQ_REXITHERLOST", "", -2, 120.0);
		AddNpc(628, 153053, "Mausoleum Gravestone03 (Blue)", "f_rokas_29", 1073.306641, 657.823303, -819.924377, -63.0, "ROKAS29_MQ_DEVICE1", "", "", -2, 30.0);
		AddNpc(629, 153053, "Mausoleum Gravestone03 (Blue)", "f_rokas_29", 1343.0, 470.0, 311.0, -63.0, "ROKAS29_MQ_DEVICE2", "", "", -2, 30.0);
		AddNpc(631, 153053, "Mausoleum Gravestone03 (Blue)", "f_rokas_29", -680.0, 681.0, 360.0, -63.0, "ROKAS29_MQ_DEVICE4", "", "", -2, 30.0);
		AddNpc(632, 153053, "Mausoleum Gravestone03 (Blue)", "f_rokas_29", -332.0, 680.0, -398.0, -63.0, "ROKAS29_MQ_DEVICE5", "", "", -2, 30.0);
		AddNpc(640, 47190, "Literature 1", "f_rokas_29", -484.457031, 617.135315, -2083.193115, 15.0, "", "", "", -2, 40.0);
		AddNpc(654, 147392, "Treasure Box 1", "f_rokas_29", 1114.73999, 657.969971, -1202.02002, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
	}
}
