// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_rokas_30 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(607, 20041, "", "f_rokas_30", 954.414734, 326.241699, 410.921173, 0.0, "", "ROKAS30_ATK_DEFENCE_TRIGGER", "", -2, 50.0);
		AddNpc(608, 20109, "Veteran Miner", "f_rokas_30", 1406.0, 284.0, 662.0, -90.0, "ROKAS30_PIPOTI", "", "", -2, 50.0);
		AddNpc(609, 40095, "", "f_rokas_30", 1240.0, 148.0, -221.0, 0.0, "", "ROKAS30_PIPOTI01_TRIGGER", "", -2, 300.0);
		AddNpc(610, 20025, "", "f_rokas_30", 359.0, 402.0, 1078.0, 0.0, "ROKAS30_PIPOTI02_TRIGGER", "", "", -2, 50.0);
		AddNpc(611, 20025, "", "f_rokas_30", -220.824081, 348.687714, 716.848999, 0.0, "ROKAS30_PIPOTI03_TRIGGER", "", "", -2, 50.0);
		AddNpc(612, 20025, "", "f_rokas_30", 34.867664, 215.7491, -311.338348, 0.0, "ROKAS30_PIPOTI04_TRIGGER", "", "", -2, 50.0);
		AddNpc(613, 20025, "", "f_rokas_30", -1491.976074, 215.7491, -416.765625, 0.0, "ROKAS30_PIPOTI05_TRIGGER", "", "", -2, 50.0);
		AddNpc(619, 20108, "Minor Commander", "f_rokas_30", 950.130005, 148.169998, -782.25, -45.0, "ROKAS30_BAIL", "", "", -2, 0.0);
		AddNpc(620, 147421, "Paladin Follower No Instrument C1", "f_rokas_30", 1140.0, 148.0, -476.0, 0.0, "ROKAS30_COLLIN", "", "", -2, 0.0);
		AddNpc(621, 147345, "Cyrenia Odell", "f_rokas_30", 1551.0, 284.0, 410.0, 0.0, "ROKAS30_ODEL", "", "", -2, 0.0);
		AddNpc(627, 47102, "Canyon Area Device 1", "f_rokas_30", -1351.0, 193.0, -873.0, 0.0, "ROKAS30_SAELDEVICE2", "", "", -2, 30.0);
		AddNpc(629, 47102, "Canyon Area Device 1", "f_rokas_30", 542.0, 402.0, 1065.0, 0.0, "ROKAS30_SEALDESTROY1", "", "", -2, 30.0);
		AddNpc(630, 47102, "Canyon Area Device 1", "f_rokas_30", -205.0, 348.0, 484.0, 0.0, "ROKAS30_SAELDEVICE1", "", "", -2, 30.0);
		AddNpc(631, 47102, "Canyon Area Device 1", "f_rokas_30", -310.0, 215.0, -250.0, 1.0, "ROKAS30_SEALDESTROY2", "", "", -2, 30.0);
		AddNpc(632, 147345, "Cyrenia Odell", "f_rokas_30", -1397.0, 215.0, -493.0, 0.0, "", "ROKAS30_ODEL_KIDNAP", "", -2, 100.0);
		AddNpc(638, 20011, "Supply Soldier", "f_rokas_30", -164.0, 348.0, 488.0, 0.0, "ROKAS30_ZACARIEL_SERVANT1", "", "", -2, 30.0);
		AddNpc(639, 20015, "View", "f_rokas_30", -1313.0, 179.0, -838.0, 0.0, "ROKAS30_ZACARIEL_SERVANT2", "", "", -2, 30.0);
		AddNpc(640, 20101, "", "f_rokas_30", 1018.0, 304.0, 389.0, 0.0, "", "ROKAS30_SUDDEN_ATTACK", "", -2, 30.0);
		AddNpc(640, 20101, "", "f_rokas_30", 1000.0, 318.0, 394.0, 0.0, "", "ROKAS30_SUDDEN_ATTACK", "", -2, 30.0);
		AddNpc(641, 152002, "Old Man", "f_rokas_30", 752.554382, 326.165375, 475.001617, -73.0, "ROKAS30_HURT", "", "", -2, 30.0);
		AddNpc(643, 20026, "", "f_rokas_30", 539.0, 401.0, 992.0, 0.0, "", "ROKAS30_SEALPRODECT_1", "", -2, 150.0);
		AddNpc(644, 147345, "Cyrenia Odell", "f_rokas_30", 145.0, 325.0, 385.0, 0.0, "ROKAS_ODEL2", "", "", -2, 30.0);
		AddNpc(651, 147318, "Hogma Stone Statue01", "f_rokas_30", -368.190002, 215.75, -217.259995, -38.0, "", "ROKAS30_MQ6_1_HOGMA", "", -2, 40.0);
		AddNpc(652, 147318, "Hogma Stone Statue01", "f_rokas_30", -304.690002, 215.75, -205.570007, -137.0, "", "ROKAS30_MQ6_1_HOGMA", "", -2, 40.0);
		AddNpc(653, 147316, "Hogma Stone Statue 2", "f_rokas_30", -397.529999, 215.75, -185.710007, -40.0, "", "ROKAS30_MQ6_1_HOGMA", "", -2, 40.0);
		AddNpc(654, 147317, "Hogma Shaman Stone Statue", "f_rokas_30", -359.109985, 215.75, -187.029999, -92.0, "", "ROKAS30_MQ6_1_HOGMA", "", -2, 40.0);
		AddNpc(655, 147315, "Hogma Captain Stone Statue", "f_rokas_30", -326.790009, 215.75, -280.26001, 36.0, "", "ROKAS30_MQ6_1_HOGMA", "", -2, 40.0);
		AddNpc(657, 147392, "Treasure Box 1", "f_rokas_30", 359.899994, 402.109985, 1077.959961, 1.0, "ROKAS30_PIPOTI02_TREASUREBOX", "", "", -2, 40.0);
		AddNpc(660, 147392, "Treasure Box 1", "f_rokas_30", -239.0, 348.0, 727.0, 0.0, "ROKAS30_PIPOTI03_TREASUREBOX", "", "", -2, 40.0);
		AddNpc(661, 147392, "Treasure Box 1", "f_rokas_30", 34.869999, 215.7491, -311.339996, -175.0, "ROKAS30_PIPOTI04_TREASUREBOX", "", "", -2, 40.0);
		AddNpc(662, 147392, "Treasure Box 1", "f_rokas_30", -1510.02002, 215.7491, -414.290009, 0.0, "ROKAS30_PIPOTI05_TREASUREBOX", "", "", -2, 40.0);
		AddNpc(668, 147392, "Treasure Box 1", "f_rokas_30", -433.940002, 348.790009, 306.959991, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(669, 154025, "Petrification Detector", "f_rokas_30", 1119.304565, 148.168472, -347.16748, 0.0, "JOB_PLAGUEDOCTOR71_NPC1", "", "", -2, 40.0);
	}
}
