// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_rokas_28 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(10, 147336, "Broken Equipment", "f_rokas_28", -337.0, 1187.0, 299.0, 135.0, "", "ROKAS28_BLOCK", "", -2, 80.0);
		AddNpc(602, 20025, "", "f_rokas_28", -445.0, 1297.0, 70.0, 0.0, "", "ROKAS28_ODEL_TRIGGER", "", -2, 80.0);
		AddNpc(603, 20025, "", "f_rokas_28", 651.0, 1241.0, 466.0, 0.0, "ROKAS28_TRAP", "", "", -2, 50.0);
		AddNpc(606, 47107, "Canyon Area Device 6", "f_rokas_28", 1422.0, 1159.0, 772.0, 0.0, "ROKAS28_ENTICE", "", "", -2, 50.0);
		AddNpc(1000, 20125, "Mid Commander (Male 2)", "f_rokas_28", -544.0, 1121.0, -1500.0, -45.0, "ROKAS28_MQ1_1", "ROKAS28_MQ1_2", "", -2, 100.0);
		AddNpc(1001, 20025, "", "f_rokas_28", 556.0, 1241.0, 553.0, 0.0, "", "ROKAS28_TRAP_2", "", -2, 40.0);
		AddNpc(1003, 20041, "", "f_rokas_28", 1616.0, 1161.0, 1791.0, 0.0, "", "ROKAS28_ODEL_MQ4_ENT", "", -2, 300.0);
		AddNpc(1004, 20025, "", "f_rokas_28", 1263.859985, 1271.993042, 1974.244019, 0.0, "ROKAS28_MQ5_NPC", "", "", -2, 30.0);
		AddNpc(1005, 153040, "Historian (F)", "f_rokas_28", -475.0, 1183.0, -506.0, 0.0, "ROKAS28_ODEL_MQ6", "", "", -2, 50.0);
		AddNpc(1006, 20025, "", "f_rokas_28", -1318.0, 1298.0, -480.0, 0.0, "", "ROKAS28_MQ7_NPC", "", -2, 150.0);
		AddNpc(1011, 47106, "Canyon Area Device 5", "f_rokas_28", -216.0, 1187.0, -69.0, 0.0, "ROKAS28_SEAL_FAKE1", "", "", -2, 30.0);
		AddNpc(1012, 47106, "Canyon Area Device 5", "f_rokas_28", 1650.0, 1161.0, 1715.0, 0.0, "ROKAS28_SEAL_TRUE1", "", "", -2, 30.0);
		AddNpc(1013, 47106, "Canyon Area Device 5", "f_rokas_28", -616.0, 1297.0, 14.0, 0.0, "ROKAS28_SEAL_TRUE2", "", "", -2, 30.0);
		AddNpc(1014, 47106, "Canyon Area Device 5", "f_rokas_28", 371.0, 1349.0, 646.0, 0.0, "ROKAS28_SEAL_TRUE3", "", "", -2, 30.0);
		AddNpc(1015, 20150, "Veteran Miner 2", "f_rokas_28", 251.0, 1158.0, -346.0, 0.0, "ROKAS28_FRIDKA", "", "", -2, 30.0);
		AddNpc(1016, 20102, "Merchant 1", "f_rokas_28", 501.0, 1157.0, -177.0, 0.0, "ROKAS28_ORION", "", "", -2, 30.0);
		AddNpc(1023, 153040, "Historian (F)", "f_rokas_28", 16.0, 1158.0, -571.0, 0.0, "ROKAS28_ODEL", "", "", -2, 30.0);
		AddNpc(1032, 147469, "No Shadow Npc", "f_rokas_28", 1647.958008, 1160.871948, 2088.266113, 0.0, "ROKAS28_SECRET_PORTAL", "", "", -2, 40.0);
		AddNpc(1040, 147392, "Treasure Box 1", "f_rokas_28", 630.549988, 1156.97998, -159.619995, 180.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(1041, 47106, "Canyon Area Device 5", "f_rokas_28", -638.0, 1184.0, -617.0, 0.0, "ROKAS28_SEAL_FAKE2", "", "", -2, 30.0);
		AddNpc(1042, 47106, "Canyon Area Device 5", "f_rokas_28", -42.0, 1121.0, -1502.0, 0.0, "ROKAS28_SEAL_FAKE3", "", "", -2, 30.0);
		AddNpc(1043, 47106, "Canyon Area Device 5", "f_rokas_28", 733.0, 1159.0, -446.0, 0.0, "ROKAS28_SEAL_FAKE4", "", "", -2, 30.0);
		AddNpc(1044, 47106, "Canyon Area Device 5", "f_rokas_28", 777.0, 1241.0, 724.0, 0.0, "ROKAS28_SEAL_FAKE5", "", "", -2, 30.0);
		AddNpc(1045, 47106, "Canyon Area Device 5", "f_rokas_28", 1156.0, 1159.0, 1125.0, 0.0, "ROKAS28_SEAL_FAKE6", "", "", -2, 30.0);
	}
}
