// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_rokas_25 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(2, 47102, "Canyon Area Device 1", "f_rokas_25", -1941.0, 511.0, 912.0, -37.0, "ROKAS25_SWITCH1", "ROKAS25_SWITCH1", "", -2, 30.0);
		AddNpc(3, 20118, "Tobias", "f_rokas_25", -2300.0, 268.0, -421.0, -37.0, "ROKAS25_REXIPHER2", "", "", -2, 35.0);
		AddNpc(5, 20139, "Pablo", "f_rokas_25", 441.630005, 267.940002, 241.399994, -37.0, "ROKAS25_REXIPHER3", "", "", -2, 35.0);
		AddNpc(8, 47102, "Canyon Area Device 1", "f_rokas_25", 1080.0, 164.0, -200.0, -37.0, "ROKAS25_SWITCH3", "ROKAS25_SWITCH3", "", -2, 30.0);
		AddNpc(11, 47102, "Canyon Area Device 1", "f_rokas_25", 2096.0, 189.0, 393.0, -37.0, "ROKAS25_SWITCH4", "ROKAS25_SWITCH4", "", -2, 250.0);
		AddNpc(12, 47102, "Canyon Area Device 1", "f_rokas_25", 1612.0, 71.0, -1072.0, -37.0, "ROKAS25_SWITCH5", "", "", -2, 30.0);
		AddNpc(13, 47102, "Canyon Area Device 1", "f_rokas_25", 2513.0, 71.0, -1065.0, -37.0, "ROKAS25_SWITCH6", "", "", -2, 250.0);
		AddNpc(32, 47101, "Royal Mausoleum Entrance", "f_rokas_25", 2011.0, 164.0, -227.0, -60.0, "", "ROKAS25_ZACHARIEL32_NPC", "", -2, 300.0);
		AddNpc(44, 20041, "", "f_rokas_25", 818.007507, 347.536987, 1171.682373, 0.0, "", "JOB_PYROMANCER3_1_TRIGGER", "", -2, 250.0);
		AddNpc(45, 147312, "Dropped Paper", "f_rokas_25", -1908.254761, 359.16629, 572.577881, 0.0, "JOB_THAUMATURGE3_1_PAPER1", "", "", -2, 40.0);
		AddNpc(46, 147312, "Dropped Paper", "f_rokas_25", -2061.469971, 359.16629, 574.375427, 0.0, "JOB_THAUMATURGE3_1_PAPER2", "", "", -2, 40.0);
		AddNpc(47, 147312, "Dropped Paper", "f_rokas_25", -2128.049805, 359.16629, 637.806641, 0.0, "JOB_THAUMATURGE3_1_PAPER3", "", "", -2, 40.0);
		AddNpc(101, 20117, "Armand", "f_rokas_25", -1964.0, 268.0, -469.0, -90.0, "ROKAS25_SUB1", "", "", -2, 35.0);
		AddNpc(607, 40064, "Grill", "f_rokas_25", 205.0, 267.940002, 805.0, -111.0, "ROKAS25_CALDRON1", "", "", -2, 35.0);
		AddNpc(608, 20150, "Veteran Miner 2", "f_rokas_25", -1017.0, 268.0, 418.0, 0.0, "ROKAS25_KEBIN", "", "", -2, 35.0);
		AddNpc(609, 20138, "Cedric", "f_rokas_25", 190.830002, 267.940002, 762.950012, 0.0, "ROKAS25_BINSENT", "", "", -2, 35.0);
		AddNpc(610, 20139, "Pablo", "f_rokas_25", -1828.0, 268.0, -567.0, -84.0, "ROKAS25_HILDA1", "", "", -2, 35.0);
		AddNpc(611, 20139, "Pablo", "f_rokas_25", -805.379517, 267.944092, 836.407104, 0.0, "ROKAS25_HILDA2", "", "", -2, 35.0);
		AddNpc(612, 20139, "Pablo", "f_rokas_25", 32.68515, 267.944092, 382.909515, 0.0, "ROKAS25_HILDA3", "", "", -2, 35.0);
		AddNpc(624, 40064, "Grill", "f_rokas_25", 249.270004, 267.940002, 799.52002, -80.0, "ROKAS25_CALDRON2", "", "", -2, 35.0);
		AddNpc(650, 47160, "Lost Stuff Of Vendor 1", "f_rokas_25", -1911.329224, 268.62561, -1097.920532, 0.0, "ROKAS25_EX2_STRUCTURE", "", "", -2, 35.0);
		AddNpc(650, 47160, "Lost Stuff Of Vendor 1", "f_rokas_25", -2151.335205, 268.62561, -1180.065063, 0.0, "ROKAS25_EX2_STRUCTURE", "", "", -2, 35.0);
		AddNpc(650, 47160, "Lost Stuff Of Vendor 1", "f_rokas_25", -2006.6698, 268.62561, -776.872375, 0.0, "ROKAS25_EX2_STRUCTURE", "", "", -2, 35.0);
		AddNpc(650, 47160, "Lost Stuff Of Vendor 1", "f_rokas_25", -2384.875, 268.62561, -1011.536621, 0.0, "ROKAS25_EX2_STRUCTURE", "", "", -2, 35.0);
		AddNpc(650, 47160, "Lost Stuff Of Vendor 1", "f_rokas_25", -2437.09668, 268.62561, -664.148071, 0.0, "ROKAS25_EX2_STRUCTURE", "", "", -2, 35.0);
		AddNpc(650, 47160, "Lost Stuff Of Vendor 1", "f_rokas_25", -2321.536865, 268.62561, -796.326355, 0.0, "ROKAS25_EX2_STRUCTURE", "", "", -2, 35.0);
		AddNpc(650, 47160, "Lost Stuff Of Vendor 1", "f_rokas_25", -1622.0, 268.0, -905.0, 0.0, "ROKAS25_EX2_STRUCTURE", "", "", -2, 35.0);
		AddNpc(650, 47160, "Lost Stuff Of Vendor 1", "f_rokas_25", -1739.483643, 268.62561, -1144.72937, 0.0, "ROKAS25_EX2_STRUCTURE", "", "", -2, 35.0);
		AddNpc(656, 147390, "Paladin Follower A1", "f_rokas_25", 1985.0, 167.0, -328.0, 0.0, "ROKAS25_REXIPHER5", "", "", -2, 35.0);
		AddNpc(659, 147312, "Dropped Paper", "f_rokas_25", 677.97644, 181.495193, 770.38208, 0.0, "ROKAS_25_HQ01_NPC01", "", "", -2, 40.0);
		AddNpc(660, 147312, "Dropped Paper", "f_rokas_25", 1720.164673, 164.308395, 77.561882, 0.0, "ROKAS_25_HQ01_NPC02", "", "", -2, 40.0);
		AddNpc(661, 147312, "Dropped Paper", "f_rokas_25", 1399.872437, 71.802261, -837.157654, 0.0, "ROKAS_25_HQ01_NPC03", "", "", -2, 40.0);
		AddNpc(662, 147312, "Dropped Paper", "f_rokas_25", 1946.991455, 189.087402, 634.787354, 0.0, "ROKAS_25_HQ01_NPC04", "", "", -2, 40.0);
		AddNpc(679, 147392, "Treasure Box 1", "f_rokas_25", -2482.459961, 268.730011, -913.390015, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(680, 40095, "", "f_rokas_25", -686.045654, 267.944092, 834.398376, 0.0, "", "EXPLORER_MISLE27", "", -2, 20.0);
	}
}
