// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_rokas_26 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(3, 20142, "Minor Commander 5", "f_rokas_26", 42.0, 1739.0, -1171.0, -90.0, "ROKAS26_BIO", "", "", -2, 50.0);
		AddNpc(4, 20016, "Western Woods Scout", "f_rokas_26", -406.0, 1837.0, -312.0, 0.0, "ROKAS26_EHTA", "", "", -2, 50.0);
		AddNpc(5, 20016, "Western Woods Scout", "f_rokas_26", 923.0, 1670.0, -749.0, 0.0, "ROKAS26_LINT", "ROKAS_26_HQ01_NPC01", "ROKAS_26_HQ01_SESSIONDESTORY", -2, 80.0);
		AddNpc(6, 20118, "Tobias", "f_rokas_26", -49.0, 1739.0, -1210.0, 0.0, "ROKAS26_REXIPHER1", "", "", -2, 50.0);
		AddNpc(7, 20026, "", "f_rokas_26", -125.461731, 1738.300049, -1320.5625, 0.0, "", "ROKAS25_TO_26_START", "", -2, 300.0);
		AddNpc(9, 20026, "", "f_rokas_26", 1120.0, 1671.0, -1471.0, 0.0, "", "ROKAS26_Q4_ENT", "", -2, 80.0);
		AddNpc(11, 20041, "", "f_rokas_26", -1147.845459, 2015.318115, 291.939392, 0.0, "", "ROKAS26_QUEST03", "", -2, 250.0);
		AddNpc(12, 20041, "", "f_rokas_26", -1458.0, 2168.0, 1359.0, 0.0, "", "ROKAS26_QUEST04", "", -2, 250.0);
		AddNpc(13, 20026, "", "f_rokas_26", -358.0, 1739.0, -1201.0, 0.0, "", "ROKAS26_Q14_ENT", "", -2, 80.0);
		AddNpc(14, 20026, "", "f_rokas_26", 1685.0, 1722.0, -275.0, -135.0, "", "ROKAS26_QUEST01", "", -2, 30.0);
		AddNpc(15, 20026, "", "f_rokas_26", -1062.0, 1768.0, -1751.0, 0.0, "", "ROKAS26_Q5_ENT", "", -2, 80.0);
		AddNpc(16, 20026, "", "f_rokas_26", 1091.0, 1671.0, -1478.0, 0.0, "", "ROKAS26_QS5_ENT", "", -2, 80.0);
		AddNpc(18, 152068, "Stone", "f_rokas_26", -1179.0, 2093.0, 784.0, 0.0, "ROKAS26_STONE", "", "", -2, 80.0);
		AddNpc(18, 152068, "Stone", "f_rokas_26", -1146.0, 2093.0, 826.0, 0.0, "ROKAS26_STONE", "", "", -2, 80.0);
		AddNpc(18, 152068, "Stone", "f_rokas_26", -1386.0, 2093.0, 814.0, 0.0, "ROKAS26_STONE", "", "", -2, 80.0);
		AddNpc(18, 152068, "Stone", "f_rokas_26", -1341.0, 2093.0, 766.0, 0.0, "ROKAS26_STONE", "", "", -2, 80.0);
		AddNpc(18, 152068, "Stone", "f_rokas_26", -1340.0, 2093.0, 940.0, 0.0, "ROKAS26_STONE", "", "", -2, 80.0);
		AddNpc(18, 152068, "Stone", "f_rokas_26", -1115.0, 2093.0, 925.0, 0.0, "ROKAS26_STONE", "", "", -2, 80.0);
		AddNpc(18, 152068, "Stone", "f_rokas_26", -1289.0, 2015.0, 457.0, 0.0, "ROKAS26_STONE", "", "", -2, 80.0);
		AddNpc(18, 152068, "Stone", "f_rokas_26", -1092.0, 2015.0, 551.0, 0.0, "ROKAS26_STONE", "", "", -2, 80.0);
		AddNpc(18, 152068, "Stone", "f_rokas_26", -991.0, 2015.0, 474.0, 0.0, "ROKAS26_STONE", "", "", -2, 80.0);
		AddNpc(18, 152068, "Stone", "f_rokas_26", -987.0, 2015.0, 250.0, 0.0, "ROKAS26_STONE", "", "", -2, 80.0);
		AddNpc(18, 152068, "Stone", "f_rokas_26", -1000.0, 2015.0, 210.0, 0.0, "ROKAS26_STONE", "", "", -2, 80.0);
		AddNpc(18, 152068, "Stone", "f_rokas_26", -1061.0, 2015.0, 126.0, 0.0, "ROKAS26_STONE", "", "", -2, 80.0);
		AddNpc(18, 152068, "Stone", "f_rokas_26", -1128.0, 2015.0, 70.0, 0.0, "ROKAS26_STONE", "", "", -2, 80.0);
		AddNpc(19, 47201, "Discolored Grass Of Siauliai", "f_rokas_26", 1013.0, 1670.0, -1558.0, 0.0, "ROKAS26_POPPY", "", "", -2, 25.0);
		AddNpc(19, 47201, "Discolored Grass Of Siauliai", "f_rokas_26", 1143.0, 1670.0, -1121.0, 0.0, "ROKAS26_POPPY", "", "", -2, 25.0);
		AddNpc(19, 47201, "Discolored Grass Of Siauliai", "f_rokas_26", 1183.0, 1670.0, -1363.0, 0.0, "ROKAS26_POPPY", "", "", -2, 25.0);
		AddNpc(19, 47201, "Discolored Grass Of Siauliai", "f_rokas_26", 1181.0, 1670.0, -1526.0, 0.0, "ROKAS26_POPPY", "", "", -2, 25.0);
		AddNpc(19, 47201, "Discolored Grass Of Siauliai", "f_rokas_26", 1058.0, 1670.0, -1037.0, -90.0, "ROKAS26_POPPY", "", "", -2, 25.0);
		AddNpc(19, 47201, "Discolored Grass Of Siauliai", "f_rokas_26", 1196.0, 1670.0, -1232.0, 0.0, "ROKAS26_POPPY", "", "", -2, 25.0);
		AddNpc(19, 47201, "Discolored Grass Of Siauliai", "f_rokas_26", 826.0, 1670.0, -1198.0, 0.0, "ROKAS26_POPPY", "", "", -2, 25.0);
		AddNpc(19, 47201, "Discolored Grass Of Siauliai", "f_rokas_26", 1224.0, 1670.0, -1296.0, 0.0, "ROKAS26_POPPY", "", "", -2, 25.0);
		AddNpc(19, 47201, "Discolored Grass Of Siauliai", "f_rokas_26", 1193.0, 1670.0, -1167.0, 0.0, "ROKAS26_POPPY", "", "", -2, 25.0);
		AddNpc(19, 47201, "Discolored Grass Of Siauliai", "f_rokas_26", 1019.0, 1670.0, -1479.0, 0.0, "ROKAS26_POPPY", "", "", -2, 25.0);
		AddNpc(19, 47201, "Discolored Grass Of Siauliai", "f_rokas_26", 928.0, 1670.0, -1213.0, 0.0, "ROKAS26_POPPY", "", "", -2, 25.0);
		AddNpc(19, 47201, "Discolored Grass Of Siauliai", "f_rokas_26", 968.0, 1670.0, -1298.0, 0.0, "ROKAS26_POPPY", "", "", -2, 25.0);
		AddNpc(20, 20041, "", "f_rokas_26", 136.0, 2140.0, 1758.0, 0.0, "", "ROKAS26_QUEST05", "", -2, 250.0);
		AddNpc(21, 40095, "", "f_rokas_26", -126.42923, 2140.500244, 1732.884155, 0.0, "ROKAS26_SUB_Q12", "", "", -2, 170.0);
		AddNpc(508, 147372, "Empty Npc", "f_rokas_26", -1117.031738, 2168.340088, 1548.978149, 0.0, "ROKAS26_SUB_Q10_TRIGGER", "", "", -2, 30.0);
		AddNpc(509, 147405, "Paladin Follower B3", "f_rokas_26", -340.0, 1738.0, -1440.0, 0.0, "ROKAS26_MQ1_NPC", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", 1090.0, 1670.0, -1431.0, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", 1232.231567, 1670.066772, -606.429565, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", 1697.523682, 1722.860229, -70.343643, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", -530.092346, 1761.812012, -999.475403, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", -130.408539, 1836.599976, -343.416382, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", 56.902611, 1836.599976, 652.444763, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", -622.977905, 1938.599976, 452.83783, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", -1109.11499, 2015.318115, 298.216919, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", -1265.189941, 2015.318115, 350.362885, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", -1240.616333, 2093.517334, 866.124023, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", 1123.740234, 1670.066772, -2283.187988, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", 1269.898438, 1670.066772, -1807.297363, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", 975.922424, 1670.066772, -1913.241211, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", 1132.790039, 1670.066772, -1892.02832, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", 1037.49231, 1670.066772, -1165.421875, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", 953.285583, 1670.066772, -927.564453, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", 1880.086914, 1722.860229, -234.991745, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", 1614.0, 1722.0, -371.0, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", -623.104309, 1805.329956, -739.456421, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", 50.076035, 1836.599976, -173.425568, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", 235.200775, 1836.599976, 341.559631, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", 94.765045, 1836.599976, 426.510803, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", -1209.114258, 2015.318115, 131.631363, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", -1454.758179, 2168.340088, 1342.088379, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", -1119.969238, 2168.340088, 1642.897827, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", -1160.0, 2168.0, 1319.0, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", -958.480774, 2168.340088, 1500.240601, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", 42.527412, 2140.500244, 1782.51062, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(510, 147372, "Empty Npc", "f_rokas_26", 30.319389, 2140.500244, 1582.565063, 0.0, "ROKAS26_MQ1_STONE", "", "", -2, 30.0);
		AddNpc(520, 152068, "Stone", "f_rokas_26", 1521.0, 1723.0, -314.0, 0.0, "ROKAS26_QUEST01_STONE_1", "", "", -2, 40.0);
		AddNpc(521, 47106, "Canyon Area Device 5", "f_rokas_26", -1503.520142, 2015.318115, 232.353943, 0.0, "ROKAS26_QUEST03_STONE", "", "", -2, 40.0);
		AddNpc(522, 47106, "Canyon Area Device 5", "f_rokas_26", -1359.734985, 2168.340088, 1179.565063, 0.0, "ROKAS26_QUEST04_STONE", "", "", -2, 40.0);
		AddNpc(523, 47106, "Canyon Area Device 5", "f_rokas_26", -143.990005, 2140.0, 1496.51001, 0.0, "ROKAS26_QUEST05_STONE", "", "", -2, 40.0);
		AddNpc(524, 153051, "Npc Shnayim", "f_rokas_26", 67.129303, 2140.500244, 1645.545776, -145.0, "", "ROKAS26_NPC_SHNAYIM", "", -2, 40.0);
		AddNpc(531, 147392, "Treasure Box 1", "f_rokas_26", 2048.050049, 1722.959961, 204.0, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(532, 20139, "Pablo", "f_rokas_26", -1024.324341, 2168.340088, 1909.930176, -96.0, "ROKAS24_RP_1_NPC", "", "", -2, 1.0);
		AddNpc(533, 40095, "", "f_rokas_26", -892.938721, 1767.127686, -1695.959106, 0.0, "", "EXPLORER_MISLE28", "", -2, 20.0);
		AddNpc(534, 154046, "Instanceddungeonentrynpc", "f_rokas_26", 77.204041, 2140.500244, 1689.680176, 0.0, "ROKAS_26_TO_GUILD_FIELD_BOSS", "", "", -2, 40.0);
	}
}
