// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_rokas_27 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(4, 20128, "Minor Commander 3", "f_rokas_27", 151.0, 1196.0, -2362.0, 45.0, "ROKAS27_GLEN", "", "", -2, 30.0);
		AddNpc(5, 20102, "Merchant 1", "f_rokas_27", -195.0, 1295.0, -1683.0, 0.0, "ROKAS27_HEINEN", "", "", -2, 30.0);
		AddNpc(6, 152001, "Ordinary Wife", "f_rokas_27", 916.999878, 1340.339355, 381.420563, -22.0, "ROKAS27_AIRINE", "", "", -2, 30.0);
		AddNpc(7, 147399, "Paladin Follower A2", "f_rokas_27", -486.117249, 1196.784424, -3033.804443, 0.0, "ROKAS27_REXITHER_1", "", "", -2, 50.0);
		AddNpc(11, 20026, "", "f_rokas_27", 892.0, 1198.0, -2099.0, 0.0, "", "ROKAS27_QB_7", "", -2, 150.0);
		AddNpc(12, 20026, "", "f_rokas_27", 918.0, 1209.0, -1156.0, 0.0, "", "ROKAS27_QB_9", "", -2, 180.0);
		AddNpc(12, 20026, "", "f_rokas_27", 933.0, 1209.0, -1145.0, 0.0, "", "ROKAS27_QB_9", "", -2, 180.0);
		AddNpc(14, 20026, "", "f_rokas_27", 1777.0, 1228.0, -291.0, 0.0, "", "ROKAS27_QB_11", "", -2, 180.0);
		AddNpc(15, 20026, "", "f_rokas_27", 1646.0, 1342.0, 160.0, 0.0, "", "ROKAS27_QB_13", "", -2, 180.0);
		AddNpc(20, 20026, "", "f_rokas_27", 357.0, 1242.0, -643.0, -56.0, "", "ROKAS27_QB_10", "", -2, 150.0);
		AddNpc(22, 47109, "Canyon Area Device 7", "f_rokas_27", 763.796265, 1340.339355, 238.651352, 0.0, "ROKAS27_QB_14_1", "", "", -2, 30.0);
		AddNpc(23, 47109, "Canyon Area Device 7", "f_rokas_27", 1134.333008, 1340.339355, 341.325287, 0.0, "ROKAS27_QB_14_2", "", "", -2, 30.0);
		AddNpc(24, 47109, "Canyon Area Device 7", "f_rokas_27", 983.797485, 1340.339355, 606.219666, 0.0, "ROKAS27_QB_14_3", "", "", -2, 30.0);
		AddNpc(26, 152002, "Old Man", "f_rokas_27", -435.559174, 1196.784424, -2988.451172, -69.0, "ROKAS27_DESIG_01", "", "", -2, 30.0);
		AddNpc(27, 152002, "Old Man", "f_rokas_27", 958.0, 1198.0, -1818.0, 0.0, "ROKAS27_DESIG_02", "", "", -2, 30.0);
		AddNpc(28, 20150, "Veteran Miner 2", "f_rokas_27", 337.0, 1295.0, -1527.0, -42.0, "ROKAS27_CABLE_LEFT", "", "", -2, 30.0);
		AddNpc(29, 20109, "Veteran Miner", "f_rokas_27", 888.0, 1209.0, -1158.0, -52.0, "ROKAS27_CABLE_RIGHT", "", "", -2, 30.0);
		AddNpc(30, 20026, "", "f_rokas_27", 1841.0, 1228.0, -144.0, 0.0, "", "ROKAS27_QB_10", "", -2, 180.0);
		AddNpc(31, 147438, "Corsair Master", "f_rokas_27", -201.197968, 1196.784424, -3102.801758, -90.0, "JOB_CORSAIR4_NPC", "", "", -2, 40.0);
		AddNpc(32, 155075, "Elementalist Submaster", "f_rokas_27", -235.139313, 1196.784424, -2850.654785, -90.0, "JOB_WARLOCK3_1_NPC", "", "", -2, 30.0);
		AddNpc(33, 57226, "Sadhu Master", "f_rokas_27", -344.0, 1197.0, -3309.0, 0.0, "JOB_SADU3_1_NPC", "", "", -2, 30.0);
		AddNpc(34, 147441, "Pardoner Master", "f_rokas_27", -533.801941, 1196.784424, -3222.404785, 0.0, "JOB_PARDONER4_1", "", "", -2, 40.0);
		AddNpc(80, 47109, "Canyon Area Device 7", "f_rokas_27", -819.0, 1295.0, -2247.0, -44.0, "", "ROKAS27_QB_3", "", -2, 180.0);
		AddNpc(607, 46212, "Box", "f_rokas_27", 595.0, 1196.0, -2676.0, 86.0, "ROKAS27_MQ1BOX", "", "", -2, 35.0);
		AddNpc(608, 46212, "Box", "f_rokas_27", 87.0, 1295.0, -1434.0, 86.0, "ROKAS27_MQ2BOX", "", "", -2, 35.0);
		AddNpc(609, 46212, "Box", "f_rokas_27", 956.0, 1234.0, -598.0, 86.0, "ROKAS27_MQ3BOX", "", "", -2, 35.0);
		AddNpc(610, 46212, "Box", "f_rokas_27", 2215.0, 1228.0, -87.0, 86.0, "ROKAS27_MQ4BOX", "", "", -2, 35.0);
		AddNpc(611, 46212, "Box", "f_rokas_27", 1904.0, 1228.0, -407.0, 86.0, "ROKAS27_MQ5BOX", "", "", -2, 35.0);
		AddNpc(612, 152002, "Old Man", "f_rokas_27", 1845.160034, 1227.670044, -110.029999, -107.0, "ROKAS27_DESIG_03", "", "", -2, 35.0);
		AddNpc(615, 152001, "Ordinary Wife", "f_rokas_27", 1828.369995, 1227.670044, -91.980003, -7.0, "ROKAS27_AIRINE2", "", "", -2, 35.0);
		AddNpc(706, 20026, "", "f_rokas_27", 916.626587, 1340.339355, 381.708374, 0.0, "", "ROKAS27_AIRINE_EFFECT", "", -2, 40.0);
		AddNpc(707, 152025, "Valley Device 8", "f_rokas_27", 912.319214, 1342.339355, 384.023438, -176.0, "", "ROKAS27_CUBE_2", "", -2, 40.0);
		AddNpc(708, 152024, "Valley Barrier Chain", "f_rokas_27", 731.259033, 1340.339355, 205.864243, -45.0, "", "ROKAS27_CHAIN01", "", -2, 40.0);
		AddNpc(709, 152024, "Valley Barrier Chain", "f_rokas_27", 1169.623291, 1340.339355, 334.22998, 80.0, "", "ROKAS27_CHAIN02", "", -2, 40.0);
		AddNpc(710, 152024, "Valley Barrier Chain", "f_rokas_27", 983.026123, 1340.339355, 599.952271, 161.0, "", "ROKAS27_CHAIN03", "", -2, 40.0);
		AddNpc(713, 20170, "Search Trigger", "f_rokas_27", 2070.219971, 1299.579956, 161.240005, 0.0, "", "", "", -2, 15.0);
		AddNpc(722, 147392, "Treasure Box 1", "f_rokas_27", 1148.77002, 1232.310059, -387.429993, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(723, 40095, "", "f_rokas_27", 2209.537842, 1227.670288, 119.49263, 0.0, "", "EXPLORER_MISLE29", "", -2, 20.0);
	}
}
