// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_rokas_24 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(4, 20108, "Minor Commander", "f_rokas_24", 476.0, 163.0, -2042.0, -90.0, "ROKAS_24_NEALS", "", "", -2, 35.0);
		AddNpc(5, 20158, "Gentleman 12", "f_rokas_24", 1598.0, 16.0, -185.0, 0.0, "ROKAS_24_BEARD", "", "", -2, 35.0);
		AddNpc(6, 147422, "Paladin Follower No Instrument C2", "f_rokas_24", -1041.0, 804.0, 1647.0, 0.0, "ROKAS_24_KEFEK", "", "", -2, 35.0);
		AddNpc(8, 147469, "No Shadow Npc", "f_rokas_24", -2908.685791, 1341.924316, -579.530762, 0.0, "ROKAS_24_BEACON_TRIGGER", "", "", -2, 50.0);
		AddNpc(9, 147372, "Empty Npc", "f_rokas_24", -168.0, 687.0, 2207.0, 0.0, "ROKAS_24_RELIC_TRIGGERGO", "", "", -2, 30.0);
		AddNpc(10, 147415, "Sentinel Woman 2", "f_rokas_24", 1138.0, 201.0, 998.0, 16.0, "ROKAS24_MIRTA", "", "", -2, 30.0);
		AddNpc(11, 147425, "Florijonas", "f_rokas_24", -985.0, 782.0, -3361.0, 0.0, "ROKAS_24_FLORIJONAS", "", "", -2, 35.0);
		AddNpc(12, 147425, "Florijonas", "f_rokas_24", -484.0, 725.0, -1777.0, -90.0, "ROKAS_24_FLORIJONAS2", "", "", -2, 35.0);
		AddNpc(13, 147425, "Florijonas", "f_rokas_24", -745.0, 1125.0, 216.0, 0.0, "ROKAS_24_FLORIJONAS3", "", "", -2, 35.0);
		AddNpc(14, 147475, "Tomb Mini Cube", "f_rokas_24", -695.0, 1125.0, 264.0, -76.0, "ROKAS24_DEVICE_1", "", "", -2, 50.0);
		AddNpc(15, 20041, "", "f_rokas_24", 832.0, 124.0, -1235.0, 0.0, "", "ROKAS24_QB_10_TRIGGER", "", -2, 200.0);
		AddNpc(16, 20041, "", "f_rokas_24", -710.0, 724.0, -2104.0, 0.0, "", "ROKAS24_QB_11_TRIGGER", "", -2, 200.0);
		AddNpc(17, 47102, "Canyon Area Device 1", "f_rokas_24", 1188.0, 201.0, 1014.0, 0.0, "ROKAS24_DEVICE_2", "", "", -2, 50.0);
		AddNpc(19, 20026, "", "f_rokas_24", -469.0, 724.0, -1806.0, 0.0, "", "ROKAS24_QB_4_TRIGGER", "", -2, 180.0);
		AddNpc(24, 20154, "Gentleman 8", "f_rokas_24", 955.0, 124.0, -1829.0, -90.0, "ROKAS24_DABIO", "", "", -2, 35.0);
		AddNpc(25, 147425, "Florijonas", "f_rokas_24", 603.0, 238.0, -1883.0, -90.0, "ROKAS_24_FLORIJONAS4", "", "", -2, 35.0);
		AddNpc(26, 47201, "Discolored Grass Of Siauliai", "f_rokas_24", 1775.790039, 16.67, -336.790009, 0.0, "ROKAS24_FORSYTHIA", "", "", -2, 35.0);
		AddNpc(26, 47201, "Discolored Grass Of Siauliai", "f_rokas_24", 1587.530029, 16.700001, -426.76001, 0.0, "ROKAS24_FORSYTHIA", "", "", -2, 35.0);
		AddNpc(26, 47201, "Discolored Grass Of Siauliai", "f_rokas_24", 1702.650024, 16.700001, -401.119995, 0.0, "ROKAS24_FORSYTHIA", "", "", -2, 35.0);
		AddNpc(26, 47201, "Discolored Grass Of Siauliai", "f_rokas_24", 1709.780029, 16.639999, -213.830002, 0.0, "ROKAS24_FORSYTHIA", "", "", -2, 35.0);
		AddNpc(26, 47201, "Discolored Grass Of Siauliai", "f_rokas_24", 1687.290039, 16.629999, -308.76001, 0.0, "ROKAS24_FORSYTHIA", "", "", -2, 35.0);
		AddNpc(26, 47201, "Discolored Grass Of Siauliai", "f_rokas_24", 1277.189941, 123.93, -867.330017, 0.0, "ROKAS24_FORSYTHIA", "", "", -2, 35.0);
		AddNpc(26, 47201, "Discolored Grass Of Siauliai", "f_rokas_24", 1136.530029, 123.93, -659.539978, 0.0, "ROKAS24_FORSYTHIA", "", "", -2, 35.0);
		AddNpc(26, 47201, "Discolored Grass Of Siauliai", "f_rokas_24", 1647.199951, 16.309999, -53.799999, 0.0, "ROKAS24_FORSYTHIA", "", "", -2, 35.0);
		AddNpc(26, 47201, "Discolored Grass Of Siauliai", "f_rokas_24", 1233.73999, 123.93, -986.460022, 0.0, "ROKAS24_FORSYTHIA", "", "", -2, 35.0);
		AddNpc(26, 47201, "Discolored Grass Of Siauliai", "f_rokas_24", 1049.48999, 123.93, -480.049988, 0.0, "ROKAS24_FORSYTHIA", "", "", -2, 35.0);
		AddNpc(26, 47201, "Discolored Grass Of Siauliai", "f_rokas_24", 1723.829956, 15.44, -19.84, 0.0, "ROKAS24_FORSYTHIA", "", "", -2, 35.0);
		AddNpc(26, 47201, "Discolored Grass Of Siauliai", "f_rokas_24", 1666.550049, 16.209999, -132.600006, 0.0, "ROKAS24_FORSYTHIA", "", "", -2, 35.0);
		AddNpc(26, 47201, "Discolored Grass Of Siauliai", "f_rokas_24", 1548.72998, 16.66, -301.850006, 0.0, "ROKAS24_FORSYTHIA", "", "", -2, 35.0);
		AddNpc(27, 47160, "Lost Stuff Of Vendor 1", "f_rokas_24", 739.0, 261.0, 881.0, 0.0, "ROKAS24_SUPP_01", "", "", -2, 35.0);
		AddNpc(27, 47160, "Lost Stuff Of Vendor 1", "f_rokas_24", 777.0, 261.0, 1037.0, 0.0, "ROKAS24_SUPP_01", "", "", -2, 35.0);
		AddNpc(27, 47160, "Lost Stuff Of Vendor 1", "f_rokas_24", 796.0, 261.0, 1093.0, 0.0, "ROKAS24_SUPP_01", "", "", -2, 35.0);
		AddNpc(27, 47160, "Lost Stuff Of Vendor 1", "f_rokas_24", 853.697998, 201.952911, 252.771164, 0.0, "ROKAS24_SUPP_01", "", "", -2, 35.0);
		AddNpc(27, 47160, "Lost Stuff Of Vendor 1", "f_rokas_24", 994.890381, 178.861786, 13.509394, 0.0, "ROKAS24_SUPP_01", "", "", -2, 35.0);
		AddNpc(27, 47160, "Lost Stuff Of Vendor 1", "f_rokas_24", 840.72168, 261.21637, 681.498474, 0.0, "ROKAS24_SUPP_01", "", "", -2, 35.0);
		AddNpc(27, 47160, "Lost Stuff Of Vendor 1", "f_rokas_24", 485.929443, 261.216553, 722.238464, 0.0, "ROKAS24_SUPP_01", "", "", -2, 35.0);
		AddNpc(27, 47160, "Lost Stuff Of Vendor 1", "f_rokas_24", 461.064178, 261.212921, 453.577332, 0.0, "ROKAS24_SUPP_01", "", "", -2, 35.0);
		AddNpc(27, 47160, "Lost Stuff Of Vendor 1", "f_rokas_24", 931.049866, 201.955475, 532.484924, 0.0, "ROKAS24_SUPP_01", "", "", -2, 35.0);
		AddNpc(27, 47160, "Lost Stuff Of Vendor 1", "f_rokas_24", 1002.021179, 201.954666, 373.630737, 0.0, "ROKAS24_SUPP_01", "", "", -2, 35.0);
		AddNpc(27, 47160, "Lost Stuff Of Vendor 1", "f_rokas_24", 1093.192505, 194.202759, 138.45932, 0.0, "ROKAS24_SUPP_01", "", "", -2, 35.0);
		AddNpc(27, 47160, "Lost Stuff Of Vendor 1", "f_rokas_24", 714.955566, 261.212646, 328.480652, 0.0, "ROKAS24_SUPP_01", "", "", -2, 35.0);
		AddNpc(27, 47160, "Lost Stuff Of Vendor 1", "f_rokas_24", 782.817566, 189.712769, 81.280525, 0.0, "ROKAS24_SUPP_01", "", "", -2, 35.0);
		AddNpc(27, 47160, "Lost Stuff Of Vendor 1", "f_rokas_24", 1216.048706, 201.956604, 428.899689, 0.0, "ROKAS24_SUPP_01", "", "", -2, 35.0);
		AddNpc(28, 20026, "", "f_rokas_24", -1290.0, 895.0, -1310.0, -90.0, "", "ROKAS24_QB_9", "", -2, 240.0);
		AddNpc(29, 155067, "Rodelero Submaster", "f_rokas_24", 1088.881226, 123.926804, -1882.80481, -90.0, "JOB_RODELERO3_1_NPC", "", "", -2, 30.0);
		AddNpc(30, 155068, "Cataphract Submaster", "f_rokas_24", 487.185059, 123.926598, -2265.154053, 0.0, "MASTER_CATAPHRACT", "", "", -2, 1.0);
		AddNpc(31, 147435, "Thaumaturge Master", "f_rokas_24", 520.583618, 123.926567, -2178.955078, 0.0, "JOB_THAUMATURGE3_1_NPC", "", "", -2, 30.0);
		AddNpc(32, 57234, "Scout Master", "f_rokas_24", 578.659485, 238.931198, -1665.211548, -90.0, "JOB_SCOUT3_1_NPC", "", "", -2, 30.0);
		AddNpc(33, 155081, "Wugushi Submaster", "f_rokas_24", 480.510712, 238.931198, -1726.218994, 0.0, "JOB_WUGU3_1_NPC", "", "", -2, 30.0);
		AddNpc(602, 20109, "Veteran Miner", "f_rokas_24", 596.0, 123.0, -2326.0, -90.0, "ROKAS_24_NEWCOMER", "", "", -2, 0.0);
		AddNpc(603, 20109, "Veteran Miner", "f_rokas_24", 443.73999, 123.93, -604.909973, -90.0, "ROKAS_24_PHARMACIST", "", "", -2, 0.0);
		AddNpc(605, 20117, "Armand", "f_rokas_24", -1468.0, 895.0, -1328.0, 0.0, "ROKAS_24_GORATH", "", "", -2, 0.0);
		AddNpc(614, 20109, "Veteran Miner", "f_rokas_24", -574.0, 886.0, -770.0, -90.0, "ROKAS_24_ARCHAEOLOGIST", "", "", -2, 35.0);
		AddNpc(618, 20042, "", "f_rokas_24", -491.0, 687.0, 1973.0, 0.0, "", "ROKAS_24_RELIC_TRIGGERGO", "", -2, 50.0);
		AddNpc(619, 20109, "Veteran Miner", "f_rokas_24", 478.0, 163.0, -2085.0, 0.0, "ROKAS24_PIPOTI", "", "", -2, 35.0);
		AddNpc(620, 20125, "Mid Commander (Male 2)", "f_rokas_24", 640.0, 123.0, -2123.0, 0.0, "ROKAS24_ALCHEMIST", "", "", -2, 35.0);
		AddNpc(621, 47258, "Jar", "f_rokas_24", -1520.0, 895.0, -1531.0, 89.0, "ROKAS24_BOX1", "", "", -2, 30.0);
		AddNpc(621, 47258, "Jar", "f_rokas_24", -1221.0, 895.0, -1522.0, 89.0, "ROKAS24_BOX1", "", "", -2, 30.0);
		AddNpc(621, 47258, "Jar", "f_rokas_24", -1699.0, 895.0, -1201.0, 89.0, "ROKAS24_BOX1", "", "", -2, 30.0);
		AddNpc(621, 47258, "Jar", "f_rokas_24", -1515.0, 895.0, -994.0, 89.0, "ROKAS24_BOX1", "", "", -2, 30.0);
		AddNpc(621, 47258, "Jar", "f_rokas_24", -1398.0, 895.0, -1079.0, 89.0, "ROKAS24_BOX1", "", "", -2, 30.0);
		AddNpc(622, 20041, "", "f_rokas_24", 230.0, 590.0, 1365.0, 0.0, "", "ROKAS24_MQ_2TRACK", "", -2, 100.0);
		AddNpc(626, 147469, "No Shadow Npc", "f_rokas_24", 1155.0, 123.0, -1979.0, -45.0, "ROKAS_24_PORTAL", "", "", -2, 40.0);
		AddNpc(702, 20042, "", "f_rokas_24", -2731.852051, 1341.92395, -427.302307, 0.0, "", "ROKAS_24_BEACON_TRIGGERGO", "", -2, 50.0);
		AddNpc(703, 40070, "Bulletin Board", "f_rokas_24", 754.0, 124.0, -2075.0, -45.0, "ROKAS24_BOARD", "", "", -2, 50.0);
		AddNpc(707, 47200, "Discolored Grass Of Siauliai", "f_rokas_24", -146.105026, 594.219421, 1559.775635, 0.0, "ROKAS24_MQFLOWER", "", "", -2, 40.0);
		AddNpc(707, 47200, "Discolored Grass Of Siauliai", "f_rokas_24", -398.47644, 594.219421, 1199.003418, 0.0, "ROKAS24_MQFLOWER", "", "", -2, 40.0);
		AddNpc(707, 47200, "Discolored Grass Of Siauliai", "f_rokas_24", -130.43222, 594.207275, 1105.328613, 0.0, "ROKAS24_MQFLOWER", "", "", -2, 40.0);
		AddNpc(707, 47200, "Discolored Grass Of Siauliai", "f_rokas_24", -459.319763, 601.625305, 1448.075439, 0.0, "ROKAS24_MQFLOWER", "", "", -2, 40.0);
		AddNpc(707, 47200, "Discolored Grass Of Siauliai", "f_rokas_24", 140.040146, 591.753235, 1243.411865, 0.0, "ROKAS24_MQFLOWER", "", "", -2, 40.0);
		AddNpc(708, 147468, "Beacon", "f_rokas_24", -2958.14917, 1341.998901, -565.732849, -90.0, "", "ROKAS_24_BEACON_REAL", "", -2, 50.0);
		AddNpc(709, 20158, "Gentleman 12", "f_rokas_24", 1550.67041, 16.639208, -87.887154, 0.0, "ROKAS_24_BEARD_AFTER", "", "", -2, 40.0);
		AddNpc(710, 40070, "Bulletin Board", "f_rokas_24", 821.398315, 123.866829, -2989.329346, 0.0, "UPPER_WARNING_F_ROKAS_24", "", "", -2, 40.0);
		AddNpc(711, 20026, "", "f_rokas_24", 778.723816, 123.926697, -1217.161011, 0.0, "", "ROKAS_24_JOB_SPARRING_TRIGGER", "", -2, 100.0);
		AddNpc(727, 147392, "Treasure Box 1", "f_rokas_24", -677.849976, 724.390015, -2528.0, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(729, 20139, "Pablo", "f_rokas_24", -1592.777588, 1334.011841, 53.186798, -109.0, "ROKAS24_RP_2_NPC", "", "", -2, 40.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", -2114.673584, 1334.028198, -266.321442, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", -1701.32959, 1334.02832, -197.873871, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", -1989.248657, 1334.02832, 108.027771, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", -2166.124023, 1334.028076, -30.55168, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", -2291.869873, 1334.028442, -244.506699, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", -3057.812256, 1341.92395, -548.290283, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", -2856.678467, 1341.934326, -615.985168, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", -954.319824, 1125.389893, -318.311768, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", -676.268555, 1125.389893, -573.499756, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", -346.775482, 1125.389893, -488.858521, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", -731.957642, 1125.389893, 163.692902, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", -889.731201, 1125.389893, 9.140024, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", -354.726532, 1125.389893, 181.027481, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", -492.734467, 1125.389893, -170.585373, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", -704.136658, 1125.389893, -271.184631, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", -170.317749, 1125.389893, 37.310577, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", 125.526314, 1125.389893, -9.773265, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", 55.095028, 1125.389893, -204.590424, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", -108.329643, 1125.389893, -157.042755, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", -483.380219, 1125.389893, 68.816559, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", -1807.341797, 1334.020508, 177.388107, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", -1822.938599, 1334.02832, 50.62574, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", -1708.907715, 1334.02832, 6.836369, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", -2279.5354, 1334.028076, 42.232861, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(730, 155026, "Valley Area Soil", "f_rokas_24", -2172.895264, 1334.494995, -176.606598, 0.0, "ROKAS24_RP_2_OBJ", "", "", -2, 1.0);
		AddNpc(731, 152078, "Teleport Magic Circle (Mini)", "f_rokas_24", 948.940002, 123.93, -2356.209961, 0.0, "HT2_MOVING_DEVICES01", "", "", -2, 5.0);
		AddNpc(732, 152078, "Teleport Magic Circle (Mini)", "f_rokas_24", -889.799988, 724.289978, -2614.560059, 0.0, "HT2_MOVING_DEVICES02", "", "", -2, 5.0);
		AddNpc(733, 152078, "Teleport Magic Circle (Mini)", "f_rokas_24", 276.230011, 1125.390015, -136.350006, 0.0, "HT2_MOVING_DEVICES03", "", "", -2, 5.0);
		AddNpc(734, 152078, "Teleport Magic Circle (Mini)", "f_rokas_24", -2312.189941, 1334.599976, -94.529999, 0.0, "HT2_MOVING_DEVICES04", "", "", -2, 5.0);
		AddNpc(735, 152078, "Teleport Magic Circle (Mini)", "f_rokas_24", 1057.825195, 172.880005, -46.416046, 0.0, "HT2_MOVING_DEVICES05", "", "", -2, 5.0);
		AddNpc(736, 152078, "Teleport Magic Circle (Mini)", "f_rokas_24", -743.080017, 689.440002, 1397.969971, 0.0, "HT2_MOVING_DEVICES06", "", "", -2, 5.0);
		AddNpc(737, 152078, "Teleport Magic Circle (Mini)", "f_rokas_24", -1547.160034, 892.969971, 2258.580078, 0.0, "HT2_MOVING_DEVICES07", "", "", -2, 5.0);
		AddNpc(738, 40095, "", "f_rokas_24", -1877.992432, 933.192871, 1867.002686, 0.0, "", "EXPLORER_MISLE26", "", -2, 20.0);
	}
}
