// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_siauliai_46_3 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(7, 147477, "Beekeeper2", "f_siauliai_46_3", -568.398132, 134.308807, 488.613281, -90.0, "SIAULIAI_46_3_MQ01_NPC", "", "", -2, 40.0);
		AddNpc(8, 147482, "Livia", "f_siauliai_46_3", -651.418213, 134.308807, 478.424561, -45.0, "SIAULIAI_46_3_SQ_03_NPC", "", "", -2, 40.0);
		AddNpc(9, 151024, "Austeja Altar", "f_siauliai_46_3", 777.242249, 54.1763, -647.75, 180.0, "SIAULIAI_46_3_AUSTEJA_ALTAR_01", "SIAULIAI_46_3_AUSTEJA_ALTAR_01", "", -2, 250.0);
		AddNpc(10, 151024, "Austeja Altar", "f_siauliai_46_3", 358.0, 25.0, 1513.0, 1.0, "SIAULIAI_46_3_AUSTEJA_ALTAR_02", "", "", -2, 40.0);
		AddNpc(11, 147499, "Research Leader", "f_siauliai_46_3", 1878.782471, 134.308807, 856.356689, 1.0, "SIAULIAI_46_3_MQ05_NPC", "", "", -2, 40.0);
		AddNpc(12, 147484, "Brindle", "f_siauliai_46_3", 1902.068359, 134.308807, 604.4552, 1.0, "SIAULIAI_46_3_SQ_02_NPC", "", "", -2, 40.0);
		AddNpc(13, 40095, "", "f_siauliai_46_3", 1502.153076, 24.313499, 1573.55835, 0.0, "SIAULIAI_46_3_SQ_04_FARM", "", "", -2, 40.0);
		AddNpc(13, 40095, "", "f_siauliai_46_3", 1520.337402, 24.313499, 1502.058472, 0.0, "SIAULIAI_46_3_SQ_04_FARM", "", "", -2, 40.0);
		AddNpc(13, 40095, "", "f_siauliai_46_3", 1691.746704, 24.313499, 1474.497925, 0.0, "SIAULIAI_46_3_SQ_04_FARM", "", "", -2, 40.0);
		AddNpc(13, 40095, "", "f_siauliai_46_3", 1686.255371, 24.313499, 1547.950195, 0.0, "SIAULIAI_46_3_SQ_04_FARM", "", "", -2, 40.0);
		AddNpc(14, 151025, "Bee Hive", "f_siauliai_46_3", -409.00769, 196.7332, 1778.231689, -90.0, "SIAULIAI_46_3_BEEHIVE", "", "", -2, 40.0);
		AddNpc(14, 151025, "Bee Hive", "f_siauliai_46_3", -601.892883, 196.7332, 1483.20813, -45.0, "SIAULIAI_46_3_BEEHIVE", "", "", -2, 40.0);
		AddNpc(14, 151025, "Bee Hive", "f_siauliai_46_3", -99.319916, 196.7332, 1636.911011, -125.0, "SIAULIAI_46_3_BEEHIVE", "", "", -2, 40.0);
		AddNpc(14, 151025, "Bee Hive", "f_siauliai_46_3", -243.532715, 196.7332, 1387.973755, 90.0, "SIAULIAI_46_3_BEEHIVE", "", "", -2, 40.0);
		AddNpc(15, 47161, "Lost Stuff Of Vendor 2", "f_siauliai_46_3", 3588.0, 211.0, 1212.0, 1.0, "SIAULIAI_46_3_SQ_02_KIT", "", "", -2, 40.0);
		AddNpc(16, 20156, "Gentleman 10", "f_siauliai_46_3", -654.24408, 134.308807, 330.710449, 1.0, "SIAULIAI_46_3_INV_NPC_01", "", "", -2, 40.0);
		AddNpc(17, 20157, "Gentleman 11", "f_siauliai_46_3", -420.979828, 134.308807, 409.580048, 180.0, "SIAULIAI_46_3_INV_NPC_02", "", "", -2, 40.0);
		AddNpc(23, 147392, "Treasure Box 1", "f_siauliai_46_3", 2357.719971, 202.210007, -360.429993, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(1002, 20026, "", "f_siauliai_46_3", 2151.731445, 134.308823, 1103.345825, 0.0, "", "CHAR312_MSTEP1_GEN_INIT", "", -2, 40.0);
	}
}
