// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_siauliai_46_4 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(9, 147407, "Seven Valley Man 1", "f_siauliai_46_4", -227.360001, 148.220001, -960.280029, -90.0, "SIAULIAI_46_4_MQ01_NPC", "", "", -2, 40.0);
		AddNpc(10, 147418, "Seven Valley Woman 1", "f_siauliai_46_4", -260.579987, 148.220001, -979.75, -30.0, "SIAULIAI_46_4_SQ03_NPC", "", "", -2, 40.0);
		AddNpc(11, 151025, "Bee Hive", "f_siauliai_46_4", 1370.0, 149.0, -695.0, -60.0, "SIAULIAI_46_4_BEEHIVE01", "", "", -2, 40.0);
		AddNpc(12, 147459, "Small Drums", "f_siauliai_46_4", 351.820007, 188.559998, 32.09, 0.0, "SIAULIAI_46_4_MEADBARREL", "", "", -2, 40.0);
		AddNpc(12, 147459, "Small Drums", "f_siauliai_46_4", 108.032227, 188.559006, 56.712753, 0.0, "SIAULIAI_46_4_MEADBARREL", "", "", -2, 40.0);
		AddNpc(12, 147459, "Small Drums", "f_siauliai_46_4", 19.904776, 188.559006, -153.51178, 0.0, "SIAULIAI_46_4_MEADBARREL", "", "", -2, 40.0);
		AddNpc(12, 147459, "Small Drums", "f_siauliai_46_4", 588.340515, 188.559006, -214.494293, 0.0, "SIAULIAI_46_4_MEADBARREL", "", "", -2, 40.0);
		AddNpc(12, 147459, "Small Drums", "f_siauliai_46_4", 286.48996, 188.559006, -414.264496, 0.0, "SIAULIAI_46_4_MEADBARREL", "", "", -2, 40.0);
		AddNpc(12, 147459, "Small Drums", "f_siauliai_46_4", 991.85498, 188.559006, -351.391907, 0.0, "SIAULIAI_46_4_MEADBARREL", "", "", -2, 40.0);
		AddNpc(13, 46212, "Box", "f_siauliai_46_4", 1172.812744, 121.370903, 2575.272217, 90.0, "SIAULIAI_46_4_MEADBOX", "", "", -2, 40.0);
		AddNpc(14, 147476, "Beekeeper1", "f_siauliai_46_4", 1074.290039, 224.979996, 482.619995, -45.0, "SIAULIAI_46_4_MQ04_NPC", "", "", -2, 40.0);
		AddNpc(15, 147483, "Liora", "f_siauliai_46_4", 1343.829956, 224.979996, 388.26001, -90.0, "SIAULIAI_46_4_SQ04_NPC01", "", "", -2, 40.0);
		AddNpc(16, 147485, "Erya", "f_siauliai_46_4", 1093.219971, 224.979996, 791.719971, 1.0, "SIAULIAI_46_4_SQ04_NPC02", "", "", -2, 40.0);
		AddNpc(18, 20026, "", "f_siauliai_46_4", 507.690002, 148.220001, -684.619995, 0.0, "", "SIAULIAI_46_4_MQ02_TRIGGER", "", -2, 80.0);
		AddNpc(18, 20026, "", "f_siauliai_46_4", 24.27, 148.220001, -950.840027, 0.0, "", "SIAULIAI_46_4_MQ02_TRIGGER", "", -2, 80.0);
		AddNpc(18, 20026, "", "f_siauliai_46_4", 276.209991, 148.220001, -750.159973, 0.0, "", "SIAULIAI_46_4_MQ02_TRIGGER", "", -2, 80.0);
		AddNpc(18, 20026, "", "f_siauliai_46_4", 347.26001, 188.559998, -398.459991, 0.0, "", "SIAULIAI_46_4_MQ02_TRIGGER", "", -2, 80.0);
		AddNpc(18, 20026, "", "f_siauliai_46_4", 295.0, 148.220001, -1026.140015, 0.0, "", "SIAULIAI_46_4_MQ02_TRIGGER", "", -2, 80.0);
		AddNpc(18, 20026, "", "f_siauliai_46_4", 764.5, 148.220001, -720.289978, 0.0, "", "SIAULIAI_46_4_MQ02_TRIGGER", "", -2, 80.0);
		AddNpc(19, 151029, "Pile Of Boxes 01", "f_siauliai_46_4", 1137.611084, 121.370903, 2579.109619, 45.0, "", "", "", -2, 40.0);
		AddNpc(19, 151029, "Pile Of Boxes 01", "f_siauliai_46_4", 1105.372803, 121.370903, 2578.739746, 90.0, "", "", "", -2, 40.0);
		AddNpc(19, 151029, "Pile Of Boxes 01", "f_siauliai_46_4", 1165.282593, 121.370903, 2611.71582, 10.0, "", "", "", -2, 40.0);
		AddNpc(20, 151025, "Bee Hive", "f_siauliai_46_4", 1416.843994, 148.224106, -573.263245, -75.0, "", "", "", -2, 40.0);
		AddNpc(20, 151025, "Bee Hive", "f_siauliai_46_4", 1385.861572, 148.224106, -635.291931, -60.0, "", "", "", -2, 40.0);
		AddNpc(20, 151025, "Bee Hive", "f_siauliai_46_4", 1424.089233, 148.224106, -645.326782, -30.0, "", "", "", -2, 40.0);
		AddNpc(20, 151025, "Bee Hive", "f_siauliai_46_4", 1405.523926, 148.224106, -670.516418, -90.0, "", "", "", -2, 40.0);
		AddNpc(20, 151025, "Bee Hive", "f_siauliai_46_4", 1431.851685, 148.224106, -717.307007, -45.0, "", "", "", -2, 40.0);
		AddNpc(20, 151025, "Bee Hive", "f_siauliai_46_4", 1438.725098, 148.22406, -754.693787, 15.0, "", "", "", -2, 40.0);
		AddNpc(20, 151025, "Bee Hive", "f_siauliai_46_4", 1434.111206, 148.224014, -794.056335, -30.0, "", "", "", -2, 40.0);
		AddNpc(20, 151025, "Bee Hive", "f_siauliai_46_4", 1416.726563, 148.22403, -762.266479, 0.0, "", "", "", -2, 40.0);
		AddNpc(34, 147392, "Treasure Box 1", "f_siauliai_46_4", 1459.060059, 188.660004, -121.230003, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(38, 147507, "Npc Hunting Grounds Entrance", "f_siauliai_46_4", 1312.0, 188.0, -221.0, 0.0, "SIAULIAI_46_4_TO_STARTOWER_76_1", "", "", -2, 20.0);
		AddNpc(39, 20026, "", "f_siauliai_46_4", 290.48999, 148.220001, -797.580017, 0.0, "", "SIAULIAI462_HIDDENQ1_IN", "", -2, 300.0);
		AddNpc(40, 20024, "", "f_siauliai_46_4", 933.909973, 148.220001, -898.119995, 0.0, "SIAULIAI462_HIDDENQ2_CANDLE1", "", "", -2, 40.0);
		AddNpc(41, 20024, "", "f_siauliai_46_4", 1111.569946, 148.220001, -535.890015, 0.0, "SIAULIAI462_HIDDENQ2_CANDLE2", "", "", -2, 40.0);
		AddNpc(42, 20024, "", "f_siauliai_46_4", 1403.897095, 148.220001, -987.40625, 0.0, "SIAULIAI462_HIDDENQ2_CANDLE3", "", "", -2, 40.0);
		AddNpc(43, 153178, "Scented Candle", "f_siauliai_46_4", 935.070007, 148.220001, -896.679993, 0.0, "", "SIAULIAI462_CANDLE1", "", -2, 40.0);
		AddNpc(44, 153178, "Scented Candle", "f_siauliai_46_4", 1112.262573, 148.220001, -534.490295, 0.0, "", "SIAULIAI462_CANDLE2", "", -2, 40.0);
		AddNpc(45, 153178, "Scented Candle", "f_siauliai_46_4", 1404.133911, 148.220001, -988.26178, 0.0, "", "SIAULIAI462_CANDLE3", "", -2, 40.0);
		AddNpc(46, 147459, "Small Drums", "f_siauliai_46_4", 1101.219971, 121.370003, 2704.669922, 0.0, "HT3_SIAULIAI_46_4_DRUM", "", "", -2, 5.0);
		AddNpc(47, 40080, "Warning", "f_siauliai_46_4", 1145.088745, 188.580002, -225.981705, 140.0, "FREE_DUNGEON_SIGN2", "", "", -2, 40.0);
		AddNpc(48, 20147, "Helena", "f_siauliai_46_4", 1134.69458, 224.9785, 909.677063, 0.0, "CHAR120_MSTEP5_5_NPC1", "", "", -2, 40.0);
	}
}
