// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_siauliai_15_re : GeneralScript
{
	protected override void Load()
	{
		AddNpc(3, 20059, "Orsha Soldier Female", "f_siauliai_15_re", 3095.083984, 878.172119, 99.482742, -13.0, "SIAULIAI15RE_CHERASIA", "", "", -2, 1.0);
		AddNpc(4, 20060, "Orsha Soldier Male", "f_siauliai_15_re", 359.785858, 878.228394, -132.583298, 161.0, "SIAULIAI15RE_MOREN", "", "", -2, 1.0);
		AddNpc(5, 147406, "Paladin Follower B4", "f_siauliai_15_re", -2625.064453, 741.856323, -66.995323, -100.0, "SIAULIAI15RE_YEULIS", "", "", -2, 1.0);
		AddNpc(7, 147421, "Paladin Follower No Instrument C1", "f_siauliai_15_re", 1318.292236, 878.171936, 391.313568, -26.0, "SIAULIAI15RE_RIGITESS", "", "", -2, 40.0);
		AddNpc(8, 20060, "Orsha Soldier Male", "f_siauliai_15_re", 2356.711914, 878.172119, -1051.376343, -83.0, "SIAULIAI15RE_FERNIFF", "", "", -2, 40.0);
		AddNpc(9, 147404, "Paladin Follower B2", "f_siauliai_15_re", -5.042915, 1101.666504, -2246.311768, -91.0, "SIAULIAI15RE_GERMEYA", "", "", -2, 40.0);
		AddNpc(300, 155087, "Dievdirbys Submaster", "f_siauliai_15_re", 713.708618, 878.171875, 115.963478, -49.0, "JOB_2_DIEVDIRBYS_NPC", "", "", -2, 40.0);
		AddNpc(302, 147375, "Siauliai Tent", "f_siauliai_15_re", -3078.28125, 864.417114, 744.791992, 0.0, "", "", "", -2, 1.0);
		AddNpc(303, 154060, "Bonfireq1", "f_siauliai_15_re", -2916.660889, 864.417114, 812.877319, 0.0, "", "", "", -2, 1.0);
		AddNpc(303, 154060, "Bonfireq1", "f_siauliai_15_re", 337.684052, 878.22522, -126.84671, 0.0, "", "", "", -2, 1.0);
		AddNpc(304, 147322, "Treasure Chest Siauliai", "f_siauliai_15_re", -3040.687012, 864.417114, 818.226807, -30.0, "", "", "", -2, 1.0);
		AddNpc(305, 147312, "Dropped Paper", "f_siauliai_15_re", -3007.419922, 864.419983, 905.02002, -103.0, "SIAU15RE_MQ_05_ITEM", "", "", -2, 40.0);
		AddNpc(307, 20026, "", "f_siauliai_15_re", -2893.043945, 837.661072, 414.374268, 0.0, "", "SIAU15RE_MQ_05_NPC", "", -2, 80.0);
		AddNpc(308, 45313, "Kepa Wagon", "f_siauliai_15_re", 1918.806274, 878.171143, -1444.302734, 139.0, "SIAU15RE_SQ_02_NPC", "SIAU15RE_SQ_02_NPC_MSG", "", -2, 50.0);
		AddNpc(309, 45312, "Kepa Wagon", "f_siauliai_15_re", 1838.494019, 878.093506, -1711.987427, -121.0, "SIAU15RE_SQ_02_NPC", "SIAU15RE_SQ_02_NPC_MSG", "", -2, 50.0);
		AddNpc(309, 45312, "Kepa Wagon", "f_siauliai_15_re", 1861.468018, 877.950073, -2060.063477, -105.0, "SIAU15RE_SQ_02_NPC", "SIAU15RE_SQ_02_NPC_MSG", "", -2, 50.0);
		AddNpc(309, 45312, "Kepa Wagon", "f_siauliai_15_re", 2174.896973, 877.851013, -2170.481445, -126.0, "SIAU15RE_SQ_02_NPC", "SIAU15RE_SQ_02_NPC_MSG", "", -2, 50.0);
		AddNpc(310, 45311, "Kepa Wagon", "f_siauliai_15_re", 2279.441895, 877.884033, -1912.464355, -86.0, "SIAU15RE_SQ_02_NPC", "SIAU15RE_SQ_02_NPC_MSG", "", -2, 50.0);
		AddNpc(310, 45311, "Kepa Wagon", "f_siauliai_15_re", 2260.116699, 878.104919, -1601.96936, 93.0, "SIAU15RE_SQ_02_NPC", "SIAU15RE_SQ_02_NPC_MSG", "", -2, 50.0);
		AddNpc(310, 45311, "Kepa Wagon", "f_siauliai_15_re", 2571.773193, 878.172119, -1315.728882, 132.0, "SIAU15RE_SQ_02_NPC", "SIAU15RE_SQ_02_NPC_MSG", "", -2, 50.0);
		AddNpc(310, 45311, "Kepa Wagon", "f_siauliai_15_re", 2192.242188, 878.172119, -665.255737, 88.0, "SIAU15RE_SQ_02_NPC", "SIAU15RE_SQ_02_NPC_MSG", "", -2, 50.0);
		AddNpc(311, 45311, "Kepa Wagon", "f_siauliai_15_re", 1854.747437, 878.172119, -1276.157959, -93.0, "SIAU15RE_SQ_02_NPC", "SIAU15RE_SQ_02_NPC_MSG", "", -2, 50.0);
		AddNpc(311, 45311, "Kepa Wagon", "f_siauliai_15_re", 1921.691772, 878.172119, -1013.467529, -120.0, "SIAU15RE_SQ_02_NPC", "SIAU15RE_SQ_02_NPC_MSG", "", -2, 50.0);
		AddNpc(313, 47204, "Siauliai Discolored Grass4", "f_siauliai_15_re", -1135.920044, 922.76001, 1290.130005, 0.0, "", "SIAU15RE_SQ_05_PROP", "", -2, 1.0);
		AddNpc(313, 47204, "Siauliai Discolored Grass4", "f_siauliai_15_re", -1186.550049, 922.76001, 1299.599976, 0.0, "", "SIAU15RE_SQ_05_PROP", "", -2, 1.0);
		AddNpc(313, 47204, "Siauliai Discolored Grass4", "f_siauliai_15_re", -1181.76001, 922.76001, 1323.290039, 0.0, "", "SIAU15RE_SQ_05_PROP", "", -2, 1.0);
		AddNpc(313, 47204, "Siauliai Discolored Grass4", "f_siauliai_15_re", -1132.400024, 922.76001, 1350.079956, 0.0, "", "SIAU15RE_SQ_05_PROP", "", -2, 1.0);
		AddNpc(313, 47204, "Siauliai Discolored Grass4", "f_siauliai_15_re", -1101.170044, 922.76001, 1328.400024, 0.0, "", "SIAU15RE_SQ_05_PROP", "", -2, 1.0);
		AddNpc(313, 47204, "Siauliai Discolored Grass4", "f_siauliai_15_re", -1064.640015, 922.76001, 1283.660034, 0.0, "", "SIAU15RE_SQ_05_PROP", "", -2, 1.0);
		AddNpc(313, 47204, "Siauliai Discolored Grass4", "f_siauliai_15_re", -1054.51001, 922.76001, 1322.530029, 0.0, "", "SIAU15RE_SQ_05_PROP", "", -2, 1.0);
		AddNpc(313, 47204, "Siauliai Discolored Grass4", "f_siauliai_15_re", -1107.339966, 922.76001, 1354.48999, 0.0, "", "SIAU15RE_SQ_05_PROP", "", -2, 1.0);
		AddNpc(320, 147375, "Siauliai Tent", "f_siauliai_15_re", -3011.199951, 864.417114, 913.909912, -45.0, "", "SIAU15RE_MQ_05_TENT", "", -2, 1.0);
		AddNpc(325, 147392, "Treasure Box 1", "f_siauliai_15_re", 1575.0, 878.0, 435.0, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(326, 147392, "Treasure Box 1", "f_siauliai_15_re", 463.579987, 922.859985, 1401.5, 45.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(900, 147507, "Npc Hunting Grounds Entrance", "f_siauliai_15_re", -515.0, 1015.0, 2119.0, 0.0, "SIAULIAI_15_RE_TO_ZACHARIEL_79_1", "", "", -2, 20.0);
		AddNpc(901, 40080, "Warning", "f_siauliai_15_re", -498.0, 1015.0, 2165.0, 0.0, "FREE_DUNGEON_SIGN6", "", "", -2, 40.0);
		AddNpc(902, 40095, "", "f_siauliai_15_re", -825.826172, 922.763, 1253.805786, 0.0, "", "EXPLORER_MISLE12", "", -2, 20.0);
	}
}
