// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_siauliai_11_re : GeneralScript
{
	protected override void Load()
	{
		AddNpc(5, 147399, "Paladin Follower A2", "f_siauliai_11_re", 2324.01001, 171.9151, -643.349243, 0.0, "SIAULIAI11RE_TALBASI", "", "", -2, 1.0);
		AddNpc(6, 147400, "Paladin Follower A3", "f_siauliai_11_re", -227.377747, 84.886703, 365.471924, -81.0, "SIAULIAI11RE_SENDAL", "", "", -2, 1.0);
		AddNpc(7, 147405, "Paladin Follower B3", "f_siauliai_11_re", -172.450882, 84.886703, 348.096252, -132.0, "SIAULIAI11RE_JEGAUS", "", "", -2, 1.0);
		AddNpc(8, 155044, "Monk3", "f_siauliai_11_re", -522.710022, 146.479996, 1371.619995, 89.0, "SIAULIAI11RE_PRANAS", "", "", -2, 1.0);
		AddNpc(9, 151078, "Orsha Soldier Female 2", "f_siauliai_11_re", 324.909363, 84.886703, 789.766235, -114.0, "SIAULIAI11RE_RARENA", "", "", -2, 1.0);
		AddNpc(10, 151079, "Orsha Soldier Female 3", "f_siauliai_11_re", 2366.019775, 171.9151, -501.562012, -116.0, "SIAULIAI11RE_ORWEN", "", "", -2, 1.0);
		AddNpc(11, 20060, "Orsha Soldier Male", "f_siauliai_11_re", 1488.017334, 209.715195, -557.625549, -82.0, "SIAULIAI11RE_NOTORESU", "", "", -2, 1.0);
		AddNpc(12, 155044, "Monk3", "f_siauliai_11_re", 393.543365, 84.886703, 1658.513794, -88.0, "SIAULIAI11RE_PRANAS_1", "", "", -2, 40.0);
		AddNpc(18, 153041, "Sack Of Crops", "f_siauliai_11_re", -648.848694, 146.483505, 1493.352417, 179.0, "", "", "", -2, 40.0);
		AddNpc(18, 153041, "Sack Of Crops", "f_siauliai_11_re", 1383.052979, 109.6371, -1305.285767, -162.0, "", "", "", -2, 40.0);
		AddNpc(18, 153041, "Sack Of Crops", "f_siauliai_11_re", 1376.28064, 109.6371, -1320.148926, 127.0, "", "", "", -2, 40.0);
		AddNpc(20, 147375, "Siauliai Tent", "f_siauliai_11_re", -641.781677, 146.483505, 1569.674194, -71.0, "", "", "", -2, 40.0);
		AddNpc(20, 147375, "Siauliai Tent", "f_siauliai_11_re", -544.96759, 146.483505, 1575.933472, -97.0, "", "", "", -2, 40.0);
		AddNpc(21, 46212, "Box", "f_siauliai_11_re", -574.466797, 146.483505, 1513.113892, 90.0, "SIAU11RE_MQ_06_NPC", "", "", -2, 40.0);
		AddNpc(22, 147375, "Siauliai Tent", "f_siauliai_11_re", 1447.407959, 109.6371, -1330.488037, -70.0, "", "", "", -2, 40.0);
		AddNpc(23, 47161, "Lost Stuff Of Vendor 2", "f_siauliai_11_re", 1316.0, 109.639999, -1300.0, 0.0, "", "", "", -2, 1.0);
		AddNpc(300, 155066, "Barbarian Submaster", "f_siauliai_11_re", 974.047241, 209.715195, 1089.258667, -48.0, "JOB_2_BARBARIAN_NPC", "", "", -2, 40.0);
		AddNpc(301, 151031, "Piece Of Wood", "f_siauliai_11_re", 597.259338, 280.574707, -654.09845, -98.0, "JOB_2_PELTASTA2_WOOD", "", "", -2, 40.0);
		AddNpc(301, 151031, "Piece Of Wood", "f_siauliai_11_re", 546.725586, 280.574707, -483.618713, -97.0, "JOB_2_PELTASTA2_WOOD", "", "", -2, 40.0);
		AddNpc(301, 151031, "Piece Of Wood", "f_siauliai_11_re", 592.107788, 280.574707, -374.413818, -112.0, "JOB_2_PELTASTA2_WOOD", "", "", -2, 40.0);
		AddNpc(301, 151031, "Piece Of Wood", "f_siauliai_11_re", 787.637085, 280.574707, -692.309631, -174.0, "JOB_2_PELTASTA2_WOOD", "", "", -2, 40.0);
		AddNpc(301, 151031, "Piece Of Wood", "f_siauliai_11_re", 914.012878, 280.574707, -601.560791, -151.0, "JOB_2_PELTASTA2_WOOD", "", "", -2, 40.0);
		AddNpc(301, 151031, "Piece Of Wood", "f_siauliai_11_re", 940.135986, 280.574707, -481.556213, -86.0, "JOB_2_PELTASTA2_WOOD", "", "", -2, 40.0);
		AddNpc(302, 147375, "Siauliai Tent", "f_siauliai_11_re", 1591.089111, 283.695801, 585.371338, -60.0, "", "", "", -2, 0.0);
		AddNpc(302, 147375, "Siauliai Tent", "f_siauliai_11_re", 1717.19519, 283.695801, 509.723267, 180.0, "", "", "", -2, 0.0);
		AddNpc(303, 154060, "Bonfireq1", "f_siauliai_11_re", 1633.730835, 283.695801, 522.147278, 0.0, "SIAU11RE_MQ_02_NPC_02", "", "", -2, 0.0);
		AddNpc(304, 47160, "Lost Stuff Of Vendor 1", "f_siauliai_11_re", 1703.211914, 283.695801, 331.348969, 0.0, "SIAU11RE_MQ_02_NPC_03", "", "", -2, 0.0);
		AddNpc(305, 147312, "Dropped Paper", "f_siauliai_11_re", 1566.048096, 283.695801, 469.154083, 0.0, "SIAU11RE_MQ_02_NPC_01", "", "", -2, 0.0);
		AddNpc(306, 20026, "", "f_siauliai_11_re", -334.503601, 102.588013, 1177.001221, 0.0, "", "SIAU11RE_MQ_05_NPC", "", -2, 50.0);
		AddNpc(307, 154065, "", "f_siauliai_11_re", 2623.815674, 209.715195, 388.670654, 0.0, "SIAU11RE_SQ_02_NPC", "", "", -2, 1.0);
		AddNpc(307, 154065, "", "f_siauliai_11_re", 2642.352539, 209.715195, 532.785095, 0.0, "SIAU11RE_SQ_02_NPC", "", "", -2, 1.0);
		AddNpc(307, 154065, "", "f_siauliai_11_re", 2661.311523, 209.715179, 698.503357, 0.0, "SIAU11RE_SQ_02_NPC", "", "", -2, 1.0);
		AddNpc(307, 154065, "", "f_siauliai_11_re", 2721.047119, 209.715195, 793.729431, 0.0, "SIAU11RE_SQ_02_NPC", "", "", -2, 1.0);
		AddNpc(307, 154065, "", "f_siauliai_11_re", 2807.665283, 209.715195, 891.840698, 0.0, "SIAU11RE_SQ_02_NPC", "", "", -2, 1.0);
		AddNpc(307, 154065, "", "f_siauliai_11_re", 2664.542725, 209.715195, 920.439575, 0.0, "SIAU11RE_SQ_02_NPC", "", "", -2, 1.0);
		AddNpc(307, 154065, "", "f_siauliai_11_re", 2525.73584, 209.715195, 871.898621, 0.0, "SIAU11RE_SQ_02_NPC", "", "", -2, 1.0);
		AddNpc(307, 154065, "", "f_siauliai_11_re", 2391.332764, 209.715195, 975.188477, 0.0, "SIAU11RE_SQ_02_NPC", "", "", -2, 1.0);
		AddNpc(307, 154065, "", "f_siauliai_11_re", 2300.056641, 209.715195, 1123.155029, 0.0, "SIAU11RE_SQ_02_NPC", "", "", -2, 1.0);
		AddNpc(307, 154065, "", "f_siauliai_11_re", 2181.918701, 209.715195, 1040.427734, 0.0, "SIAU11RE_SQ_02_NPC", "", "", -2, 1.0);
		AddNpc(307, 154065, "", "f_siauliai_11_re", 2278.875977, 209.71521, 908.751526, 0.0, "SIAU11RE_SQ_02_NPC", "", "", -2, 1.0);
		AddNpc(307, 154065, "", "f_siauliai_11_re", 2412.966553, 209.715195, 827.842285, 0.0, "SIAU11RE_SQ_02_NPC", "", "", -2, 1.0);
		AddNpc(307, 154065, "", "f_siauliai_11_re", 2394.85791, 209.715179, 679.816833, 0.0, "SIAU11RE_SQ_02_NPC", "", "", -2, 1.0);
		AddNpc(307, 154065, "", "f_siauliai_11_re", 2266.20166, 209.715195, 708.457275, 0.0, "SIAU11RE_SQ_02_NPC", "", "", -2, 1.0);
		AddNpc(307, 154065, "", "f_siauliai_11_re", 2327.016846, 209.715195, 544.923096, 0.0, "SIAU11RE_SQ_02_NPC", "", "", -2, 1.0);
		AddNpc(307, 154065, "", "f_siauliai_11_re", 2270.998291, 209.71521, 424.092316, 0.0, "SIAU11RE_SQ_02_NPC", "", "", -2, 1.0);
		AddNpc(307, 154065, "", "f_siauliai_11_re", 2404.364502, 209.715195, 333.179108, 0.0, "SIAU11RE_SQ_02_NPC", "", "", -2, 1.0);
		AddNpc(307, 154065, "", "f_siauliai_11_re", 2483.552734, 209.715195, 432.152557, 0.0, "SIAU11RE_SQ_02_NPC", "", "", -2, 1.0);
		AddNpc(307, 154065, "", "f_siauliai_11_re", 2485.07666, 209.715195, 589.61731, 0.0, "SIAU11RE_SQ_02_NPC", "", "", -2, 1.0);
		AddNpc(308, 47160, "Lost Stuff Of Vendor 1", "f_siauliai_11_re", -436.150787, 84.886703, 334.42038, 0.0, "SIAU11RE_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(308, 47160, "Lost Stuff Of Vendor 1", "f_siauliai_11_re", -933.722717, 146.0112, -13.784008, 0.0, "SIAU11RE_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(308, 47160, "Lost Stuff Of Vendor 1", "f_siauliai_11_re", -1061.255493, 146.0112, 220.605286, 0.0, "SIAU11RE_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(308, 47160, "Lost Stuff Of Vendor 1", "f_siauliai_11_re", -761.681152, 146.0112, 180.56958, 0.0, "SIAU11RE_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(308, 47160, "Lost Stuff Of Vendor 1", "f_siauliai_11_re", -1127.228394, 86.205452, 1580.909058, 0.0, "SIAU11RE_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(308, 47160, "Lost Stuff Of Vendor 1", "f_siauliai_11_re", -925.761536, 146.0112, 389.252533, 0.0, "SIAU11RE_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(308, 47160, "Lost Stuff Of Vendor 1", "f_siauliai_11_re", -27.632328, 84.886703, 822.784485, 0.0, "SIAU11RE_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(308, 47160, "Lost Stuff Of Vendor 1", "f_siauliai_11_re", -561.904846, 84.886703, 798.409546, 0.0, "SIAU11RE_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(308, 47160, "Lost Stuff Of Vendor 1", "f_siauliai_11_re", -524.81134, 84.886703, -22.300564, 0.0, "SIAU11RE_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(308, 47160, "Lost Stuff Of Vendor 1", "f_siauliai_11_re", -274.87442, 84.886703, 36.054676, 0.0, "SIAU11RE_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(308, 47160, "Lost Stuff Of Vendor 1", "f_siauliai_11_re", -1285.276611, 84.886703, 1001.271729, 0.0, "SIAU11RE_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(308, 47160, "Lost Stuff Of Vendor 1", "f_siauliai_11_re", 48.056454, 84.886703, 317.239899, 0.0, "SIAU11RE_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(308, 47160, "Lost Stuff Of Vendor 1", "f_siauliai_11_re", -1200.384399, 84.886703, 1272.640747, 0.0, "SIAU11RE_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(308, 47160, "Lost Stuff Of Vendor 1", "f_siauliai_11_re", -103.091393, 84.886703, 195.328049, 0.0, "SIAU11RE_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(308, 47160, "Lost Stuff Of Vendor 1", "f_siauliai_11_re", -1452.678223, 84.886703, 811.022461, 0.0, "SIAU11RE_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(308, 47160, "Lost Stuff Of Vendor 1", "f_siauliai_11_re", -954.864868, 84.886703, 647.177734, 0.0, "SIAU11RE_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(308, 47160, "Lost Stuff Of Vendor 1", "f_siauliai_11_re", -916.651123, 84.886703, 871.973877, 0.0, "SIAU11RE_SQ_08_NPC", "", "", -2, 1.0);
		AddNpc(309, 147403, "Paladin Follower B1", "f_siauliai_11_re", 345.999695, 84.886703, 1655.486084, -20.0, "SIAU11RE_TORNAVA", "", "", -2, 0.0);
		AddNpc(310, 147406, "Paladin Follower B4", "f_siauliai_11_re", 432.945343, 84.886703, 1680.066284, -86.0, "SIAU11RE_DARAMAUS", "", "", -2, 0.0);
		AddNpc(312, 154068, "Jolly", "f_siauliai_11_re", 346.057465, 84.886703, 796.858337, -69.0, "", "SIAU11RE_MQ_03_DOG", "", -2, 1.0);
		AddNpc(317, 20026, "", "f_siauliai_11_re", 1274.110474, 109.6371, -1367.164185, 0.0, "", "SIAU11RE_SQ_04_NPC", "", -2, 200.0);
		AddNpc(320, 147392, "Treasure Box 1", "f_siauliai_11_re", -1679.0, 150.0, 1345.0, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(321, 147392, "Treasure Box 1", "f_siauliai_11_re", -706.950012, 146.580002, 1474.329956, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(322, 154046, "Instanceddungeonentrynpc", "f_siauliai_11_re", 266.974091, 140.878296, 2093.729004, 0.0, "SIAULIAI_11_RE_TO_GUILD_FIELD_BOSS", "", "", -2, 40.0);
	}
}
