// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_siauliai_46_2 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(6, 147491, "Female Follower Of Austeja 1", "f_siauliai_46_2", -1220.556396, 121.9254, 4364.196289, -90.0, "SIAULIAI_46_2_MQ01_NPC", "", "", -2, 40.0);
		AddNpc(7, 151041, "Goddess Austeja", "f_siauliai_46_2", 1070.0, -73.0, 4905.0, -90.0, "SIAULIAI_46_2_AUSTEJA", "", "", -2, 40.0);
		AddNpc(8, 147414, "Obelisk", "f_siauliai_46_2", 1079.0, -73.0, 4705.0, -90.0, "SIAULIAI_46_2_SEAL", "", "", -2, 40.0);
		AddNpc(9, 20139, "Pablo", "f_siauliai_46_2", -1152.331543, 165.568207, 4832.515625, 0.0, "SIAULIAI_46_2_SQ_03_NPC", "", "", -2, 40.0);
		AddNpc(10, 147478, "Beekeeper3", "f_siauliai_46_2", -1507.169922, 121.9254, 4216.360352, 1.0, "SIAULIAI_46_2_SQ_05_NPC", "", "", -2, 40.0);
		AddNpc(11, 47203, "Large Discolored Grass Of Siauliai", "f_siauliai_46_2", 1075.0, 6.0, 5290.0, 1.0, "SIAULIAI_46_2_SQ_01_NPC", "", "", -2, 40.0);
		AddNpc(12, 151023, "Tree Branch", "f_siauliai_46_2", -1638.030151, 165.568207, 3754.249268, 30.0, "SIAULIAI_46_2_BEETREE", "", "", -2, 40.0);
		AddNpc(12, 151023, "Tree Branch", "f_siauliai_46_2", -1587.202148, 165.568207, 3779.21582, -45.0, "SIAULIAI_46_2_BEETREE", "", "", -2, 40.0);
		AddNpc(12, 151023, "Tree Branch", "f_siauliai_46_2", -1484.864624, 165.568207, 3875.619873, -120.0, "SIAULIAI_46_2_BEETREE", "", "", -2, 40.0);
		AddNpc(12, 151023, "Tree Branch", "f_siauliai_46_2", -2264.281494, 165.568207, 3238.183105, -60.0, "SIAULIAI_46_2_BEETREE", "", "", -2, 40.0);
		AddNpc(12, 151023, "Tree Branch", "f_siauliai_46_2", -2157.313965, 165.568207, 3290.182129, 0.0, "SIAULIAI_46_2_BEETREE", "", "", -2, 40.0);
		AddNpc(13, 20026, "", "f_siauliai_46_2", -676.0, 224.0, 3692.0, -90.0, "", "SIAULIAI_46_2_MQ_03_TRIGGER", "", -2, 250.0);
		AddNpc(14, 40095, "", "f_siauliai_46_2", 470.0, 39.0, 5734.0, 0.0, "SIAULIAI_46_2_SQ_04_01", "", "", -2, 40.0);
		AddNpc(15, 151032, "Scarecrow", "f_siauliai_46_2", 470.0, 39.0, 5734.0, 1.0, "", "SIAULIAI_46_2_SQ_04_01_AFTER", "", -2, 40.0);
		AddNpc(16, 147413, "Gele Plateau Barrier", "f_siauliai_46_2", -1954.0, 166.0, 3248.0, -90.0, "SIAULIAI_46_2_GUARDIAN", "", "", -2, 40.0);
		AddNpc(17, 151024, "Austeja Altar", "f_siauliai_46_2", -676.0, 224.0, 3692.0, -90.0, "", "", "", -2, 40.0);
		AddNpc(18, 151031, "Piece Of Wood", "f_siauliai_46_2", -1526.563232, 165.568207, 3599.97998, 10.0, "SIAULIAI_46_2_WOODPIECE", "", "", -2, 40.0);
		AddNpc(18, 151031, "Piece Of Wood", "f_siauliai_46_2", -1304.129761, 165.568207, 3588.928467, -30.0, "SIAULIAI_46_2_WOODPIECE", "", "", -2, 40.0);
		AddNpc(18, 151031, "Piece Of Wood", "f_siauliai_46_2", -1757.105103, 165.568207, 3125.288818, 30.0, "SIAULIAI_46_2_WOODPIECE", "", "", -2, 40.0);
		AddNpc(18, 151031, "Piece Of Wood", "f_siauliai_46_2", -1980.488403, 165.568207, 3057.131836, -50.0, "SIAULIAI_46_2_WOODPIECE", "", "", -2, 40.0);
		AddNpc(18, 151031, "Piece Of Wood", "f_siauliai_46_2", -1217.575684, 165.568207, 3778.556396, 100.0, "SIAULIAI_46_2_WOODPIECE", "", "", -2, 40.0);
		AddNpc(27, 147392, "Treasure Box 1", "f_siauliai_46_2", 920.98999, 5.56, 5094.939941, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(28, 47200, "Discolored Grass Of Siauliai", "f_siauliai_46_2", 834.301941, 0.72, 4385.114258, -34.0, "SIAULIAI462_HIDDENQ1_PLANT1", "", "", -2, 40.0);
		AddNpc(28, 47200, "Discolored Grass Of Siauliai", "f_siauliai_46_2", 922.671692, 0.72, 4149.369141, -34.0, "SIAULIAI462_HIDDENQ1_PLANT1", "", "", -2, 40.0);
		AddNpc(28, 47200, "Discolored Grass Of Siauliai", "f_siauliai_46_2", 1185.237671, 0.72, 4218.521484, -29.0, "SIAULIAI462_HIDDENQ1_PLANT1", "", "", -2, 40.0);
		AddNpc(28, 47200, "Discolored Grass Of Siauliai", "f_siauliai_46_2", 1148.790039, 3.15, 4387.850098, 0.0, "SIAULIAI462_HIDDENQ1_PLANT1", "", "", -2, 40.0);
		AddNpc(28, 47200, "Discolored Grass Of Siauliai", "f_siauliai_46_2", 1031.328735, 1.03, 4276.248047, 0.0, "SIAULIAI462_HIDDENQ1_PLANT1", "", "", -2, 40.0);
		AddNpc(28, 47200, "Discolored Grass Of Siauliai", "f_siauliai_46_2", 700.48999, 1.51, 4287.629883, 0.0, "SIAULIAI462_HIDDENQ1_PLANT1", "", "", -2, 40.0);
		AddNpc(29, 153067, "Bright Thorny Flower", "f_siauliai_46_2", -659.97998, 223.149994, 3470.439941, 0.0, "SIAULIAI462_HIDDENQ1_PLANT2", "", "", -2, 40.0);
		AddNpc(29, 153067, "Bright Thorny Flower", "f_siauliai_46_2", -462.54068, 223.149994, 3770.362793, 0.0, "SIAULIAI462_HIDDENQ1_PLANT2", "", "", -2, 40.0);
		AddNpc(29, 153067, "Bright Thorny Flower", "f_siauliai_46_2", -424.260803, 223.149994, 3576.099365, 0.0, "SIAULIAI462_HIDDENQ1_PLANT2", "", "", -2, 40.0);
		AddNpc(29, 153067, "Bright Thorny Flower", "f_siauliai_46_2", -798.599976, 223.149994, 3508.409912, 0.0, "SIAULIAI462_HIDDENQ1_PLANT2", "", "", -2, 40.0);
	}
}
