// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_siauliai_46_1 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(7, 147492, "Female Follower Of Austeja 2", "f_siauliai_46_1", -1352.521606, 261.961914, -156.1866, -90.0, "SIAULIAI_46_1_MQ01_NPC", "", "", -2, 40.0);
		AddNpc(8, 151024, "Austeja Altar", "f_siauliai_46_1", -130.0, 325.0, 10.0, 90.0, "SIAULIAI_46_1_ALTAR", "", "", -2, 40.0);
		AddNpc(9, 147501, "Broken Obelisk", "f_siauliai_46_1", -217.26741, 234.675293, -868.981079, -45.0, "SIAULIAI_46_1_DEADTREE01", "", "", -2, 40.0);
		AddNpc(10, 147501, "Broken Obelisk", "f_siauliai_46_1", 311.0, 212.0, -871.0, -90.0, "SIAULIAI_46_1_DEADTREE02", "", "", -2, 40.0);
		AddNpc(11, 20102, "Merchant 1", "f_siauliai_46_1", -1776.32251, 261.961914, -1027.201416, 1.0, "SIAULIAI_46_1_SQ_03_NPC", "", "", -2, 40.0);
		AddNpc(12, 147484, "Brindle", "f_siauliai_46_1", 1974.625732, 389.52121, 855.254395, -120.0, "SIAULIAI_46_1_SQ_04_NPC", "", "", -2, 40.0);
		AddNpc(13, 147493, "Chemist", "f_siauliai_46_1", 1714.453247, 389.809601, 889.589172, -90.0, "SIAULIAI_46_1_SQ_05_NPC", "", "", -2, 40.0);
		AddNpc(14, 47160, "Lost Stuff Of Vendor 1", "f_siauliai_46_1", -646.702332, 261.961914, -1296.509766, 0.0, "SIAULIAI_46_1_SQ_03_BAG01", "", "", -2, 40.0);
		AddNpc(15, 47160, "Lost Stuff Of Vendor 1", "f_siauliai_46_1", -280.234619, 261.961914, -369.477875, 0.0, "SIAULIAI_46_1_SQ_03_BAG02", "", "", -2, 40.0);
		AddNpc(16, 47161, "Lost Stuff Of Vendor 2", "f_siauliai_46_1", 945.762512, 258.763885, -168.528427, 0.0, "SIAULIAI_46_1_SQ_03_BAG03", "", "", -2, 40.0);
		AddNpc(17, 20026, "", "f_siauliai_46_1", 1110.467896, 390.792023, 466.917755, 0.0, "", "SIAULIAI_46_1_SQ_05_TRIGGER", "", -2, 40.0);
		AddNpc(17, 20026, "", "f_siauliai_46_1", 853.993347, 390.792114, 1024.04187, 0.0, "", "SIAULIAI_46_1_SQ_05_TRIGGER", "", -2, 40.0);
		AddNpc(17, 20026, "", "f_siauliai_46_1", 582.75531, 390.792114, 724.592407, 0.0, "", "SIAULIAI_46_1_SQ_05_TRIGGER", "", -2, 40.0);
		AddNpc(17, 20026, "", "f_siauliai_46_1", 602.789612, 390.792114, 1008.73822, 0.0, "", "SIAULIAI_46_1_SQ_05_TRIGGER", "", -2, 40.0);
		AddNpc(17, 20026, "", "f_siauliai_46_1", 913.392212, 390.792114, 485.612854, 0.0, "", "SIAULIAI_46_1_SQ_05_TRIGGER", "", -2, 40.0);
		AddNpc(17, 20026, "", "f_siauliai_46_1", 906.487854, 390.792114, 711.861389, 0.0, "", "SIAULIAI_46_1_SQ_05_TRIGGER", "", -2, 40.0);
		AddNpc(17, 20026, "", "f_siauliai_46_1", 758.41394, 390.792114, 293.908813, 0.0, "", "SIAULIAI_46_1_SQ_05_TRIGGER", "", -2, 40.0);
		AddNpc(17, 20026, "", "f_siauliai_46_1", 549.089844, 390.792114, 466.567444, 0.0, "", "SIAULIAI_46_1_SQ_05_TRIGGER", "", -2, 40.0);
		AddNpc(26, 47192, "Literature 3", "f_siauliai_46_1", 732.25708, 390.792114, 518.382507, -11.0, "SIAULIAI46_1_HIDDEN_EVENT", "", "", -2, 40.0);
		AddNpc(27, 147392, "Treasure Box 1", "f_siauliai_46_1", 954.0, 390.890015, 1020.97998, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(28, 147482, "Livia", "f_siauliai_46_1", -762.447266, 261.961914, -651.974792, 0.0, "CHAR420_STEP322_NPC1", "", "", -2, 40.0);
		AddNpc(29, 147473, "Mira", "f_siauliai_46_1", -725.751648, 261.961914, -582.553894, 0.0, "CHAR420_STEP322_NPC2", "", "", -2, 40.0);
		AddNpc(30, 46212, "Box", "f_siauliai_46_1", -754.357788, 261.961914, -601.806824, 89.0, "CHAR420_STEP322_NPC3", "", "", -2, 40.0);
		AddNpc(31, 151028, "Bucket", "f_siauliai_46_1", -674.846985, 261.961914, -734.506897, 0.0, "CHAR420_STEP322_NPC4", "", "", -2, 40.0);
		AddNpc(32, 147458, "Drums", "f_siauliai_46_1", -690.627747, 261.961914, -700.562134, 0.0, "CHAR420_STEP322_NPC5", "", "", -2, 40.0);
	}
}
