// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_f_tableland_11_1 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(1, 20150, "Veteran Miner 2", "f_tableland_11_1", -2319.810059, 801.669983, 2045.689941, -76.0, "TABLELAND_11_1_CART_MANAGER", "", "", -2, 30.0);
		AddNpc(12, 155051, "Plateau Magic Circle Activation Device", "f_tableland_11_1", -403.536224, -39.64056, -785.844604, 0.0, "TABLELAND_11_1_PAIR", "", "", -2, 40.0);
		AddNpc(18, 156022, "Male Necromancer 2", "f_tableland_11_1", 370.144653, -163.647736, -1293.309204, -90.0, "TABLELAND_11_1_ADOMAS", "TABLELAND_11_1_SQ_01_BALLOON", "", -2, 80.0);
		AddNpc(19, 155012, "Leather Bag", "f_tableland_11_1", 392.104584, -163.647736, -1270.231201, 0.0, "TABLELAND_11_1_ADOMAS_BAG", "", "", -2, 40.0);
		AddNpc(21, 156020, "Female Necromancer", "f_tableland_11_1", -1050.656494, 0.108856, -426.243195, 0.0, "TABLELAND_11_1_LEMIJA", "", "", -2, 400.0);
		AddNpc(22, 20026, "", "f_tableland_11_1", 369.753937, -163.647736, -1296.102173, 0.0, "", "TABLELAND_11_1_SQ_02_TRIG", "", -2, 80.0);
		AddNpc(23, 20024, "", "f_tableland_11_1", -195.534225, 56.16, 102.360443, 0.0, "TABLELAND_11_1_SQ_03_LAST", "", "", -2, 40.0);
		AddNpc(24, 20024, "", "f_tableland_11_1", 78.965515, 56.16, -265.919281, 0.0, "TABLELAND_11_1_SQ_03_LOCK", "", "", -2, 40.0);
		AddNpc(25, 20024, "", "f_tableland_11_1", 148.372971, 56.159515, 23.163054, 0.0, "TABLELAND_11_1_SQ_03_FOOD", "", "", -2, 40.0);
		AddNpc(26, 20024, "", "f_tableland_11_1", -331.932373, 56.159515, -208.264145, 0.0, "TABLELAND_11_1_SQ_03_LETTER", "", "", -2, 40.0);
		AddNpc(27, 20024, "", "f_tableland_11_1", 20.329351, 56.159515, 53.671749, 0.0, "TABLELAND_11_1_SQ_03_BLOOD", "", "", -2, 40.0);
		AddNpc(28, 20024, "", "f_tableland_11_1", -186.907883, 56.159515, 33.40807, 0.0, "TABLELAND_11_1_SQ_03_TRACE", "", "", -2, 40.0);
		AddNpc(29, 20026, "", "f_tableland_11_1", 1111.648804, 288.619598, 538.717346, 0.0, "", "TABLELAND_11_1_SQ_04_TRIG", "", -2, 200.0);
		AddNpc(30, 156020, "Female Necromancer", "f_tableland_11_1", 1133.519409, 288.619598, 465.867004, 90.0, "TABLELAND_11_1_LEMIJA2", "", "", -2, 40.0);
		AddNpc(31, 147362, "", "f_tableland_11_1", -186.774994, 56.159515, 619.180054, 0.0, "", "TABLELAND_11_1_SETPOS", "", -2, 100.0);
		AddNpc(31, 147362, "", "f_tableland_11_1", -244.950455, 56.159515, 473.252197, 0.0, "", "TABLELAND_11_1_SETPOS", "", -2, 100.0);
		AddNpc(31, 147362, "", "f_tableland_11_1", 56.090687, 56.159515, 685.944092, 0.0, "", "TABLELAND_11_1_SETPOS", "", -2, 100.0);
		AddNpc(31, 147362, "", "f_tableland_11_1", -146.054901, 56.159515, 624.733948, 0.0, "", "TABLELAND_11_1_SETPOS", "", -2, 100.0);
		AddNpc(31, 147362, "", "f_tableland_11_1", -150.996124, 56.159515, 435.692932, 0.0, "", "TABLELAND_11_1_SETPOS", "", -2, 100.0);
		AddNpc(31, 147362, "", "f_tableland_11_1", 18.88575, 56.159515, 596.435974, 0.0, "", "TABLELAND_11_1_SETPOS", "", -2, 100.0);
		AddNpc(31, 147362, "", "f_tableland_11_1", -78.433578, 56.159515, 528.132813, 0.0, "", "TABLELAND_11_1_SETPOS", "", -2, 100.0);
		AddNpc(32, 20049, "", "f_tableland_11_1", -124.24556, 56.159515, 331.553802, -166.0, "", "TABLELAND_11_1_DARK_WALL", "", -2, 40.0);
		AddNpc(32, 20049, "", "f_tableland_11_1", -155.511337, 56.134491, 730.301819, 3.0, "", "TABLELAND_11_1_DARK_WALL", "", -2, 40.0);
		AddNpc(32, 20049, "", "f_tableland_11_1", -165.556946, 58.356575, 765.863403, 3.0, "", "TABLELAND_11_1_DARK_WALL", "", -2, 40.0);
		AddNpc(33, 156019, "Male Necromancer", "f_tableland_11_1", 24.559479, 56.159515, 603.830933, 90.0, "TABLELAND_11_1_FAUSTAS", "", "", -2, 40.0);
		AddNpc(34, 156021, "Female Cryomancer", "f_tableland_11_1", 25.828306, 56.159515, 650.243469, -135.0, "", "TABLELAND_11_1_ELEMA", "", -2, 0.0);
		AddNpc(35, 20025, "", "f_tableland_11_1", 26.309486, 56.159515, 623.399414, 0.0, "", "TABLELAND_11_1_KRUVINA", "", -2, 200.0);
		AddNpc(36, 47251, "Royal Mausoleum Tombstone01", "f_tableland_11_1", 20.599476, 56.159515, 681.506531, -78.0, "TABLELAND_11_1_RIP", "", "", -2, 40.0);
		AddNpc(37, 156020, "Female Necromancer", "f_tableland_11_1", -9.446407, 56.159515, 657.301392, -45.0, "TABLELAND_11_1_LEMIJA3", "", "", -2, 40.0);
		AddNpc(38, 156019, "Male Necromancer", "f_tableland_11_1", 24.543121, 56.159515, 603.873474, 90.0, "", "TABLELAND_11_1_FAUSTAS_DOWN", "", -2, 0.0);
		AddNpc(39, 20026, "", "f_tableland_11_1", -165.665207, 58.261562, 765.175171, 3.0, "", "TABLELAND_11_1_SQ_07_BACK", "", -2, 60.0);
		AddNpc(40, 156041, "Empty Npc 3", "f_tableland_11_1", 24.170418, 56.159515, 603.837158, 0.0, "", "TABLELAND_11_1_DARK_EFF", "", -2, 0.0);
		AddNpc(40, 156041, "Empty Npc 3", "f_tableland_11_1", 25.304487, 56.159515, 653.445923, 0.0, "", "TABLELAND_11_1_DARK_EFF", "", -2, 0.0);
		AddNpc(41, 156019, "Male Necromancer", "f_tableland_11_1", 33.174747, 56.159515, 639.394775, -135.0, "", "TABLELAND_11_1_FAUSTAS_DOWN2", "", -2, 40.0);
		AddNpc(42, 20026, "", "f_tableland_11_1", 644.878784, 288.619598, 695.290344, 0.0, "", "TABLELAND_11_1_SQ_07_WRONG", "", -2, 40.0);
		AddNpc(43, 156020, "Female Necromancer", "f_tableland_11_1", -118.297272, 56.159515, 317.390411, 90.0, "TABLELAND_11_1_SQ_07_ENDNPC", "", "", -2, 40.0);
		AddNpc(44, 20026, "", "f_tableland_11_1", -247.344559, -39.64056, -794.53186, 0.0, "JOB_DRAGOON_8_1_KEY", "", "", -2, 40.0);
		AddNpc(44, 20026, "", "f_tableland_11_1", -586.310974, -91.576935, -1258.334473, 0.0, "JOB_DRAGOON_8_1_KEY", "", "", -2, 40.0);
		AddNpc(44, 20026, "", "f_tableland_11_1", -858.526428, -91.576935, -927.666687, 0.0, "JOB_DRAGOON_8_1_KEY", "", "", -2, 40.0);
		AddNpc(44, 20026, "", "f_tableland_11_1", -982.780273, 0.108856, -320.196259, 0.0, "JOB_DRAGOON_8_1_KEY", "", "", -2, 40.0);
		AddNpc(44, 20026, "", "f_tableland_11_1", -642.802002, 0.108856, -269.62085, 0.0, "JOB_DRAGOON_8_1_KEY", "", "", -2, 40.0);
		AddNpc(44, 20026, "", "f_tableland_11_1", -835.111206, -109.806122, 371.822235, 0.0, "JOB_DRAGOON_8_1_KEY", "", "", -2, 40.0);
		AddNpc(44, 20026, "", "f_tableland_11_1", -207.031082, 56.159515, -59.384323, 0.0, "JOB_DRAGOON_8_1_KEY", "", "", -2, 40.0);
		AddNpc(44, 20026, "", "f_tableland_11_1", 162.05188, 56.159515, -207.617126, 0.0, "JOB_DRAGOON_8_1_KEY", "", "", -2, 40.0);
		AddNpc(44, 20026, "", "f_tableland_11_1", -33.377083, 56.159515, 579.486816, 0.0, "JOB_DRAGOON_8_1_KEY", "", "", -2, 40.0);
		AddNpc(44, 20026, "", "f_tableland_11_1", -168.501312, 94.53653, 1118.924194, 0.0, "JOB_DRAGOON_8_1_KEY", "", "", -2, 40.0);
		AddNpc(44, 20026, "", "f_tableland_11_1", 76.405708, 94.53653, 1296.123535, 0.0, "JOB_DRAGOON_8_1_KEY", "", "", -2, 40.0);
		AddNpc(44, 20026, "", "f_tableland_11_1", -94.322029, 94.427673, 1943.491821, 0.0, "JOB_DRAGOON_8_1_KEY", "", "", -2, 40.0);
		AddNpc(44, 20026, "", "f_tableland_11_1", 229.196014, 94.427673, 2039.28418, 0.0, "JOB_DRAGOON_8_1_KEY", "", "", -2, 40.0);
		AddNpc(44, 20026, "", "f_tableland_11_1", 720.721985, 288.619598, 626.804749, 0.0, "JOB_DRAGOON_8_1_KEY", "", "", -2, 40.0);
		AddNpc(44, 20026, "", "f_tableland_11_1", 809.890564, 181.880524, 185.211594, 0.0, "JOB_DRAGOON_8_1_KEY", "", "", -2, 40.0);
		AddNpc(44, 20026, "", "f_tableland_11_1", 284.86795, 56.159515, -70.870392, 0.0, "JOB_DRAGOON_8_1_KEY", "", "", -2, 40.0);
		AddNpc(1000, 147392, "Treasure Box 1", "f_tableland_11_1", -680.030029, -109.709999, 584.72998, -135.0, "TREASUREBOX_LV", "", "", -2, 0.0);
	}
}
