// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_id_catacomb_04 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(4, 147500, "Warp Portal", "id_catacomb_04", 3279.531494, 370.801086, -948.331543, 135.0, "CATACOMB_04_SECRETOUT", "", "", -2, 30.0);
		AddNpc(6, 147475, "Tomb Mini Cube", "id_catacomb_04", -423.866028, 272.515411, -1760.794678, 0.0, "CATACOMB_04_OBJ_01", "", "", -2, 40.0);
		AddNpc(7, 154000, "Teleport Magic Circle", "id_catacomb_04", -1566.0, 346.355408, -756.0, 0.0, "CATACOMB_04_OBJ_02", "", "", -2, 40.0);
		AddNpc(8, 147413, "Gele Plateau Barrier", "id_catacomb_04", 617.0, 285.28421, 1192.0, 0.0, "CATACOMB_04_OBJ_03", "", "", -2, 40.0);
		AddNpc(9, 151058, "Spatial Magic Stone", "id_catacomb_04", 1589.0, 265.308411, 861.0, 90.0, "CATACOMB_04_OBJ_04", "", "", -2, 40.0);
		AddNpc(10, 147469, "No Shadow Npc", "id_catacomb_04", -774.0, 264.895599, 952.0, 0.0, "CATACOMB_04_OBJ_05", "", "", -2, 40.0);
		AddNpc(11, 147500, "Warp Portal", "id_catacomb_04", 1395.222046, 419.928802, -154.549911, 0.0, "CATACOMB_04_OBJ_06", "", "", -2, 40.0);
		AddNpc(12, 151052, "Royal Mausoleum Desk2", "id_catacomb_04", 2918.0, 385.555908, -1596.0, 135.0, "CATACOMB_04_OBJ_07", "", "", -2, 40.0);
		AddNpc(1000, 147392, "Treasure Box 1", "id_catacomb_04", -126.309998, 265.0, 1200.430054, -135.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(1001, 152057, "No Shadow Npc Tall", "id_catacomb_04", 2068.551025, 306.679993, 1249.536865, 0.0, "HT_CATACOMB_04_SKULL", "", "", -2, 10.0);
		AddNpc(1001, 152057, "No Shadow Npc Tall", "id_catacomb_04", 2069.956299, 307.279999, 1197.62085, 0.0, "HT_CATACOMB_04_SKULL", "", "", -2, 10.0);
		AddNpc(1001, 152057, "No Shadow Npc Tall", "id_catacomb_04", 2071.464355, 307.820007, 1151.012329, 0.0, "HT_CATACOMB_04_SKULL", "", "", -2, 10.0);
		AddNpc(1001, 152057, "No Shadow Npc Tall", "id_catacomb_04", 2069.149902, 308.359985, 973.76001, 0.0, "HT_CATACOMB_04_SKULL", "", "", -2, 10.0);
		AddNpc(1001, 152057, "No Shadow Npc Tall", "id_catacomb_04", 2069.725098, 308.359985, 885.455078, 0.0, "HT_CATACOMB_04_SKULL", "", "", -2, 10.0);
	}
}
