// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_id_catacomb_02 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(4, 147449, "Grita", "id_catacomb_02", -697.0, 278.972504, 1275.0, -90.0, "CATACOMB_02_NPC_01", "", "", -2, 40.0);
		AddNpc(6, 151056, "Magic Stone Of Mutuality", "id_catacomb_02", -876.0, 278.972595, 1321.0, 0.0, "CATACOMB_02_OBJ_01", "", "", -2, 40.0);
		AddNpc(7, 47190, "Literature 1", "id_catacomb_02", -2326.116699, 325.790863, -1219.337158, 0.0, "CATACOMB_02_RECORD_01", "", "", -2, 40.0);
		AddNpc(8, 47191, "Literature 2", "id_catacomb_02", -2138.615723, 305.698944, -1365.071777, 135.0, "CATACOMB_02_RECORD_02", "", "", -2, 40.0);
		AddNpc(9, 47192, "Literature 3", "id_catacomb_02", -1954.895996, 286.790985, -1537.223755, 90.0, "CATACOMB_02_RECORD_03", "", "", -2, 40.0);
		AddNpc(10, 147311, "Book", "id_catacomb_02", -2294.926025, 305.698914, -1468.334717, 90.0, "CATACOMB_02_BOOK_01", "", "", -2, 40.0);
		AddNpc(11, 147311, "Book", "id_catacomb_02", -1899.912109, 305.790833, -1090.485718, 0.0, "CATACOMB_02_BOOK_02", "", "", -2, 40.0);
		AddNpc(12, 147312, "Dropped Paper", "id_catacomb_02", -2132.07959, 325.790985, -1194.384277, 0.0, "CATACOMB_02_BOOK_03", "", "", -2, 40.0);
		AddNpc(13, 45321, "Holy Ark", "id_catacomb_02", -1155.565918, 325.790985, -85.389175, 0.0, "CATACOMB_02_OBJ_02", "", "", -2, 40.0);
		AddNpc(13, 45321, "Holy Ark", "id_catacomb_02", -1069.245483, 325.790985, -128.404205, 90.0, "CATACOMB_02_OBJ_02", "", "", -2, 40.0);
		AddNpc(13, 45321, "Holy Ark", "id_catacomb_02", -605.696106, 325.790985, 402.216736, 180.0, "CATACOMB_02_OBJ_02", "", "", -2, 40.0);
		AddNpc(14, 45321, "Holy Ark", "id_catacomb_02", -604.499817, 325.791046, 319.083374, 180.0, "CATACOMB_02_OBJ_03", "CATACOMB_02_OBJ_03", "", -2, 100.0);
		AddNpc(15, 151057, "Magic Generating Stones", "id_catacomb_02", -206.928513, 305.497711, 1009.759888, 0.0, "CATACOMB_02_OBJ_04", "", "", -2, 40.0);
		AddNpc(15, 151057, "Magic Generating Stones", "id_catacomb_02", -207.23703, 303.705414, 1573.155762, 0.0, "CATACOMB_02_OBJ_04", "", "", -2, 40.0);
		AddNpc(15, 151057, "Magic Generating Stones", "id_catacomb_02", 70.045105, 287.500153, 1535.151855, 0.0, "CATACOMB_02_OBJ_04", "", "", -2, 40.0);
		AddNpc(15, 151057, "Magic Generating Stones", "id_catacomb_02", 80.987801, 268.052185, 1250.03772, 0.0, "CATACOMB_02_OBJ_04", "", "", -2, 40.0);
		AddNpc(15, 151057, "Magic Generating Stones", "id_catacomb_02", 375.496216, 267.362915, 1003.516418, 0.0, "CATACOMB_02_OBJ_04", "", "", -2, 40.0);
		AddNpc(15, 151057, "Magic Generating Stones", "id_catacomb_02", 373.748535, 268.052185, 1273.623657, 0.0, "CATACOMB_02_OBJ_04", "", "", -2, 40.0);
		AddNpc(16, 151057, "Magic Generating Stones", "id_catacomb_02", -163.245926, 284.706085, 1286.296265, 0.0, "CATACOMB_02_OBJ_05_1", "", "", -2, 40.0);
		AddNpc(17, 151057, "Magic Generating Stones", "id_catacomb_02", 88.793449, 287.651611, 962.531982, 0.0, "CATACOMB_02_OBJ_05_2", "", "", -2, 40.0);
		AddNpc(18, 151057, "Magic Generating Stones", "id_catacomb_02", 387.522766, 287.500153, 1577.788696, 0.0, "CATACOMB_02_OBJ_05_3", "", "", -2, 40.0);
		AddNpc(19, 151057, "Magic Generating Stones", "id_catacomb_02", -297.00592, 349.63031, -1016.422974, 0.0, "CATACOMB_02_OBJ_06", "CATACOMB_02_OBJ_06", "", -2, 120.0);
		AddNpc(19, 151057, "Magic Generating Stones", "id_catacomb_02", -258.073181, 328.582367, -741.78241, 0.0, "CATACOMB_02_OBJ_06", "CATACOMB_02_OBJ_06", "", -2, 120.0);
		AddNpc(19, 151057, "Magic Generating Stones", "id_catacomb_02", -284.174072, 348.076813, -447.416351, 0.0, "CATACOMB_02_OBJ_06", "CATACOMB_02_OBJ_06", "", -2, 120.0);
		AddNpc(19, 151057, "Magic Generating Stones", "id_catacomb_02", 4.134962, 331.94931, -1063.694702, 0.0, "CATACOMB_02_OBJ_06", "CATACOMB_02_OBJ_06", "", -2, 120.0);
		AddNpc(19, 151057, "Magic Generating Stones", "id_catacomb_02", 7.347023, 311.94931, -765.484253, 0.0, "CATACOMB_02_OBJ_06", "CATACOMB_02_OBJ_06", "", -2, 120.0);
		AddNpc(19, 151057, "Magic Generating Stones", "id_catacomb_02", 6.946754, 331.94931, -475.535065, 0.0, "CATACOMB_02_OBJ_06", "CATACOMB_02_OBJ_06", "", -2, 120.0);
		AddNpc(19, 151057, "Magic Generating Stones", "id_catacomb_02", 283.539124, 311.949341, -1023.636475, 0.0, "CATACOMB_02_OBJ_06", "CATACOMB_02_OBJ_06", "", -2, 120.0);
		AddNpc(19, 151057, "Magic Generating Stones", "id_catacomb_02", 285.644348, 311.94931, -760.30072, 0.0, "CATACOMB_02_OBJ_06", "CATACOMB_02_OBJ_06", "", -2, 120.0);
		AddNpc(19, 151057, "Magic Generating Stones", "id_catacomb_02", 304.354218, 331.94931, -461.413391, 0.0, "CATACOMB_02_OBJ_06", "CATACOMB_02_OBJ_06", "", -2, 120.0);
		AddNpc(20, 147305, "Mage Tower Defense", "id_catacomb_02", 1480.973145, 317.439148, 437.504364, 0.0, "CATACOMB_02_OBJ_07", "", "", -2, 40.0);
		AddNpc(21, 147305, "Mage Tower Defense", "id_catacomb_02", 1473.301392, 317.439087, 151.747162, 0.0, "CATACOMB_02_OBJ_08", "", "", -2, 40.0);
		AddNpc(22, 147305, "Mage Tower Defense", "id_catacomb_02", 1778.455811, 317.439148, 141.266617, 0.0, "CATACOMB_02_OBJ_09", "", "", -2, 40.0);
		AddNpc(23, 147305, "Mage Tower Defense", "id_catacomb_02", 1773.041138, 317.439087, 432.130554, 0.0, "CATACOMB_02_OBJ_10", "", "", -2, 40.0);
		AddNpc(24, 151059, "Catacombs Grave01", "id_catacomb_02", 1636.169922, 327.736908, 300.617157, -45.0, "CATACOMB_02_OBJ_11", "", "", -2, 40.0);
		AddNpc(27, 151057, "Magic Generating Stones", "id_catacomb_02", -163.245926, 284.706085, 1286.296265, 0.0, "CATACOMB_02_OBJ_05_1_AFTER", "", "", -2, 40.0);
		AddNpc(28, 151057, "Magic Generating Stones", "id_catacomb_02", 88.793449, 287.651611, 962.531982, 0.0, "CATACOMB_02_OBJ_05_2_AFTER", "", "", -2, 40.0);
		AddNpc(29, 151057, "Magic Generating Stones", "id_catacomb_02", 387.522766, 287.500153, 1577.788696, 0.0, "CATACOMB_02_OBJ_05_3_AFTER", "", "", -2, 40.0);
		AddNpc(1000, 147392, "Treasure Box 1", "id_catacomb_02", -1200.890015, 289.920013, 1646.150024, 135.0, "TREASUREBOX_LV", "", "", -2, 0.0);
	}
}
