// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_id_catacomb_01 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(601, 147469, "No Shadow Npc", "id_catacomb_01", -229.127426, 935.687134, -2565.841064, 0.0, "CATACOMB_01_SPIRIT_01", "", "", -2, 40.0);
		AddNpc(601, 147469, "No Shadow Npc", "id_catacomb_01", -142.840469, 936.256714, -1030.828125, 0.0, "CATACOMB_01_SPIRIT_01", "", "", -2, 40.0);
		AddNpc(603, 20135, "Foreseeing Owl", "id_catacomb_01", 1658.325317, 887.589172, -621.829224, -90.0, "", "CATACOMB_01_SPIRIT_02", "", -2, 60.0);
		AddNpc(605, 147392, "Treasure Box 1", "id_catacomb_01", -217.55751, 960.687195, -1804.255981, -45.0, "CATACOMB_01_SPIRIT_03", "", "", -2, 40.0);
		AddNpc(606, 20026, "", "id_catacomb_01", -535.986389, 955.06427, 867.044617, 0.0, "", "CATACOMB_01_EVILAURA_01", "", -2, 40.0);
		AddNpc(606, 20026, "", "id_catacomb_01", -470.992584, 933.476135, 1145.750854, 0.0, "", "CATACOMB_01_EVILAURA_01", "", -2, 40.0);
		AddNpc(606, 20026, "", "id_catacomb_01", -525.561646, 952.168884, 1413.986206, 0.0, "", "CATACOMB_01_EVILAURA_01", "", -2, 40.0);
		AddNpc(606, 20026, "", "id_catacomb_01", -235.325836, 935.687073, 826.016724, 0.0, "", "CATACOMB_01_EVILAURA_01", "", -2, 40.0);
		AddNpc(606, 20026, "", "id_catacomb_01", -225.382477, 915.687073, 1121.133667, 0.0, "", "CATACOMB_01_EVILAURA_01", "", -2, 40.0);
		AddNpc(606, 20026, "", "id_catacomb_01", -216.222, 935.687073, 1359.507202, 0.0, "", "CATACOMB_01_EVILAURA_01", "", -2, 40.0);
		AddNpc(606, 20026, "", "id_catacomb_01", 44.462715, 916.151978, 866.058472, 0.0, "", "CATACOMB_01_EVILAURA_01", "", -2, 40.0);
		AddNpc(606, 20026, "", "id_catacomb_01", 47.693233, 919.197571, 1128.774292, 0.0, "", "CATACOMB_01_EVILAURA_01", "", -2, 40.0);
		AddNpc(606, 20026, "", "id_catacomb_01", 79.690804, 937.081726, 1415.757324, 0.0, "", "CATACOMB_01_EVILAURA_01", "", -2, 40.0);
		AddNpc(609, 152009, "Pilgrim Npc Woman'S Tomb", "id_catacomb_01", 1611.626953, 868.598633, -955.189514, -90.0, "CATACOMB_01_TOMBSTONE_01", "", "", -2, 40.0);
		AddNpc(610, 152009, "Pilgrim Npc Woman'S Tomb", "id_catacomb_01", -641.769897, 935.687073, -615.21814, -90.0, "CATACOMB_01_TOMBSTONE_02", "", "", -2, 40.0);
		AddNpc(611, 147463, "Stone Slabs", "id_catacomb_01", 995.576355, 915.997498, 2860.073242, 0.0, "CATACOMB_01_TOMBSTONE_03", "", "", -2, 40.0);
		AddNpc(612, 40070, "Bulletin Board", "id_catacomb_01", -174.096222, 935.687073, -2942.401611, -45.0, "CATACOMB_01_BOARD_01", "", "", -2, 40.0);
		AddNpc(613, 147463, "Stone Slabs", "id_catacomb_01", 99.65654, 935.687195, 1985.887695, 0.0, "CATACOMB_01_TOMBSTONE_04", "", "", -2, 40.0);
		AddNpc(700, 147392, "Treasure Box 1", "id_catacomb_01", 180.110001, 935.789978, -523.76001, 0.0, "TREASUREBOX_LV", "", "", -2, 0.0);
		AddNpc(701, 147311, "Book", "id_catacomb_01", -571.365723, 972.349976, -1099.729614, -62.0, "LOWLV_MASTER_ENCY_SQ_30_BOOK", "", "", -2, 40.0);
		AddNpc(702, 20026, "", "id_catacomb_01", 923.417542, 922.280029, 3010.378906, 0.0, "", "LOWLV_MASTER_ENCY_SQ_40", "", -2, 150.0);
		AddNpc(703, 20026, "", "id_catacomb_01", -231.583878, 935.700012, -1110.486328, 0.0, "", "LOWLV_BOASTER_SQ_50", "", -2, 100.0);
		AddNpc(704, 40095, "", "id_catacomb_01", 240.416809, 974.663147, 2901.986816, 0.0, "", "EXPLORER_MISLE9", "", -2, 20.0);
		AddNpc(705, 147357, "Barrier Of Paladin Temple A", "id_catacomb_01", -61.0, 935.0, -2364.0, -35.0, "EXORCIST_JOB_QUEST_OBJ_START", "", "", -2, 40.0);
		AddNpc(706, 155099, "Great Cathedral Footstep(Remove The Obb)", "id_catacomb_01", -91.860001, 935.690002, -2376.169922, 0.0, "", "EXORCIST_PLACE_HIDE", "", -2, 40.0);
	}
}
