// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_p_catacomb_1 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(5, 40070, "Bulletin Board", "p_catacomb_1", -3.177528, 267.536194, 1062.539185, 0.0, "UPPER_WARNING_P_CATACOMB_1", "", "", -2, 40.0);
		AddNpc(6, 147446, "Necromancer Master", "p_catacomb_1", 193.182846, 260.225494, 82.648132, -90.0, "JOB_NECRO4_NPC", "", "", -2, 40.0);
	}
}
