// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_p_cathedral_1 : GeneralScript
{
	protected override void Load()
	{
		AddNpc(4, 40070, "Bulletin Board", "p_cathedral_1", 10.105087, 0.4, 295.002258, 0.0, "UPPER_WARNING_P_CATHEDRAL_1", "", "", -2, 40.0);
		AddNpc(5, 153173, "Miko Master", "p_cathedral_1", 580.616577, 0.399994, -320.262512, -90.0, "MIKO_MASTER", "", "", -2, 40.0);
		AddNpc(6, 151018, "No Shadow Npc", "p_cathedral_1", 541.788269, 0.399994, -321.345215, 0.0, "MIKO_SOUL_SPIRIT", "", "", -2, 40.0);
	}
}
