// <auto-generated>
// Project_Epic NPC import. Regenerate with:
//   python server/app/tools/import-project-epic-npcs.py --project-epic <path>
// </auto-generated>

using GuiltineSin.Zone.Scripting;
using static GuiltineSin.Zone.Scripting.Shortcuts;


public class ProjectEpicNpc_test_zone : GeneralScript
{
	protected override void Load()
	{
		AddNpc(2, 20113, "Uska", "test_zone", -40.0, 0.0, 126.0, 0.0, "TEST_RANK", "", "", -2, 40.0);
		AddNpc(3, 20113, "Uska", "test_zone", -35.0, 0.0, 81.0, 0.0, "TEST_TP_SHOP", "", "", -2, 40.0);
		AddNpc(15, 20011, "Supply Soldier", "test_zone", -51.0, 0.0, -310.0, 0.0, "", "", "", -2, 40.0);
		AddNpc(31, 48021, "F Katyn Owl01 Fall", "test_zone", -59.0, 0.0, 288.0, 280.0, "", "", "", -2, 40.0);
		AddNpc(32, 48022, "F Katyn Owl02 Fall", "test_zone", 40.0, 0.0, 388.0, 280.0, "", "", "", -2, 40.0);
		AddNpc(33, 48023, "F Katyn Owl03 Fall", "test_zone", 153.0, 0.0, 501.0, 280.0, "", "", "", -2, 40.0);
		AddNpc(34, 48024, "F Katyn Owl04 Fall", "test_zone", 246.0, 0.0, 594.0, 280.0, "", "", "", -2, 40.0);
		AddNpc(35, 47085, "Thorn Forest Gate 5", "test_zone", 342.0, 0.0, 690.0, -45.0, "", "", "", -2, 40.0);
		AddNpc(36, 47086, "Thorn Forest Gate 6", "test_zone", 391.0, 0.0, 456.0, -45.0, "", "", "", -2, 40.0);
		AddNpc(37, 20016, "Western Woods Scout", "test_zone", -713.0, 0.0, -611.0, 0.0, "IMC_GUARD", "", "", -2, 40.0);
		AddNpc(108, 40130, "Statue Of Goddess Ausrine", "test_zone", 38.0, 0.0, 190.0, 0.0, "SKILLPOINTUP2", "", "", -2, 100.0);
	}
}
